### ISSUE TITLE
function IsPythonVersionRegistered does not recognise 64 bit version 3.8.

### ISSUE THREAD

**Issue by FactoryXCode** [pyscripter/python4delphi#100]
Hi,

The version check method `function IsPythonVersionRegistered` does not return the correct python 64 bit version (3.8).

It searches for all or single users, but the values to search for in the registry are wrong. See attached image.
![reg_python_381_64bit](https://user-images.githubusercontent.com/41634066/72159884-9af7fb80-33bd-11ea-8562-ec185e19bb24.jpg)

Tested on Windows 10 64bit, version 1909. Delphi 10.3.3

**Comment by pyscripter** [comment]
What one is supposed to see in the image?

**Comment by FactoryXCode** [comment]
This is the registration section in the registry of Python 3.8.1, 64-bit (the latest version) for multiple users.

**Comment by pyscripter** [comment]
You can only use the 64-bit version of Python with the 64-bit Delphi programs and the 32-bit version of python with 32-bit Delphi programs.   Are you compiling your Delphi program for 64-bits??

**Comment by FactoryXCode** [comment]
No, 32 bits. Both 32 or 64 does not matter, the function is not correct to fiddle out the correct python version installed. The assumption of CPU86 is not correct. An installed version of python is not depended on the OS architecture or CPU, and that is what the function implies. So, it returns an error 193: "could not open Dll "python38.dll""

**Comment by pyscripter** [comment]
Did you understand my previous comment?  Delphi 32-bit programs only detect 32-bit versions of Python.  This is by design, since they cannot work with 64-bit versions of Python.
