### ISSUE TITLE
Compiler directives {$IFEND}

### ISSUE THREAD

**Issue by FactoryXCode** [pyscripter/python4delphi#101]
Compiler directives {$IFEND} should be altered, since Delphi version XE4 (compilerversion 25.0), to {$ENDIF}.

The most adequate solution is:

`  {$IF NOT DEFINED(FPC) and (CompilerVersion < 24.0)} { > Delphi XE3 }
    {$ENDIF}
  {$ELSE}
    {$IFEND} { < Delphi XE4 }`

**Comment by Artem3213212** [comment]
See http://docwiki.embarcadero.com/RADStudio/Rio/en/Legacy_IFEND_(Delphi) . It's will be better solution:
```
{$IF NOT DEFINED(FPC) and (CompilerVersion>24.0)}
{$LEGACYIFEND ON}
{$IFEND}
```

**Comment by pyscripter** [comment]
I thought recent versions of Delphi accept either {$IFEND} or {$ENDIF}.  In Delphi Rio I do not even get a warning.

**Comment by Artem3213212** [comment]
It looks like you have setted LEGACYIFEND option in Project > Options > Delphi Compiler > Compiling page. I think that the best way is always send this param to compiler from soureces because than you can use this lib without package.

**Comment by FactoryXCode** [comment]
I think, best is to handle this locally per unit regardless what a user did set in his compiler settings.
Since Delphi XE4, the compiler will always generate a hint: [DCC Hint] JohnDoo.pas(line number): H2586 Legacy '$IFEND' directive found. Consider changing to '$ENDIF' or enable $LEGACYIFEND.

**Comment by Artem3213212** [comment]
Yes but it will be better if you make .inc file with all directives for compiler and include it in all modules.

**Comment by FactoryXCode** [comment]
I agree with that. In our projects we always add an inc-file to deal with compiler settings per version. Other wise we have to write a different package version for each Delphi version.

**Comment by pyscripter** [comment]
Does FPC accept IFEND?  It does not say so in the documentation.
The other option is to just use ENDIF and drop XE4 or older compatibility.

**Comment by FactoryXCode** [comment]
Within FPC you are allowed to use both. Delphi is more strict on that.
See: [2.4.2 Usage](https://www.freepascal.org/docs-html/prog/progsu128.html).
Why drop XE3 or older compatibility? Not because of a simple compiler setting, I may hope :-). 
We stopped support for Delphi < 2009, but the option to compile with version 7 is still possible, with a few adjustment. I think most users of the old compilers are capable to do so.

**Comment by pyscripter** [comment]
- Under releases users can download older versions that may compile with older versions of Delphi.
- The whole world is now Unicode based.
- Python is dropping 2.x support.
-  Delphi community edition can be now freely used by most users.
- I have no older versions of Delphi to check compatibility.
- The effort to be backward compatible is no longer justified at least for me.

**Comment by FactoryXCode** [comment]
"FPC compatibility is more important than supporting older versions of Delphi." ?? I don't see any relationship between older FPC or Delphi versions.
The name of the package doesn't suggest it's written for FPC (Python4Delphi).
Then it's about time Python4Delphi needs an update to be compatible with Python 3.

**Comment by pyscripter** [comment]
It is a question of development time.  Supporting FPC and older Delphi versions takes a lot of effort.  Also it makes the code more complicated (too many IFDEFs).

P4D of course is Python 3 compatible.
