### ISSUE TITLE
Use of packed records

### ISSUE THREAD

**Issue by FactoryXCode** [pyscripter/python4delphi#102]
I'd like to comment that packed records are not done when porting from external (non Delphi) API's or calling external libraries written in another language than Delphi. The "packed" argument should only be used for backward compatibility of Delphi versions 1 and 2 or if 16 bit code is involved to get a correct alignment. In general it is not a recommended practice, because it can prevent compatibility with other languages or platforms, it slows data access and, for example, in the case of a character array, it affects type compatibility.
See [Memory management and Implicit Packing of Fields with a Common Type Specification](http://docwiki.embarcadero.com/RADStudio/Rio/en/Internal_Data_Formats_(Delphi))

Since Delphi 6 packed records should not be used when interacting with
other API's like C/C++ or dll's written in other languages.
Alignments should be treated as with C/C++ in the same manner.

Units that holds aligned records ( translated from for example #pragma pack(push, 1)),  should be initialized with 

`{$IFNDEF FPC}
    {$IFDEF WIN32}
      {$ALIGN 1} { Delphi 6+ equivalent to #pragma pack(push, 1) }
    {$ELSE} { Win64 }
      {$ALIGN 8}
    {$ENDIF}
  {$ENDIF}`

and all "packed" commands should be removed.
Note; Records in Win64 are always aligned by 8 bytes.

**Comment by pascaldragon** [comment]
> 
> Note; Records in Win64 are always aligned by 8 bytes.

This is not true. The size of the following struct will be 9, not 16 in Win64:

```
#pragma pack(push, 1)

struct Test
{
   unsigned char f1;
   long long f2;
};

#pragma pack(pop)
```

Thus `$ALIGN 1` needs to be used for Win64 as well. Not to mention that your `$IFDEF` does not cover non Windows platforms.

Also FPC supports the `$ALIGN` directive as well...

**Comment by pyscripter** [comment]
The current code base appears to be working well in Win32, Win64, FPC, Mac, Linux etc.   If it works don't fix it.
