### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by Pigrecos** [pyscripter/python4delphi#103]
Hi, thanks for your work.
I have a problem with the import of some modules, with the Windows Console everything works perfectly.

For example:
```
D: \ Applications \ Microsoft Visual Studio> python
Python 3.7.6 (tags / v3.7.6: 43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print (numpy .__ version__)
1.18.1
>>>
```

if, on the other hand, I insert only the word import numpy in the memo in one of your examples and I run the script, the error comes out:
```
First chance exception at $ 00007FFFAE55C184. Exception class $C000008E with message c000008e FLOAT_DIVIDE_BY_ZERO. Process Project1.exe (9124)

00007FFFAE55C184 F20F5E442448     divsd xmm0,qword ptr [rsp+$48]
```
detail error module from call stack:
Python37\lib\site-packages\numpy\core\_multiarray_umath.cp37-win_amd64.pyd

thank you

**Comment by pyscripter** [comment]
See #99 for the solution.

**Comment by Pigrecos** [comment]
thank you
