### ISSUE TITLE
Compilation Issues in P4DLaz package

### ISSUE THREAD

**Issue by mamin27** [pyscripter/python4delphi#104]
I tried to compile P4DLaz into Lazarus, but I found next issues in code. One is minor, 
next there is overloading issue. 

In Components/Sources/Core/PythonEngin.pas

first issue:
<pre><code class=python>
{$ENDIF}
{$IFDEF LINUX}
  PYTHON_KNOWN_VERSIONS: array[1..10] of TPythonVersionProp =
    (
    (DllName: 'libpython2.5.so'; RegVersion: '2.5'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython2.6.so'; RegVersion: '2.6'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython2.7.so'; RegVersion: '2.7'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython3.2.so'; RegVersion: '3.2'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython3.3.so'; RegVersion: '3.3'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython3.4.so'; RegVersion: '3.4'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython3.5.so'; RegVersion: '3.5'; APIVersion: 1013; CanUseLatest: True),
    (DllName: 'libpython3.6.so'; RegVersion: '3.6'; APIVersion: 1013; CanUseLatest: True)
    (DllName: 'libpython3.7.so'; RegVersion: '3.7'; APIVersion: 1013; CanUseLatest: True)
    (DllName: 'libpython3.8.so'; RegVersion: '3.8'; APIVersion: 1013; CanUseLatest: True)
    );
{$ENDIF}
</pre></code>

**for libpython3.6, libpython3.7 is missing ',' character at end of line**

next issue:
<pre><code class=python>
function CleanString(const s : AnsiString; AppendLF : Boolean = True) : AnsiString; overload;
function CleanString(const s : string; AppendLF : Boolean = True) : string; overload;
</pre></code>
Lazarus compiler has trouble with compilation:
**PythonEngine.pas(3178,10) Error: Function is already declared Public/Forward "CleanString(const AnsiString;Boolean="TRUE"):AnsiString;"**

**Comment by pyscripter** [comment]
The issue with missing commas is now fixed.
Does replacing {$mode delphi} with {$mode delphiunicode} resolve the second issue?

**Comment by mamin27** [comment]
Hello pyscripter,

It helps partially. (After updating Definition.inc -> {$MODE DELHIUNICODE})

Here are next issues in compilation messages:
<pre>
TinyWideStrings.pas(63,39) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
TinyWideStrings.pas(68,27) Warning: Implicit string type conversion from "AnsiString" to "WideString"
MethodCallBack.pas(176,23) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(176,63) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(176,98) Hint: Converting the operands to "Int64" before doing the add could prevent overflow errors.
MethodCallBack.pas(194,31) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(194,23) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(198,18) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(198,48) Hint: Converting the operands to "Int64" before doing the add could prevent overflow errors.
MethodCallBack.pas(198,10) Warning: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(223,11) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(223,33) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(235,49) Hint: Conversion between ordinals and pointers is not portable
MethodCallBack.pas(347,17) Hint: Local variable "Q" does not seem to be initialized
PythonEngine.pas(2418,15) Error: There is no method in an ancestor class to be overridden: "GetDisplayName:UnicodeString;"
PythonEngine.pas(2419,15) Error: There is no method in an ancestor class to be overridden: "SetDisplayName(const UnicodeString);"
PythonEngine.pas(2621,14) Error: There is no method in an ancestor class to be overridden: "GetDisplayName:UnicodeString;"
PythonEngine.pas(3106,15) Note: Virtual method "Execute;" has a lower visibility (private) than parent class TThread (protected)
</pre>

**Comment by mamin27** [comment]
Hello pyscripter,

I was fixed P4DLaz.

There are a lot of fixes in FPS version. Probably you will be interested at my fix experiences and you can fix it deeply. I just fixed the compiler issues without any testing. Also I suppose that some of functionality was damaged. (by the comments). If you want I could help you with testing and fixing at lazarus site in the future. Package of changes I could send you in package later if you want.

**Comment by pyscripter** [comment]
I have changed the CleanString declaration to 
function CleanString(const s : UnicodeString; AppendLF : Boolean) : UnicodeString;
Which should fix the originally reported error.

For further FCP compatibility issues please create a new issue.  I would definitely be interested to fully support FCP so please do submit Pull Requests to that purpose.   Please also note that there is an FCP fork at https://github.com/Alexey-T/Python-for-Lazarus.

**Comment by mamin27** [comment]
There are a lot of fixes in FPS version. Probably you will be interested at my fix experiences and you can fix it deeply. I just fixed the compiler issues without any testing. Also I suppose that some of functionality was damaged. (by the comments). If you want I could help you with testing and fixing at lazarus site in the future. Package of changes I could send you in package later if you want.
