### ISSUE TITLE
Ignored DllPath in loading dll

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#116]
```
procedure TDynamicDll.LoadDll;
begin
  OpenDll( DllName );
end;
```
DllPath ignored, so Win10 OS py is loaded
https://github.com/Alexey-T/CudaText/issues/2414

**Comment by Alexey-T** [comment]
maybe fix is
```

procedure TDynamicDll.LoadDll;
var
  S: string;
begin
  S := DllName;
  if DllPath <> '' then
    S:= DllPath + DirectorySeparator + DllName;
  OpenDll(S);
end;
    ```

**Comment by Alexey-T** [comment]
I must add this too
https://github.com/Alexey-T/Python-for-Lazarus/commit/e271069081935614e462fb74f2008ee24c04f844

**Comment by pyscripter** [comment]
OpenDLL calls DoOpenDLL which calls GetDllPath.  Check the source code.
