### ISSUE TITLE
Releaseversioning not fully usable by Delphinus

### ISSUE THREAD

**Issue by Memnarch** [pyscripter/python4delphi#119]
Hi,
Thanks for supporting Delphinus.
When i looked at your releases, i noticed they do not adhere to a proper versioning scheme.
That way Delphinus can not identify properly, which version is newer.

For more information see: 
https://github.com/Memnarch/Delphinus/wiki/Versioning-your-package

**Comment by pyscripter** [comment]
I am sorry but I have decided to drop Delphinus support.  I don't think it was used much and I would advice users to use the master branch instead of releases.

**Comment by Memnarch** [comment]
Oh that's sad to hear. Unfortunetly Github does not provide any feedback on how hoften a specific release is downloaded.
I have daily download of Delphinus on my homepage so that's used/looked at for sure.
