### ISSUE TITLE
SetProgramArgs on macOS

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#120]
https://github.com/Alexey-T/Python-for-Lazarus/commit/8dc41685b547f0982755b90115d9a43a2d2b358c

it's needed on macOS, to not crash, now sys.argv shows OK text in CudaText.
not sure it's ok for FreeBSD/Solaris, will test it later.

**Comment by pyscripter** [comment]
I have implemented a similar fix.
In PythonEngine.pas
{$IFDEF Posix}

and in Definitions.inc
{$IFDEF FPC}
 ...
  {$IFDEF UNIX}
    {$DEFINE POSIX}
  {$ENDIF UNIX}
{$ENDIF FPC}

**Comment by Alexey-T** [comment]
My fix is ok for FPC

**Comment by pyscripter** [comment]
But not compatible with Delphi.  UNIX is not defined  in Delphi.   POSIX is.  My solution is compatible with both FPC and Delphi.

**Comment by Alexey-T** [comment]
https://wiki.freepascal.org/Platform_defines
I dont see here POSIX word, sorry

**Comment by Alexey-T** [comment]
And test on Linux shows that POSIX is absent

**Comment by pyscripter** [comment]
Did you read  my message:

and in Definitions.inc
{$IFDEF FPC}
...
{$IFDEF UNIX}
{$DEFINE POSIX}
{$ENDIF UNIX}
{$ENDIF FPC}

**Comment by Alexey-T** [comment]
OK, I missed it

**Comment by pyscripter** [comment]
Could you please check whether a similar fix is needed for PyUnicode_FromWideString and PyUnicode_AsWideString  (LINUX -> UNIX or POSIX)

**Comment by Alexey-T** [comment]
```
function TPythonEngine.PyUnicode_FromWideString( const AString : UnicodeString) : PPyObject;
{$IFDEF unix}
var
  _ucs4Str : UCS4String;
{$ENDIF}
begin
{$IFDEF unix}
  // Note that Linux uses UCS4 strings, whereas it declares using UCS2 strings!!!
  _ucs4Str := WideStringToUCS4String(AString);
  Result := PyUnicode_FromWideChar( {PWideChar}(@_ucs4Str[0]), Length(_ucs4Str)-1 {trim trailing zero});
{$ELSE}
  Result := PyUnicode_FromWideChar( PWideChar(AString), Length(AString) );
{$ENDIF}
end;  
```
so yes, POSIX is needed here. this works on macOS.
PyUnicode_AsWideString - too

**Comment by pyscripter** [comment]
872cb35081bf1c31ad94643546c63c80ae149aff
