### ISSUE TITLE
while running one script ,try to run another script.

### ISSUE THREAD

**Issue by GitContainer** [pyscripter/python4delphi#122]
My situation:

I had two scripts（a.py ，b.py） containing code 'plt.show', when I ran a.py，A chart showed，but Icouldn't run b.py before closed the chart window.‘’raised exception class ￥C0000005 with message ‘c000000 5 access_vilolation.
Is it any solution for this situation？’

**Comment by pyscripter** [comment]
Are you using matplotlib? Which backend?
I would recommend to save figures as images or html and display them in Delphi.

**Comment by pyscripter** [comment]
This is not a proper bug report.  No reproducible code, no feedback, so I am closing it.
