### ISSUE TITLE
Some method names

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#123]
looking at my changes in git, i see that we have not clear, vague, names. so i got very bad work. names look silimar.
can we add some prefixes maybe?

![Screenshot from 2020-04-01 15-59-32](https://user-images.githubusercontent.com/4154978/78140068-194ec180-7432-11ea-8a4d-1d71a98f34d5.png)

**Comment by pyscripter** [comment]
You got a point but it is not that bad.

The high level method is LoadDLL.

LoadDLL calls OpenDLL (both public)
OpenDLL calls DoOpenDLL (protected and virtual)

Given that DoOpenDLL is protected the user sees just LoadDLL and OpenDLL.  I guess LoadDLL could be renamed just Load, but that would break a lot of existing code.

I will pass this one.
