### ISSUE TITLE
Help!!!It is strange

### ISSUE THREAD

**Issue by GitContainer** [pyscripter/python4delphi#124]
It is strange, when I ran  a pandas dataframe.drop_duplicates script after a 'sql line', there was an error "Project.exe raised exception class EInvalidOP with message 'Invalid floating point operation'". But It can ran 'dataframe.drop_duplicates' line  without 'sql' line  secussfully.   pandas ==1.0 /1.3  p4d==latest release
'''
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://ruser:haosql@localhost:3306/shenweipipeline')
sql = ''' select * from ft5201; '''
df = pd.read_sql_query(sql, engine)
df.drop_duplicates(subset=['RecordDateTime'],keep='first',inplace=True)
'''

**Comment by pyscripter** [comment]
You need to call MaskFPUExceptions(True), before loading python.  See the links below.
```
(* Mask FPU Excptions - Useful for importing SciPy and other Python libs
   See http://bugs.python.org/issue9980 and
   http://stackoverflow.com/questions/3933851/
 *)
  procedure MaskFPUExceptions(ExceptionsMasked : boolean;
  MatchPythonPrecision : Boolean = True);
```
However the specific issue may be related to having conflicting versions of matplotlib installed.

**Comment by GitContainer** [comment]
I have called MaskFPUExceptions(True) using following code:
'''
 MaskFPUExceptions(True);
  FPUExceptionMask := GetExceptionMask;
  SetExceptionMask([exZeroDivide, exPrecision]);
  PythonEngine1.ExecStrings(Editor.Lines);
  SetExceptionMask(FPUExceptionMask);
'''
and  tested another script secussfully,
'''
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,9,(50,4)), columns=list('ABCD'))
df.drop_duplicates(subset=['A'],keep='first',inplace=True)
print(df)
'''
and then I loaded 
"'
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://ruser:haosql@localhost:3306/shenweipipeline')
sql = ''' select * from ft5201; '''
df = pd.read_sql_query(sql, engine)
df.drop_duplicates(subset=['RecordDateTime'],keep='first',inplace=True)
'''
Error occured.

**Comment by GitContainer** [comment]
ooo,I think I know where is the problem,  I should not set' SetExceptionMask([exZeroDivide, exPrecision])' .
Thank you for your prompt reply.

**Comment by pyscripter** [comment]
MaskFPUExceptions(True);
is all you need.

**Comment by MuhammadAzizulHakim** [comment]
> MaskFPUExceptions(True);
> is all you need.

I know this would seem trivial, but I struggle to find where to put this for hours.. 
In my case, the error 'Invalid floating point operation' was raised when I use Keras inside the Demo01 in Python4Delphi.

For newcomers to Delphi like me, this is the example where you need to put the "MaskFPUExceptions(True);"
1. Go to the "Code" tab or Unit1.pas
2. For Demo01, I put the MaskFPUExceptions(True); here:
procedure TForm1.Button1Click(Sender: TObject);
begin
  MaskFPUExceptions(True);
  PythonEngine1.ExecStrings( Memo1.Lines );
end;

After that, everything works well! I hope this would help anyone new to Delphi or Python4Delphi.

![2_1](https://user-images.githubusercontent.com/24671511/109105788-30408580-7761-11eb-97c5-b283252e3aa1.PNG)
