### ISSUE TITLE
Initialization (Py_Initialize) fails if PYTHONHOME is not defined in Windows

### ISSUE THREAD

**Issue by ReinierNL** [pyscripter/python4delphi#127]
Even if the PythonEngine can find and load a python dll, it may fail to initialize (in TPythonEngine.Initialize, called by AfterLoad, on the call of Py_Initialize).
What happens is that the program just aborts with no error messages.

I've found that this must have something to do with not finding everything Python needs to initialize, because this was solved once I added PYTHONHOME to my environment variables.

I have (had) no PYTHONHOME (or PYTHONPATH) defined on my system. I am using Anaconda; apparently Anaconda does not need it.
I suggest a line of text is added to **Readme.txt**, under INSTALLATION, after "install the Python for Windows distribution", saying: "Make sure you have an environment variable PYTHONHOME defined which points to the root folder of your Python".

Perhaps also in **Tutorial.txt**, one or two lines of text may be added (copied from Readme.txt) at the beginning about setting up the Python environment.

**Comment by pyscripter** [comment]
No need to set the environment variable.  
For registered python versions this should not be a problem.
For unregistered python versions, you can call the SetPythonHome method instead before loading the engine.

The PythonVersions unit was written to handle these kind of complications.   See Demo34 on how it can be used.

I agree all these are not (well) documented.

**Comment by ReinierNL** [comment]
Hi pyscripter, thanks for your reply; sorry I didn't see it earlier; somehow I got no notification from github. oh well.

It's nice to know that setting the environment variable is not necessary, 
when you solve it using PythonVersion.
However, it took me really long before I solved the problem myself.
This is unnecessary because it can be avoided by adding just one line of text to the Readme file.

If you prefer, that line of text can also point to the PythonVersion solution in stead of setting PYTHONHOME or both possibilities can be mentioned.
The thing is, if Demo01 does not work 'out of the box', this discourages people to try further.
And nobody will get to Demo34 if all the previous demos don't work :-).

Shall I prepare a pull request for the Readme.txt (and tutorial.txt)?

**Comment by pyscripter** [comment]
Please do!

**Comment by pyscripter** [comment]
I have now added two new Wiki pages that I hope provide sufficient documentation
- How Python for Delphi finds your Python distribution 
- Masking FPU Exceptions
I have also added pointers to those from the Readme file and tutorial.txt.

Have a look and come back if you think they are not clear enough.
