### ISSUE TITLE
PythonDelphiVar1's event bug

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#129]
event: PythonDelphiVar1SetData  can not be fire on.

if one var define in the script, the event:PythonDelphiVar1GetData cant not be fired on any more.

the event:PythonDelphiVar1Change  triggered zero time.

my env is:  
10.2.3 tokyo,fmx delphi...64bit

**Comment by pyscripter** [comment]
Could you please submit a minimal project that reproduces the problem?

**Comment by softbug123** [comment]
[Project10_2020-04-17.zip](https://github.com/pyscripter/python4delphi/files/4491893/Project10_2020-04-17.zip)

**Comment by softbug123** [comment]
please check it, thx..

**Comment by pyscripter** [comment]
The statement

IC0101 = "123123" in your script makes IC0101 refer to a string rather than you Delphi var.
To change the value of the Delphi var do instead

IC0101.Value = "123123"

Then both the set and change events fire.
