### ISSUE TITLE
how to stop the python scripts?

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#130]
if i have the python script run in my dephi... just like below:

import time 
while True:  
  ticks = time.time()
  print( "time:", ticks)

probleam1:  how to conrtol to let it stop it.  please dont consider using the state var.
probleam2:  where to put the code to let the main ui thread can wake up,  then , where to put the  Application.ProcessMessages ??

**Comment by pyscripter** [comment]
Please use the issue tracker for  bug reports and not for asking questions.
