### ISSUE TITLE
[dcc64 Error] PythonEngine.pas(1377): E2003 Undeclared identifier: 'pidAllPlatforms'

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#131]
it raise a complie error when i update the new code from github.
![bug pic](https://user-images.githubusercontent.com/19881844/79677251-d78b8c80-8221-11ea-8157-b94436bf1d06.png)

**Comment by softbug123** [comment]
{ Platform identifiers }
  pidWin32        = $0001;
  pidWin64        = $0002;
  pidOSX32        = $0004;
  pidiOSSimulator = $0008;
  pidAndroid      = $0010;
  pidLinux32      = $0020;
  pidiOSDevice32  = $0040;
  pidiOSDevice    = pidiOSDevice32;// deprecated 'Use pidiOSDevice32';
  pidLinux64      = $0080;

  pidWinNX32      = $0100;
  pidWinIoT32     = $0200; // Embedded IoT (Internet of Things) Windows w/ Intel Galileo
  pidiOSDevice64  = $0400;
  pidWinARM       = $0800;
  pidOSX64        = $1000;
  pidOSXNX64      = pidOSX64 deprecated 'Use pidOSX64';
  pidLinux32Arm   = $2000;
  pidLinux64Arm   = $4000;
  pidAndroid64    = $8000;


can not found this params.  my platform is  tokyo 10.2.3

**Comment by pyscripter** [comment]
I am using Delphi 10.3 and 

  pidAllPlatforms = pidWin32 or pidWin64 or
                    pidOSX32 or pidOSX64 or
                    pidiOSDevice32 or pidiOSDevice64 or
                    pidiOSSimulator32 or pidiOSSimulator64 or
                    pidAndroid32Arm or
                    pidLinux64;

As a quick fix you can add this to PythonEngine.pas and WrapDelphi.pas.
I will revert back these changes.

**Comment by softbug123** [comment]
thx very much!!!

**Comment by pyscripter** [comment]
I will keep open till I fix it.
