### ISSUE TITLE
Exception EpySynataxError~~

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#132]
1. i have the python 3.8 in my c:\python38,i am sure.
2. i know we should add the (  )  to the print's left and right.
3. i nerver called the print sys.version,  where is it come out.??? i am so confuse。。

![12222](https://user-images.githubusercontent.com/19881844/79678970-c5b2e500-8233-11ea-9453-1b262ea7a466.png)

[Demo05.zip](https://github.com/pyscripter/python4delphi/files/4498336/Demo05.zip)

**Comment by softbug123** [comment]
if  i create a new demo like demo05, it will not be happend this probleams. pls help me.

**Comment by pyscripter** [comment]
If you view the form as text you will see:

  object PythonEngine1: TPythonEngine
    InitScript.Strings = (
      'import sys'
      'print "Python Dll: ", sys.version'
      'print sys.copyright'
      'print')

You need to change PythonEngine1.InitScripts.Strings to make it conform to python 3 syntax if you are using python 3.x.
