### ISSUE TITLE
how to reponse for my main form.

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#137]
hi,

i let the python run  in my main form,  the example code:

i=1
a=“ok”
while True:
   i=i+1
   print(i)
   if a<>"ok":
      break

if i run it, the main form can not be wake,the repeat code runing leading the main form dying... you known,we always want the script to run  loop....

my question is:  how to let the main form get some relief?.... do u have some suggestion??

**Comment by softbug123** [comment]
we used the application.processmessage in the delphi,  but how to using it in scripts.     i tried wrappe it to called by python script. but access ill~~~errror.

**Comment by pyscripter** [comment]
Please study the demos and don't use the issue tracker to ask questions.  Demo 33 shows you how to use threads.
