### ISSUE TITLE
Any plan for using python to create cross-platform GUI with Lazarus component library(lcl) or Delphi Visual Component Library(vcl)?

### ISSUE THREAD

**Issue by haifenghuang** [pyscripter/python4delphi#138]
Sir, do you have any plan for using python to create cross-platform GUI like [https://github.com/ying32/govcl](url)? I thought that would be very cool.

**Comment by pyscripter** [comment]
P4D is GUI agnostic.  It can be used with any GUI.
See https://github.com/pyscripter/python4delphi/wiki/SupportedPlatforms for supported platforms.
See https://github.com/pyscripter/python4delphi/tree/master/PythonForDelphi/Modules for wrapping the Vcl and exposing it to Python.  A similar approach can be used for wrapping any GUI (e.g. LCL, FMX etc.).
