### ISSUE TITLE
access av when import kafka

### ISSUE THREAD

**Issue by softbug123** [pyscripter/python4delphi#139]
a object  which is TpythonEngine,  write some thing in it's initScript property:

from kafka import  KafkaConsumer

then,run the Application,it will be lead to av error:

![微信截图_20200528150114](https://user-images.githubusercontent.com/19881844/83109951-e0ab2b80-a0f4-11ea-8db6-fd4438e6b8cd.png)

![微信截图_20200528150501](https://user-images.githubusercontent.com/19881844/83110104-236d0380-a0f5-11ea-8e3a-8a3f74ab1d02.png)

but i remove this import, it will be ok...  why?   kafka can not suit python4delphi?

**Comment by pyscripter** [comment]
Are you using threads?  Please post a minimal test program that reproduces the issue.

**Comment by softbug123** [comment]
just take any demo,put the code:

from kafka import  KafkaConsumer

to the Tpythonengine's InitScript property,it will be catched. here is a example in the attchement.
if you run it, you will see the issuse again.  please install the kafka first.  

pip3 install kafka

[Demo01.zip](https://github.com/pyscripter/python4delphi/files/4699053/Demo01.zip)

**Comment by softbug123** [comment]
threads is no relation with this issuse. can u try it asap...thank u.

**Comment by pyscripter** [comment]
Does it hep setting the PythonEngine InitThreads to on.

I am on Python 3.8.2
after 
pip install kafka
tried 
>>> from kafka import KafkaConsumer
```
C:\Python\Python38>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaConsumer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python38\lib\site-packages\kafka\__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "C:\Python\Python38\lib\site-packages\kafka\producer\__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "C:\Python\Python38\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
```
and got a syntax error in kafka code.

**Comment by pyscripter** [comment]
I got it working by installing kafka-python instead of kafka.
With demo1 and python 3.8 I see no problems

![image](https://user-images.githubusercontent.com/1311616/83340438-a2725f80-a2e0-11ea-8b53-60d6fd206e8a.png)

**Comment by softbug123** [comment]
i got.

pip3 uninstall kafka

pip3 install kafka-python



because the keyword async !!!

**Comment by softbug123** [comment]
thx u verymuch.
