### ISSUE TITLE
Creating Python binary wheel for Linux with FPC

### ISSUE THREAD

**Issue by abitrolly** [pyscripter/python4delphi#140]
I understand that most examples are about embedding Python into Delphi, but is there a tutorial for Python programmers how to use some Delphi or Free Pascal function in Python? 

There are some low level tutorials available, such as https://macpgmr.github.io/MacXPlatform/PascalDynLibs.html but maybe there is a high-level wrapper?

**Comment by pyscripter** [comment]
In the Modules folder you can find three examples of creating Python extension modules using P4D.

- Delphi wraps the Rtl and Vcl classes
- DemoModule 
- RttiModule

The last two demonstrate two different ways of exposing a simple pascal function to Python.  The project in DemoModule can be easily adapted to work with FPC and Linux.

**Comment by abitrolly** [comment]
I was browsing Demos folder and completely missed the Modules. Thanks.

https://github.com/pyscripter/python4delphi/tree/master/PythonForDelphi/Modules
