### ISSUE TITLE
how to run *.pyc  with  TPythonEngine

### ISSUE THREAD

**Issue by liuzg2** [pyscripter/python4delphi#141]
how to run *.pyc  with  TPythonEngine

**Comment by liuzg2** [comment]
read a bytecode  pyc 
exec with  TPythonEngine from  a  bytecode   filesteam

**Comment by liuzg2** [comment]
co := Py_CompileString(PChar(CleanString(RichEdit1.Lines.Text)), PChar(Caption), file_input );
      try
        // if successfully compiled
        if Assigned( co ) then
          begin
            // Execute ByteCode, in the __main__ context
            res := PyImport_ExecCodeModule( '__main__', co );
          end;
      finally
        // Cleanup ByteCode
        Py_XDECREF(co);
      end;

how to save to pyc  
 read from  filestream( **.pyc)
and  filestream   to PPyObject

**Comment by pyscripter** [comment]
Not sure exactly, but possibly using the py_compile module.  

In any case you can ask the question at Stackoverflow.  This is an Issue Tracker and not a support site.
