### ISSUE TITLE
PyNumberMethods record is incorrect for Python 3.x

### ISSUE THREAD

**Issue by LennertP** [pyscripter/python4delphi#142]
The PyNumberMethods record was designed for Python 2.x and still contains nb_divide, nb_coerce, nb_oct, nb_hex and nb_inplace_divide. On the other hand, it lacks nb_index, nb_matrix_multiply and nb_inplace_matrix_multiply. Also, nb_nonzero was renamed as nb_bool and nb_long as nb_reserved. Finally, it has a typo for nb_substract, which should read nb_subtract. 

As a result, for Python 3.x e.g. TPythonType_NbPower() will be called when TPythonType_NbNegative() is intended.

**Comment by pyscripter** [comment]
Could you please supply a test project that demonstrates the issue?

**Comment by Alexey-T** [comment]
seems very rarely used API.

**Comment by LennertP** [comment]
Sure, I will create a small example to show the issue later today. These number services are used for operators on user-defined types, e.g. a * b for a and/or b being some TPythonType.

**Comment by LennertP** [comment]
Please find a simple example project here:
[NumberServices.zip](https://github.com/pyscripter/python4delphi/files/5016156/NumberServices.zip)
To be able to run this program you will need to point it to a local virtual environment (Search for "TODO:").

**Comment by pyscripter** [comment]
Thanks. Will have a close look.

**Comment by LennertP** [comment]
For convenience I herewith provide my version of PythonEngine.pas:
[PythonEngine.zip](https://github.com/pyscripter/python4delphi/files/5023124/PythonEngine.zip)
This version supports both Python 2 and Python 3. Next to these changes it also adds some other minor changes that you may or may not want to include (e.g. PyErr_WarnEx() and PyArg_ParseTupleAndKeywords())

**Comment by pyscripter** [comment]
Thanks!

**Comment by LennertP** [comment]
Are you convinced that my changes are correct? Can these eventually be merged in the master version?

**Comment by pyscripter** [comment]
I am sorry for the delayed response.  I will be looking into this soon...

**Comment by LennertP** [comment]
OK, no problem!

**Comment by pyscripter** [comment]
@LennertP 
Your changes were committed with some adaptations.
Thanks very much!

**Comment by LennertP** [comment]
Great, I am glad I was able to add my small contribution to this project!

**Comment by Alexey-T** [comment]
Thank you !

**Comment by pyscripter** [comment]
@LennertP I wonder whether you could write some unit tests (see the Test folder) to test the correctness of Number Services.
Also any chance of helping with the updating of other services?

**Comment by LennertP** [comment]
Hi PyScripter!

Thank you for your message. I think I should be able to come up with a couple of tests. This week is rather busy for me, I don’t know when you want to have these tests ready?

Lennert.

**Comment by pyscripter** [comment]
There is no rush.   Whenever you got some free time you are able to contribute to the project.

**Comment by pyscripter** [comment]
Fixed, thanks!

**Comment by LennertP** [comment]
That’s quick, thanks!

**Comment by LennertP** [comment]
Hi PyScripter,

Today I realized I didn’t come back to your request to add some unit test for these PyNumberMethods, my apologies! I just checked out the existing tests to see how I can contribute. Is it true that there are currently no unit tests for the operators yet? Do you expect a new unit, or is it better to add the new tests to an existing unit?

Best regards,

Lennert.

**Comment by pyscripter** [comment]
A new unit would be great! Thanks.

**Comment by LennertP** [comment]
Hi,

I prepared the unit attached. It is not completely finished yet, but perhaps it is good if you can already take a look to check if this is what you expected?

Best regards,

Lennert.

**Comment by pyscripter** [comment]
@LennertP  I am sorry but I cannot see any unit attached.  Could you please drop the file in a new comment or send it by email?

**Comment by LennertP** [comment]
L.S.,

Here is a new attempt to send the file, this time with a .txt extension.

Lennert.

**Comment by LennertP** [comment]
Hi,

I just created a new “issue” to post my tests on https://github.com/pyscripter/python4delphi/issues/211. This is a more recent version than I e-mailed you earlier today, so feel free to ignore my previous message.

Best regards,

Lennert.
