### ISSUE TITLE
Py 3.8 on Arch Linux: error in Python4Lazarus

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#143]
```
ImportError: /usr/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
```

User reported it about 1.5month ago here
https://forum.manjaro.org/t/problems-with-cudatext-text-editor/148067/10

what it means? some bad import from Py4Lazarus?

**Comment by pyscripter** [comment]
If you google for undefined symbol: "_Py_write_noraise" you will see that this is a python installation issue in Arch Linux.
See for example  https://github.com/davidhalter/jedi-vim/issues/823
