### ISSUE TITLE
import numpy exception division by zero despite call MaskFPUExceptions(True); (python 3.7.6 and RAD Studio 10.2.3 64 bits compilation)

### ISSUE THREAD

**Issue by minguyen1984** [pyscripter/python4delphi#144]
Hi pyscripter,
This is my first experience with python4delphi.
I want to test the possibility to use a bridge between python and delphi (C++ later) for scientifical calculations.
For that, I developped a little demonstrator which work very fine until I import numpy...
While importing the numpy, the application raised an exception "Division by zero" OK, i found the solution by deactivate the autoLoad on PythonEngine, then call the method MaskFPUExceptions before call loadDll and execute the command line (#69)
I still have that problem.
![image](https://user-images.githubusercontent.com/69810107/90418826-f3128100-e0b5-11ea-8f6b-9dfc10fe5072.png)
(french message ^^)
Do you have another way to fix the issue? 

The python script worked fine with pyscripter (I mean the import and the code execution).

Thanks you very for your time

Best regards

**Comment by pyscripter** [comment]
Could you please post a demo project that reproduces the issue?

**Comment by minguyen1984** [comment]
This is the demo project.
Input is a TSynedit, Output is a TMemo.
I tried with a designtime TPythonEngine and after with a dynamically created TPythonEngine.
Please note that I use an Anaconda3 for python, I set the path to the anaconda installation folder to property DllPath and generate the .exe in the Anaconda3 installation folder.

[DelphiDemo_pyNastran.zip](https://github.com/pyscripter/python4delphi/files/5086202/DelphiDemo_pyNastran.zip)

The Syndit has directly the line "import numpy", just click on "Execute" button to produce the issue.

Best regards

**Comment by pyscripter** [comment]
The dpr file is missing could you please add that.

**Comment by pyscripter** [comment]
Nevermind.  I have recreated your project.

The issue is that Anaconda requires some extra steps to load properly.  All these is described in https://github.com/pyscripter/python4delphi/wiki/FindingPython.

You need to add the following before loading the anaconda python dll.

```pascal
var
  PE: TPythonEngine;
  OldPath, NewPath : string;
...

  OldPath := System.SysUtils.GetEnvironmentVariable('PATH');
  NewPath := Format('%s;%0:s\Library\bin;', [PE.DllPath]) + OldPath;
  SetEnvironmentVariable('PATH', PWideChar(NewPath));

  PE.SetPythonHome(PE.DllPath);
  PE.LoadDll;
```

With the above I was able to import numpy without any issues.

**Comment by minguyen1984** [comment]
Thanks you very much for the solution, now it works fine.
I read the subject but I had not made the relation with the division by zero.

Hoping this issue solution will help developers in the future :)
Best regards.
