### ISSUE TITLE
No warning filter handling

### ISSUE THREAD

**Issue by katischulze** [pyscripter/python4delphi#145]
As far as I can see there is currently no way to explicitly control the python warning filters. Python automatically suppresses some warnings. I, however, want to show the warning always.
There is a function called PyErr_WarnExplicit, which, to my knowledge, ignores any persisting warning filters and displays the warning every time; but it is not defined in the current version of PythonEngine.pas.
Would it be possible to add this function to Python4Delphi?

**Comment by pyscripter** [comment]
PErr_WarnExplicit is a lower level routine than PyWarn_Ex which is imported.   It is about issuing warnings and not about warning filtering.  So I am not sure how it will help you.

To control how warnings are handled you can use the warnings module either inside your code or in engine InitScript.  See https://docs.python.org/3/library/warnings.html for details.

**Comment by katischulze** [comment]
I currently edited the PythonEngine.pas so that PyErr_WarnExplicit is imported as well and it has the desired effect. I found it a bit more elegant solution to have it in the imports rather than putting it in the InitScript, even though I would have rather avoided editing PythonEngine.pas so that updates to Python4Delphi can be easily imported.

**Comment by pyscripter** [comment]
Could you please submit a Pull Request with the change?

**Comment by pyscripter** [comment]
Thanks!  Fixed in #146
