### ISSUE TITLE
Floating Point Overflow when importing certain Libraries inside the InitScript

### ISSUE THREAD

**Issue by rifoerster** [pyscripter/python4delphi#147]
Hello,
i get an "floating point overflow at <...>" exception when import certain libraries (i.e. yaml) while it works fine with others (i.e. serial, os, BitVector, datetime, ...)

I am using RAD Studio XE6 Update 1 and the newest python4delphi Version installed through Delphinus.
Loading the above mentioned library works fine in both Spyder and IDLE, so i would assume the problem lies either somwhere in python4delphi or any setup step i missed.

Callstack: https://pastebin.com/ep0SqK56

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/MaskFPUExceptions.

**Comment by rifoerster** [comment]
That fixed things, thanks.
