### ISSUE TITLE
Returning list(list(2.0)) from a script to TPythonDelphiVar does not work

### ISSUE THREAD

**Issue by sportfloh** [pyscripter/python4delphi#148]
hey,

I want to return a list(list((float)) from python to Delphi and assign it to a variable of type TArray<TArray<double>>.
But after the assignment the Delphi variable is empty.
Returning a list(float) and assigning it to a variable of type TArray<double> works.
Any idea what the problem is or is this even possible?
I'm using Delphi.

Thanks and cheers!

**Comment by pyscripter** [comment]
VarPyth is the high level interface for accessing python objects from Delphi using custom variants.   However you can not assign Python variables to TArray variables directly.
Please study [VarPythTest.pas](https://github.com/pyscripter/python4delphi/blob/master/PythonForDelphi/Components/Sources/Core/UnitTests/VarPythTest.pas) and Demo 25 to see what can be done (and cannot be done) with VarPyth.

**Comment by sportfloh** [comment]
Thanks for your quick responce!
I assume it's also not possible to do something like
``` pascal
d, v: Variant
d := NewPythonDict;
V := VarArrayCreate([3, 4, 5], varInteger);
d.SetItem('a', v);
```
to transfer a dict with array values?

**Comment by pyscripter** [comment]
That should probably work.  TPythonEngine.VariantAsPyObject deals with Variant arrays.

But you can create a Python List directly:

V := VarPythonCreate([3, 4, 5]);

Please study the VarPyth demo and unit test.
