### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by drbond** [pyscripter/python4delphi#149]
Installation failure - "Can't load package Python_D$(Auto).bpl 
The system cannot find the file specified" - - Python_D.dprog loaded in Delphi 10.4. Installation documentation too vague to check that I have the correct setup. Using Anaconda3 installation.

**Comment by pyscripter** [comment]
Are you using Delphi 10.4.1?

Here when I open the package in Delphi 10.4 I see 
![image](https://user-images.githubusercontent.com/1311616/94297032-81f3a280-ff6c-11ea-80b8-7695afe32c79.png)

Do you you see the same?

If it does not work please try the package under Delphi 10.3-  and change the LibSuffix to 270.

**Comment by drbond** [comment]
Yes, I have Delphi 10.4.1 installed currently. Licence for Delphi 10.3 has expired so this is not available to try. I am writing a Delphi textbook for the schools market and using a temporary licence courtesy of Embarcadero. I want to include at least one chapter if not more on Python4Delphi. Hence my interest in getting it installed. What I get in the ProjectGroup is Python_D$(Auto).bpl. I loaded Python_D.dproj to get to this situation. I installed Anaconda3 32-bit and accepted the Registration option as advised in the Python4Delphi installation guide. Interestingly , when I try to select the rename option(right click Python_D$(Auto).bpl) to remove $(Auto) from Python_D$(Auto).bpl, I see only the stem Python_D.

**Comment by pyscripter** [comment]
- Are you using the latest version of P4D from this repository (https://github.com/pyscripter)?  (have you cloned the repository or downloaded a zip file?)
- Are you sure you are using Delphi 10.4.1?  In the About dialog box you should see the following:
Embarcadero® Delphi 10.4 Version 27.0.38860.1461

>  I installed Anaconda3 32-bit and accepted the Registration option as advised in the Python4Delphi installation guide.
Which installation guide?  Installation instructions are given in https://github.com/pyscripter/python4delphi/wiki/Installation and there is no mention of Anaconda.

**Comment by pyscripter** [comment]
If everything else fails please try the following:
- Open file Packages\Delphi\Delphi10.3-\Python_D.dpk in an editor outside the IDE (e.g. notepad).
- Replace
```pascal
{$IFDEF VER200}{$LIBSUFFIX '120'} {$ENDIF}
{$IFDEF VER210}{$LIBSUFFIX '140'} {$ENDIF}
{$IFDEF VER220}{$LIBSUFFIX '150'} {$ENDIF}
{$IFDEF VER230}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER240}{$LIBSUFFIX '170'} {$ENDIF}
{$IFDEF VER250}{$LIBSUFFIX '180'} {$ENDIF}
{$IFDEF VER260}{$LIBSUFFIX '190'} {$ENDIF}
{$IFDEF VER270}{$LIBSUFFIX '200'} {$ENDIF}
{$IFDEF VER280}{$LIBSUFFIX '210'} {$ENDIF}
{$IFDEF VER200}{$LIBSUFFIX '220'} {$ENDIF}
{$IFDEF VER300}{$LIBSUFFIX '230'} {$ENDIF}
{$IFDEF VER310}{$LIBSUFFIX '240'} {$ENDIF}
{$IFDEF VER320}{$LIBSUFFIX '250'} {$ENDIF}
{$IFDEF VER330}{$LIBSUFFIX '260'} {$ENDIF}
{$IFDEF VER340}{$LIBSUFFIX '270'} {$ENDIF}
```
with
{$LIBSUFFIX '270'} 

- Open the file in the Delphi 10.4 IDE and install it.

**Comment by drbond** [comment]
Yes I am using latest version which I downloaded as a zip file.
I am using Embarcadero Delphi 10.4 version 27.0.37889.9797.
Installation guide: Apologies, I meant to say that I was using the Anaconda installation guide.
Followed your suggestion of using modified Delphi 10.3 Python_D.dpk ({LIBSUFFIX '270'} successfully.
However, Demo2 requires (and I expect every other demo) Python32.dll. I have Python38.dll installed. So I guess that I have to source Python32.dll and then place in a path that Python4D can find. Also had a compile error on Demo 1 - it couldn't find 'Project1_Icon.ico'.

**Comment by pyscripter** [comment]
> I am using Embarcadero Delphi 10.4 version 27.0.37889.9797.
It seems that you have Delphi 10.4 and not Delphi 10.4.1 installed witch explains the issue you faced.  You may want to upgrade Delphi to 10.4.1 (massive number of fixes).

For setting up the Python Engine please read the instructions at the [Finding Python wiki page](https://github.com/pyscripter/python4delphi/wiki/FindingPython).  Using an Anaconda distribution complicates things a bi.

- Set the following properties
  - DLLName e.g. python38.dll
  - RegVersion e.g 3.8
  - Set UseLastKnownVerion property to False
  - Set the DLLPath to the path where the DLL is located
  - Set the AutoLoad property to False
  - In your FormCreate event handler of the MainForm or in another suitable place run the following assuming that PythonEngine 
is the name of the component
```pascal
    PythonEngine.SetPythonHome('your python installation directory')
    PythonEngine.LoadDLL
```

You also need to make sure that the \Library\bin path of the Anaconda distribution is on your system path.

**Comment by drbond** [comment]
Thanks for your prompt reply. I assumed that my Delphi 10.4 had been updated since GetIt Package manager says Patches 1 to 3 installed. Just Googled and found a post by Marco Cantu dated September 2nd referencing Delphi 10.4.1. Just before you posted your reply, I re-read Finding Python wiki page and set the properties as you describe (I just found this wiki difficult to understand. If extension.pas had been added to PythonEngine and PythonVersion.pas I would have homed in immediately instead of having to guess). However, I can't make sense of PythonEngine.SetPythonHome, etc. I tried this in FormCreate in one of the demos but there is no SetPythonHome appearing in code completion so it won't compile. Again I am missing something and this time cannot read between the lines. Without adding these two statements I get a 'Cannot initialise Python installation' or something like that runtime error which then crashes Delphi. Thanks for your help so far.

**Comment by pyscripter** [comment]
I thought the instructions above were clear enough.

- Set the following properties of your PythonEngine component
  - DLLName e.g. python38.dll
  - RegVersion e.g 3.8
  - Set UseLastKnownVerion property to False
  - Set the DLLPath to the path where the DLL is located (e.g. anaconda root folder)
  - Set the AutoLoad property to False
  - In your FormCreate event handler of the MainForm or in another suitable place run the following assuming that PythonEngine is the name of the component

So far so good?

Then in your Form OnCreate event handler add the following assuming that PythonEngine is the name of the component:
```pascal
    PythonEngine.SetPythonHome('your python installation directory')
    PythonEngine.LoadDLL
```

If the name of the PythonEngine component is PythonEngine1 then you add:
```pascal
    PythonEngine1.SetPythonHome('your python installation directory')
    PythonEngine1.LoadDLL
```

**Comment by drbond** [comment]
Thanks that does make it a little clearer but not completely. Before your most recent post, I edited PythonEngine.pas and PythonVersions.pas to set the DLLName etc. After your most recent post, I corrected FormCreate as advised. I then successfully compiled Demo4 but got a runtime error, 'what was it.. missing apostrophe'. But then following your recent post, in which you refer to setting DLLName,etc for the program's PythonEngine component, I reinstalled PythonEngine.pas and PythonVersions.pas. I then set DLLName, etc properties in FormCreate which you clearly didn't mention but where else should I set these. I am now back to getting the 'Error: Could not open DLL'python32.dll'. Clearly, I don't understand! I do want to cover Python4Delphi in my forthcoming Programming in Delphi book but I am going to have to set aside more time to read and understand the source files. I am in a Catch 22 situation since the site advises to look at / try  the demos to find out how to use Python4Delphi but by failing at the installation stage, I can't do this.

**Comment by pyscripter** [comment]
> I edited PythonEngine.pas and PythonVersions.pas to set the DLLName etc.

Bad idea

> I then set DLLName, etc properties in FormCreate which you clearly didn't mention but where else should I set these.

In the demos the main form includes a PythonEngine component.  You use the property inspector to change the component properties.

> 'Error: Could not open DLL'python32.dll'

I thought you had installed python 3.8.  The dll should be 'python38.dll'

If you post here you mainform pas and dfm files I will have a look.

**Comment by drbond** [comment]
Thanks again, you are being most helpful.I really appreciate this. Agree absolutely that changing PythonVersions.pas and PythonEngine.pas. But let me tell you how I got there:  Reading and understanding "Finding Python wiki page" for me was like landing in the middle of a foggy field and not being able to see the location of the entrance. The comments that you made above have provided the necessary orientation. I didn't see PythonEngine1 in the Object Inspector at first. I have now completed the set up as advised and successfully compiled Demo4 but the default script uses Python2.x print syntax. Also, before I could execute the script I got another print syntax error which appears to be unconnected with the default Python script: "File "<string>", line 2
    print "Python Dll: ", sys.version"
I selected continue and then I was able to test the default scripts (I had edited the print statements at design time to Python 3.x syntax.

Herewith MainForm.Pas and its dfm as requested:

[Archive.zip](https://github.com/pyscripter/python4delphi/files/5288613/Archive.zip)

**Comment by pyscripter** [comment]
There is a property of the PythonEngine called InitScript.  It contains python code that gets executed after python gets loaded and initialized.  You will need to convert that to Python 3 syntax as well.
Otherwise from what you say you are good.
