### ISSUE TITLE
Suggestion - make exposing Delphi objects to python painless by utilizing the new RTTI feature in D2010 (and above)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/python4delphi#17]
```
Hi,

I've a suggestion - make exposing Delphi objects to python painless by 
utilizing the new RTTI (runtime type information) feature in D2010 (and above).

Currently exposing a class to the hosted Python code needs to you to write too 
much code (check demo06), I guess if we take advantage of the new RTTI feature 
in the newer versions of Delphi, the process can be improved a lot.

For example, check out the Delphi chromium embedded project, all you have to do 
to expose the interface of any Delphi class to the JavaScript environment, is 
to register the class:

// this is your class exposed to JS 
  Test = class 
    class procedure doit(const v: string); 
  end; 

initialization 
// Register your class 
  TCefRTTIExtension.Register('app', Test);

// and in JavaScript code to call that class above:
app.doit(''foo'')', '', 0); 

Cool! Isn't it?

The above code was extracted from: 
http://groups.google.com/group/delphichromiumembedded/browse_thread/thread/1793e
7ca66012f0c/8ab31a5ecdb6bf48?lnk=gst&q=JavaScript+return+#

Some intro about RTTI introduced since D2010:
http://robstechcorner.blogspot.com/2009/09/delphi-2010-rtti-basics.html
```

Original issue reported on code.google.com by `edwin....@innovationgear.com` on 29 Oct 2011 at 8:50

**Comment by pyscripter** [comment]
Sorry about the delay in getting back to you on this.  I have tried merging the new RTTI staff, but after some effort, I still cannot get demo 31 to work without errors.  The attached file contains the modified WrapDelphi.pas.   If anyone can bring this to a state where all the tests of demo 31 pass, I will happily merge it.

[WrapDelphi.zip](https://github.com/pyscripter/python4delphi/files/1646869/WrapDelphi.zip)

**Comment by liuzg2** [comment]
i download the   wrapdelphi.pas
found  some   error
1、

procedure TPyDelphiWrapper.CreatePyFunc(AModule: TPythonModule; AMethodDef: PPyMethodDef);
var
  d : PPyObject;
begin
  if Assigned(FModule) and FModule.Initialized then
    with GetPythonEngine do
    begin
      d := PyModule_GetDict(FModule.Module);
      Assert(Assigned(d));
      if IsPython3000 then
        PyDict_SetItemString( d, AMethodDef^.ml_name, PyCFunction_NewEx(AMethodDef, nil, nil))
      else
        PyDict_SetItemString( d, AMethodDef^.ml_name, PyCFunction_New(AMethodDef, nil));
    end;
end;
 2   、when triiger draw  ,report accesse error  .
 def grdTestDrawCell(self, Sender, Col, Row, Rect, State):
       
       Sender.Canvas.TextRect(Rect, Rect.Left+2, Rect.Top+2, "%d " % (Col))

**Comment by pyscripter** [comment]
Implemented:
  - Major refactoring and clean-up
  - In Delhi version newer than XE, enhanced RTTI is used to provide access to
    methods, fields and properties.  So in most cases you no longer need to
    create wrapping classes.
  - __published__ property was replaced with the implementation of the __dir__()
    method, so that you can do for example dir(MainForm) to inspect the
    methods, fields and properties of MainForm.
  - Demo 31 has been updated to test/showcase some of the new features.

Study the updated demo 31 to see the improvements.

For example with the following definitions:
``` pascal
type
  TFruit = (Apple, Banana, Orange);
  TFruits = set of TFruit;

TTestRTTIAccess = class
private
  FFruit: TFruit;
  FFruits: TFruits;
public
  FruitField :TFruit;
  FruitsField: TFruits;
  StringField: string;
  DoubleField: double;
  ObjectField : TObject;
  procedure BuyFruits(AFruits: TFruits);
  procedure SetFormCaption(Form: TForm; ACaption: string);
  property Fruit: TFruit read FFruit write FFruit;
  property Fruits: TFruits read FFruits write FFruits;
end;
```
and the code: 
``` pascal
  p := PyDelphiWrapper.Wrap(TTestRTTIAccess.Create, soOwned);
  PythonModule.SetVar( 'rtti_var', p );
  PyEngine.Py_DecRef(p);
```

You can do in Python:

``` python
    def testRttiAccess(self):
        if DelphiVersion >= 15:
          rtti_var.Fruit = 'Apple'
          self.assertTrue(rtti_var.Fruit == 'Apple')
          rtti_var.Fruits = ['Apple', 'Banana']
          self.assertTrue(rtti_var.Fruits == ['Apple', 'Banana'])
          rtti_var.BuyFruits(['Apple', 'Orange'])
          self.assertTrue(rtti_var.Fruits == ['Apple', 'Orange'])
          rtti_var.SetFormCaption(MainForm, 'From TTestRTTIAccess')
          self.assertEqual(MainForm.Caption, 'From TTestRTTIAccess')
          rtti_var.FruitField = 'Apple'
          self.assertTrue(rtti_var.FruitField == 'Apple')
          rtti_var.FruitsField = ['Apple', 'Banana']
          self.assertTrue(rtti_var.FruitsField == ['Apple', 'Banana'])
          rtti_var.StringField = 'Hi'
          self.assertTrue(rtti_var.StringField == 'Hi')
          rtti_var.DoubleField = 3.14
          self.assertTrue(rtti_var.DoubleField == 3.14)
          rtti_var.ObjectField = MainForm
          MainForm.Caption = 'From TTestRTTIAccess.ObjectField'
          self.assertTrue(MainForm.Caption == 'From TTestRTTIAccess.ObjectField')

```
