### ISSUE TITLE
Error when trying to build [Fatal Error] Can't load package Python_D$(Auto).bpl. The system cannot find the file specified

### ISSUE THREAD

**Issue by umarsear** [pyscripter/python4delphi#190]
I get the above error when trying to install it in Delphi 10.4 professional edition. 

cloned from the repository using the ide, added the source directory to the path, fails when I try to build.

**Comment by pyscripter** [comment]
**You need to update to Delphi 10.4.1**

Otherwise edit the project file for 10.3- in an editor, change the LIBSUFFIX to 270 and then open in the IDE and install.
