### ISSUE TITLE
Best Practice To Embedded Flask-Framework

### ISSUE THREAD

**Issue by sashml** [pyscripter/python4delphi#192]
Hello all,

Can you please help me to dive deep and advice how I can embed Flask?
I just wonder in demo purposes how it should like.

Main goal is to get client-server application with 2 parts:

- web-server (Flask) with REST API running in standalone exe-file (Delphi) 
- Delphi client 

OR client-server approach inside single exe-file.

Thank you in advance!

**Comment by pyscripter** [comment]
This is an issue tracker, not a support forum.
P4D does not help you embed python (producing stand-alone executables).  You still need pythonxy.dll and at a least a minimal python distribution outside the executable.
