### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by drbond** [pyscripter/python4delphi#194]
Not sure how to communicate that I have made available a free sample of my Chapter 80 for Programming Effectively in Delphi for AS/A Level Computer Science. Apologies in advance for my ignorance. When I came to try Python4Delphi a week ago, I felt that my introduction would have benefitted from an accessible tutorial. This upload may go a little way towards addressing this.
[Chapter80Sample.pdf](https://github.com/pyscripter/python4delphi/files/5360994/Chapter80Sample.pdf)

**Comment by pyscripter** [comment]
THIS IS NICE!!

I could add it to the P4D Wiki, if this is OK with you.

**Comment by drbond** [comment]
Hi

Yes please do.

Best wishes

Kevin

**Comment by pyscripter** [comment]
Great.  Will do.  How do you want to be atrributed?  Is  Dr Kevin R Bond OK?

**Comment by pyscripter** [comment]
Added to the Wiki and linked from the Tutorials folder.
Thanks!
