### ISSUE TITLE
execute demos  on  UNIX 

### ISSUE THREAD

**Issue by ImageProcessingFMX** [pyscripter/python4delphi#196]
I compiled sample  "\python4delphi\Demos\FMX\SimpleDemo"  for linux 

Red Hat 7 Enterprise -> execution is OK 
Ubuntu 18.04  -> failed  with run time access violation error  , error @ libicuuc.so.60 
centOS 7 ->  failed  with run time access violation error , same lib error 

Any idea how to fix ?

**Comment by pyscripter** [comment]
A few months back, I have run the unit tests on Ubuntu 19 and it worked fine using   PythonEngine.UseLastKnownVersion := True;
Can you try with Ubuntu 19?

**Comment by pyscripter** [comment]
![IMG_20200501_114827 (Small)](https://user-images.githubusercontent.com/1311616/95788959-3ddefc80-0ce5-11eb-96d2-14d88311310d.jpg)

**Comment by ImageProcessingFMX** [comment]
guess the error  is due a buggy python installation  on my ubuntu computer
thanks for your fast reply
