### ISSUE TITLE
FPC - LongInt size on non-Windows 64bit platforms

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/python4delphi#197]
See https://github.com/Alexey-T/Python-for-Lazarus/issues/22

**Comment by pyscripter** [comment]
@Alexey-T Before I provide a fix, could you please do a test to make sure that the error exists?

All you need is to create a python engine at MacOS64 / Linunx 64, call
PyInt_FromLong and
PyInt_AsLong
and check whether they provide the correct answers..

**Comment by Alexey-T** [comment]
Ok
In Lazarus console demo, I did
```
procedure TfmMain.PythonEngineAfterInit(Sender: TObject);
const
  NTest: Longint = 1 shl 30;
var
  dir: string;
begin
  dir:= ExtractFilePath(Application.ExeName);
  {$ifdef windows}
  Py_SetSysPath([dir+'DLLs', dir+cPyZipWindows], false);
  {$endif}
  Py_SetSysPath([dir+'Py'], true);

  Caption:= BoolToStr(PythonEngine.PyInt_AsLong(PythonEngine.PyInt_FromLong(NTest)) = NTest, true);
end;  
```

app start in Ubuntu 20 x64 - caption is True

**Comment by Alexey-T** [comment]
(Ubuntu has Py 3.8)

**Comment by pyscripter** [comment]
Thanks.  Can you try the following
```pascal
var
  P1, P2: PPyObject;
with PythonEngine do begin
  P1 := PyInt_AsLong(1);
  P2 := PyNumber_Negative(P1);
  Assert(PyInt_AsLong(P2) = -1);
end;
```

**Comment by pyscripter** [comment]
@Alexey-T So what is the verdict?

**Comment by Alexey-T** [comment]
I was busy, will test today

**Comment by Alexey-T** [comment]
It didnt compile, fixed to
```

  with PythonEngine do begin
    P1 := PyInt_FromLong(1);
    P2 := PyNumber_Negative(P1);
    Assert(PyInt_AsLong(P2) = -1);
  end; 
```
and it runs OK here.
no error.

**Comment by pyscripter** [comment]
Very weird:
https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models
https://stackoverflow.com/questions/35844586/can-i-assume-the-size-of-long-int-is-always-4-bytes
and other documentations say that in Linux and MacOS long is 8 bits.
FPC longInt is 4 bits everywhere (@Alexey-T) Can you confirm that?

The discrepancy should cause the above to fail.  Shouldn't it?
Any thoughts?

**Comment by pyscripter** [comment]
@Alexey-T 

Could you please try the following as well:

```

  with PythonEngine do begin
    P1 := PyInt_FromLong(-1);
    P2 := PyNumber_Negative(P1);
    Assert(PyInt_AsLong(P2) = 1);
  end; 
```

**Comment by Alexey-T** [comment]
Yes, it is Linux x64, Py 3.8.
Last snippet also works ok! ie no exception. even BoolToStr() shows True.

**Comment by pyscripter** [comment]
Shall I close this issue then?

**Comment by Alexey-T** [comment]
It shows 4
```
procedure TForm1.FormCreate(Sender: TObject);
begin
  caption:= inttostr(sizeof(Longint))
end;
       
```

**Comment by Alexey-T** [comment]
App is for linux x64

**Comment by pyscripter** [comment]
@Alexey-T Could you please try the above tests on a Mac, so that I can close the issue.

**Comment by Alexey-T** [comment]
> 
> 
> @Alexey-T Can you confirm that FPC longInt is 32 bits (4 bytes) in Ubuntu 64 bits?
> Shall I close this issue then?

https://www.freepascal.org/docs-html/ref/refsu4.html
I didnt test on mac yet =)

**Comment by Alexey-T** [comment]
Remark In newer Delphi versions, the longint type is platform and CPU dependent. This is not so in FPC, where longint is 32-bit on all platforms.

!!!

**Comment by pyscripter** [comment]
> Remark In newer Delphi versions, the longint type is platform and CPU dependent. This is not so in FPC, where longint is 32-bit on all platforms.
> 
> !!!

Has always been since Linux, MacOS and Android were introduced.  But that is the case in C and C++.  Delphi matches the C compilers, fpc doesn't.

**Comment by Alexey-T** [comment]
>Can you confirm that FPC longInt is 32 bits (4 bytes) in Ubuntu 64 bits?
Shall I close this issue then?

Yes.

**Comment by pyscripter** [comment]
@Alexey-T  Any chance of testing on the Mac?

**Comment by pascaldragon** [comment]
FPC developer here. For FPC there is no need to test the size of LongInt, because LongInt _does not_ change its size depending on the platform. We are aware of the discrepancy with Delphi, but we consider this a known incompatibility where the backwards compatibility with older FPC code is more important than compatibility with Delphi, not to mention that originally Integer had been considered the type that changes width (as can be seen with the change of Integer from 2 Byte to 4 Byte when moving from Turbo Pascal to Delphi). Though that wasn't continued for 64-bit either, for both FPC and Delphi.

**Comment by pyscripter** [comment]
@pascaldragon  The issue is (might be)  that Delphi's LongInt matches the size that  C compilers use with long on Unix and MacOS.  fpc does not.   Python is compiled with C compilers.

**Comment by pascaldragon** [comment]
In FPC you should use the types from `ctypes` unit to interface with C code, in this case `clong`. Or you need to declare your own types that map to the appropriate Pascal types for your platform. Except for Win64 you can for example use an alias to NativeInt.

**Comment by pyscripter** [comment]
Your missing the point:

C long and Delphi LongInt:
- Windows 64nits size 4  (NativeInt would fail here)
- Linux 64 bits size 8
- MacOS 64 bits size 8

in fpc always 4.

**Comment by pascaldragon** [comment]
Yes, FPC's LongInt is of size 4 and this is by choice and if you need to interface with C code you need to use the correct types that are intended for that purpose.

So yes, you need to use `IfDefs` to handle this correctly.

**Comment by pyscripter** [comment]
> So yes, you need to use `IfDefs` to handle this correctly.

That is exactly what I though hence this issue.  However @Alexey-T reports that it works as is.

**Comment by pascaldragon** [comment]
That code probably only works by accident due to the calling convention:
```
var
  P1, P2: PPyObject;
with PythonEngine do begin
  P1 := PyInt_FromLong(1);
  P2 := PyNumber_Negative(P1);
  Assert(PyInt_AsLong(P2) = -1);
end;
```

The `PyInt_FromLong` only has one argument which is passed as a 64-bit register and on x86_64 a move of a 32-bit value to a 64-bit register will always result in an implicit clear of the upper 32-bit. Thus that call will work correctly no matter if the size of `LongInt` is 4 or 8.

The `PyNumber_Negative` is not relevant as that is on the C side only and works on pointers.

The `PyInt_AsLong` is interesting again: the result in passed in `RAX` as a 64-bit value (in this case `$ffffffffffffffff`) even though FPC will only expect a 32-bit one if you use `LongInt` as result type. The `-1` will be handled as a 32-bit value with the hexadecimal value `$ffffffff`. The comparison will be a 32-bit comparison of `EAX` (!) with `-1` thus it will be true.

To see your test failing you need to ensure that values > 2^32 are returned as then the 32-bit conversion will fail.

**Comment by pyscripter** [comment]
Interesting!

Could you please come up with a good test for this?

**Comment by pascaldragon** [comment]
Simply use a value `High(LongInt)`. I don't have Python4Delphi installed, so I can't test it directly, but the following example illustrates it (I've used `external` to simulate the difference between the Python library and the FPC code):

```
program tlongint;

function Test: Int64; public; alias:'Test64';
begin
  Test := -123412341234;
end;

function Test32: LongInt; external name 'Test64';

var
  b: Boolean;
begin
  b := Test32 = -123412341234;
  Writeln(b);
end.
```

This will write `FALSE`. If I use `-1` instead for both constants it will write `TRUE`. (Note: I only tested this on x86_64, on e.g. aarch64 it might be different)

**Comment by pyscripter** [comment]
@Alexey-T Could you please do some testing of this issue given what @pascaldragon is saying above.

**Comment by pascaldragon** [comment]
The second example you gave to @Alexey-T shows similar behavior:

```
program tlongint;

function Test2(aArg: Int64): PInt64; alias:'Test2_64';
begin
  New(Test2);
  Test2^ := aArg;
end;

function Test2_32(aArg: LongInt): PInt64; external name 'Test2_64';

function Negate(aArg: PInt64): PInt64;
begin
  New(Negate);
  Negate^ := -aArg^
end;

function Test64(aArg: PInt64): Int64; alias:'Test64';
begin
  Test64 := aArg^;
end;

function Test32(aArg: PInt64): LongInt; external name 'Test64';

var
  b: Boolean;
  p1, p2: PInt64;
begin
  p1 := Test2_32(-1);
  p2 := Negate(p1);
  b := Test32(p2) = 1;
  Writeln(b);
end.
```

For `-1` and `1` this will result in `TRUE`, but for e.g. `-123412341234` and `123412341234` it will write `FALSE` (as expected for me).

So, yes, this needs to be tested with correct numbers to be seen. ;)

**Comment by pyscripter** [comment]
The "good news" is that due to the 2-complement representation of negative numbers, you will not get an error even if you misspecify the size of an integer argument, unless the number does not fit in the specified size!
