### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/python4delphi#201]
Python 2 is no longer supported or updated.   Supporting both Python 2 & Python 3.x is becoming increasingly cumbersome.
I am proposing to remove Python 2 support at some point in the near future.

I you have objections please air them here.

**Comment by pyscripter** [comment]
@Alexey-T  Any thoughts?

**Comment by Alexey-T** [comment]
I use this in CudaText, only for Py3. But: older Linux systems have Py2 installed, so some users may need Py2.

**Comment by pyscripter** [comment]
@Alexey-T So CudaText does not use Python 2.   Users that want to build applications for Python 2 can always use older versions of these components.

**Comment by Alexey-T** [comment]
Yes, I support this

**Comment by Alexey-T** [comment]
Maybe some C++ apps use Py2 but it's hard to find Delphi ones.

**Comment by pyscripter** [comment]
@Alexey-T I have removed Python 2 from the branch "python3".
The code now is about 1000 lines shorter.  Moreover the interface is correct, which was not the case before.

I would appreciate any feedback/checking at this stage before I commit to master.

**Comment by pyscripter** [comment]
I have now committed the changes.
