### ISSUE TITLE
Small patch here

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#202]
https://forum.lazarus.freepascal.org/index.php/topic,46361.msg380703.html#msg380703

**Comment by pyscripter** [comment]
It is already 
   ` property ThreadExecMode: TThreadExecMode read fThreadExecMode write fThreadExecMode;`

in this repository!

And there is a nice demo 33 about using threads, sub-interpreters, interrupting the running threads and more.
