### ISSUE TITLE
Add ifdef for CheckRegistry()

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#206]
Pls move all calls under ifdef, I want to easy hide this for CudaText

**Comment by pyscripter** [comment]
CheckRegistry is kind of innocent.
-  Only used in Windows
-  It does nothing if OnPathInitialization is not defined.

What is the issue?

The Registry is also used by IsPythonVersionRegistered.  Also Windows only.  Not used if DLLPath is not empty.

How can the above possibly affect CudaText?

**Comment by Alexey-T** [comment]
Seems I didn't test it much, sorry, will check it
