### ISSUE TITLE
Major issue on windows python 3.6 x64 DLL

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#210]
![py---](https://user-images.githubusercontent.com/4154978/96866439-fc341b80-1473-11eb-8b1d-351bc7187b90.png)

@tmsg-gh This is CudaText beta crash-- reason is sync with python4delphi, not encoding code.

**Comment by Alexey-T** [comment]
Already deleted here! sorry. closing.

**Comment by blacklat** [comment]
in my opinion and it is certainly the same as most, if I need to load the python dll this project has no use ...
