### ISSUE TITLE
Preparing tests for NumberServices

### ISSUE THREAD

**Issue by LennertP** [pyscripter/python4delphi#211]
Hi all,

I started working on tests for the NumberServices (e.g. nsAdd, nsMultiply), see attached.
[NumberServicesTest.zip](https://github.com/pyscripter/python4delphi/files/5429526/NumberServicesTest.zip). What do you think?

Best regards,

Lennert.

**Comment by pyscripter** [comment]
Thanks.  I am having a look right now...

**Comment by LennertP** [comment]
Thank you. I noticed I left some commented out code, but will remove this later together with processing your comments.

**Comment by pyscripter** [comment]
I have made some minor changes and added the tests to the master branch.
Thanks a lot!!

**Comment by LennertP** [comment]
Thank you, great!

**Comment by LennertP** [comment]
I noticed I left small memory leaks. By adding the following this should be resolved:

destructor PyTRandomInteger.Destroy;
begin
  FRandomInteger.Free;
  inherited;
end;

This only shows up when P4DTests.exe is started from the command prompt, otherwise the window closes too quickly. There are also other leaks reported, but these seem not to be caused by my tests:

Done testing.
Tests Found   : 52
Tests Ignored : 0
Tests Passed  : 52
Tests Leaked  : 0
Tests Failed  : 0
Tests Errored : 0
Done.. press <Enter> key to quit.
Unexpected Memory Leak
An unexpected memory leak has occurred. The unexpected small block leaks are:

57 - 72 bytes: Unknown x 2
89 - 104 bytes: Unknown x 1

**Comment by pyscripter** [comment]
Fixed as well as the other memory leaks.
Thanks!

**Comment by LennertP** [comment]
That's quick, thank you for looking into this!
