### ISSUE TITLE
New Tutorial ready for upload

### ISSUE THREAD

**Issue by drbond** [pyscripter/python4delphi#212]
Hi all
Have finished the chapter on Python for Delphi and about to send off to ECS's reviewer. It is available as a free chapter as before so is a replacement for the tutorial that was uploaded earlier.
[Chapter80Tutorial.pdf](https://github.com/pyscripter/python4delphi/files/5439334/Chapter80Tutorial.pdf)
Best wishes

Kevin

**Comment by pyscripter** [comment]
Done.  Thanks.
