### ISSUE TITLE
Access violation on delete TPythonEngine from form

### ISSUE THREAD

**Issue by lmbelo** [pyscripter/python4delphi#216]
<h4>Drag and drop a TPythonEngine from Pallete to a form. Delete TPythonEngine component from form and an access violation will raise.</h4>

This issue was reproduced in the following RAD Studio version and operating system:
Embarcadero® RAD Studio 10.4 <b>Version 27.0.38860.1461 </b>
Delphi 10.4 and C++ Builder 10.4 Update 1
Windows 10 (Version 10.0, <b>Build 18363</b>, 64-bit Edition

![img_1](https://user-images.githubusercontent.com/8376898/99443684-e6dad180-28f9-11eb-948b-8643e64dc9da.jpg)

![img_2](https://user-images.githubusercontent.com/8376898/99443695-ec381c00-28f9-11eb-99cf-de4ea2496d5c.png)

**Comment by pyscripter** [comment]
Thanks for the report!  For some reason I cannot reproduce here (no access violation).  In any case I would be happy to receive a PR about this.

**Comment by pyscripter** [comment]
@lmbelo Is this still an issue?

**Comment by lmbelo** [comment]
Not happening after new package design.
