### ISSUE TITLE
No components on 10.3.3

### ISSUE THREAD

**Issue by sergioalejanpro** [pyscripter/python4delphi#226]
Hello...

I got a problem when installing on Delphi 10.3.3, there is no error, the final installation message states that all is installed ok, but it doesn't show the components names... Also there is no folder/components for Python on the palette...

I have tried installing from downloaded zip and cloning the project, but same problem here...

Any ideas ?

![image](https://user-images.githubusercontent.com/43328025/99906653-f19cba00-2c9d-11eb-8bd7-7fb403bf31b5.png)

**Comment by lmbelo** [comment]
Hello, @sergioalejanpro. Thank you for your report. I'm working on it. We apologise you're facing troubles under installation process.

**Comment by pyscripter** [comment]
Could you please try again.  The latest commit should fix that.

**Comment by sergioalejanpro** [comment]
Yes, it's working... Now it's time to test it... Thanks !
