### ISSUE TITLE
Unable to install package (p4dlaz.lpk) with Lazarus

### ISSUE THREAD

**Issue by neurolabusc** [pyscripter/python4delphi#228]
Using Lazarus Trunk and FPC 3.2 on Intel MacOS, I am unable to install p4dlaz.lpk.

1. Package fails to compile:
```
PythonEngine.pas(2861,16) Error: Incompatible types: got "TThreadID" expected "NativeInt"
```
2. lpk refers to a file that does not exist:
![lpk](https://user-images.githubusercontent.com/8930807/100135155-3c156680-2e57-11eb-8ea2-9b1ced501bff.png)

**Comment by pyscripter** [comment]
@lmbelo fpc package needs fixing

**Comment by lmbelo** [comment]
Hello, @neurolabusc . Thank you for your report.
We apologise you're facing troubles under installation process.
I'm currently working on a fix. It will be available soon.

**Comment by csevast** [comment]
I confront the same problem in Delphi Community Edition.

**Comment by lmbelo** [comment]
Hello, @csevast .
Please, confirm your Delphi version.

**Comment by csevast** [comment]
Delphi 10.3 Version 26.0.36039.7899

**Comment by lmbelo** [comment]
Be sure you're using the 10.3- package.

**Comment by csevast** [comment]
I do use 10.3- package. I tried the corresponding package for Lazarus/FPC and the same file is missing.

**Comment by lmbelo** [comment]
@csevast thank you to provide more details.
I'm going to provide a fix.

**Comment by pyscripter** [comment]
This should now be fixed.  Please let us know if something does not work.

**Comment by csevast** [comment]
Great, the package installation is flawless now, in both Delphi Community Edition 10.3 and Lazarus 2.0.10. But the issue with the missing `PythonGUIInputOutput` unit insists in the demo and sample code. I will open a new issue about it.

**Comment by lmbelo** [comment]
@csevast could you reproduce the issue, please?

**Comment by csevast** [comment]
@lmbelo, I've already fixed the problem and a pull request is also merged by @pyscripter.  But there is another problem, in the Python code of Demo31, in which a `spam` module is need. Is this https://pypi.org/project/spam/ the needed package?

**Comment by lmbelo** [comment]
@csevast great, thank you! 
Actually, `spam` is related to a **TPythonModule** component, whose declares a spam module. 
Please, open an issue. We will work on a fix.
