### ISSUE TITLE
Problems after upgrade

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/python4delphi#23]
```
What steps will reproduce the problem?
1. Use P4D 3.33 with DelphiXE and Python25 on Win7

I'm migrating a project from Delphi 2006 to XE, so I needed to upgrade P4D too. 
It compiles normally, but when I try to execute the following code, I get an 
error.

Code:

import os

Error

exceptions.ImportError: No module named os.


It's working fine on Delphi 2006.

Thanks,

Weverton
```

Original issue reported on code.google.com by `wever...@tron.com.br` on 16 May 2013 at 9:20

**Comment by pyscripter** [comment]
There is no need to package Python with your application.  Just make sure that you have a python version from www.python.org installed and registered.

For example to use  Python 2.7 from www.python.org all you have to do is
Uncheck UseLastKnownVersion.
Set RegVersion to 2.7
and DLLName to python27.dll
If you are using some other installation of python (I see you have it in "C:\Python27") you need to also fill the DLLPath. For example you can set it to "C:\Python27".
