### ISSUE TITLE
thread_id is of type TThreadID in FPC/Lazarus

### ISSUE THREAD

**Issue by neurolabusc** [pyscripter/python4delphi#234]
With FPC the function [GetCurrentThreadId()](https://www.freepascal.org/docs-html/rtl/system/getcurrentthreadid.html) returns type TThreadID, but the current code expects NativeInt.Can you type cast this, or is that not what is intended:

```
  function  TPythonInputOutput.GetCurrentThreadSlotIdx : Integer;
  var
  {$IFDEF FPC}
  thread_id : TThreadID;
  {$ELSE}
    thread_id : NativeInt;
  {$ENDIF}
    i : Integer;
  begin
    thread_id := GetCurrentThreadId;
    for i := 0 to FLinesPerThread.Count-1 do
      if NativeInt(FLinesPerThread.Objects[i]) = NativeInt(thread_id) then
        begin
          Result := i;
          Exit;
        end;
    Result := FLinesPerThread.AddObject( '', TObject(thread_id) );
  end;
```

**Comment by pyscripter** [comment]
The code is reported to compile with fpc.  Why do you want to introduce this change?

**Comment by pyscripter** [comment]
Does this work?

function  TPythonInputOutput.GetCurrentThreadSlotIdx : Integer;
var
  thread_id : TObject;
  i : Integer;
begin
  thread_id := TObject(GetCurrentThreadId);
  for i := 0 to FLinesPerThread.Count-1 do
    if FLinesPerThread.Objects[i] = thread_id then
      begin
        Result := i;
        Exit;
      end;
  Result := FLinesPerThread.AddObject( '', thread_id );
end;

**Comment by pyscripter** [comment]
I have committed the above change which should not work with all versions.
