### ISSUE TITLE
Exception Dynamically Creating Engine

### ISSUE THREAD

**Issue by peterjslater** [pyscripter/python4delphi#237]
Hi I am trying to create the Python Engine without using a form, so creating the components dynamically.
I am using Demo17 as the starting point.
I am using Delphi 10.2 and 64 Bit on Windows 10.
e.g.

```
procedure TForm1.FormShow(Sender: TObject);
begin
    PythonEngine := TPythonEngine.Create(nil);
    PythonModule := TPythonModule.create(nil);
    PythonGUIInputOutput1 := TPythonGUIInputOutput.Create(nil);
    PythonEngine.IO := PythonGUIInputOutput1;
    PythonGUIInputOutput1.Output := Memo2;
    PythonEngine.AutoLoad := True;
    PythonModule.Engine := PythonEngine;
    PythonModule.ModuleName := 'test';
end;

```
It is starting up ok, but when I try to click Execute Script, i get an exception
![image](https://user-images.githubusercontent.com/15810640/101096058-b6d64280-360a-11eb-8c66-b79aa950b9d1.png)

I have attached the modified demo as a zip

[Demo17.zip](https://github.com/pyscripter/python4delphi/files/5639302/Demo17.zip)

**Comment by peterjslater** [comment]
I found a solution to this, just need to load the dll e.g.

`procedure TForm1.FormShow(Sender: TObject);
begin
    PythonEngine := TPythonEngine.Create(nil);
    PythonModule := TPythonModule.create(nil);
    PythonGUIInputOutput1 := TPythonGUIInputOutput.Create(nil);
    PythonEngine.IO := PythonGUIInputOutput1;
    PythonGUIInputOutput1.Output := Memo2;
    PythonEngine.AutoLoad := True;
    PythonModule.Engine := PythonEngine;
    PythonModule.ModuleName := 'test';
    **PythonEngine.LoadDll;**
end;`

**Comment by pyscripter** [comment]
See also demo 34 that does that.
