### ISSUE TITLE
Simple check on NumPy version throws floating point div by zero

### ISSUE THREAD

**Issue by PrinzAxel** [pyscripter/python4delphi#239]
Hi there,

Just starting out using P4D and tried to import NumPy and confirm the version.
Got the error below when I clicked the run button.
When I clicked it again it worked.

Cheers,

Aidan.

![image](https://user-images.githubusercontent.com/4063061/101532659-c51aba80-398c-11eb-939a-93d3e9912391.png)

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/MaskFPUExceptions.
