### ISSUE TITLE
Can't use Python38.dll

### ISSUE THREAD

**Issue by PrinzAxel** [pyscripter/python4delphi#240]
Hi there,

Just starting out with P4D.
When I change the Python version to 3.8 and even explicitly set the pathing to the Anaconda folder in ProgramData everything builds OK but trying to run the Webinar 1 Simple Demo 1 just results in the app immediately failing to run.
If I add the form create handler and set a breakpoint it never gets there.

Cheers,

Aidan.

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/FindingPython for instructions on how to use Anaconda.
