### ISSUE TITLE
Problem using Pandas straight away

### ISSUE THREAD

**Issue by PrinzAxel** [pyscripter/python4delphi#241]
Hi there,

Simply importing Pandas and then trying to load a dataframe from a csv throws the error below.
Any help would be very much appreciated.

Cheers,

Aidan.

![image](https://user-images.githubusercontent.com/4063061/101533833-4030a080-398e-11eb-8149-07c53bdaa124.png)

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/MaskFPUExceptions.
