### ISSUE TITLE
numpy demo

### ISSUE THREAD

**Issue by hsauro** [pyscripter/python4delphi#242]
Is there example code that shows how to interact with numpy from Delphi? Ie get values from numpy to Delphi or manipulate numpy values from Delphi? There is a wealth of functionality in numpy and scipy that could be used if it were possible.

**Comment by pyscripter** [comment]
Please use the forum to ask questions and not the issue tracker.

See https://github.com/pyscripter/python4delphi/tree/master/Tutorials/Webinar%20II/VarPythDemo
