### ISSUE TITLE
TPythonEngine.EvalString or TPythonEngine.PyObjectAsVariant Interface not returned

### ISSUE THREAD

**Issue by vanners** [pyscripter/python4delphi#244]
I am able to pass a Delphi interface into the Python engine, and it functions normally within the Python environment, however if I pass it back out via a call to EvalString, then map it back to a variant via PyObjectAsVariant the returned variant is Null.  I was expecting a varUnknown that I could then cast back into the interface.

I don't know if the failure is within the EvalString or PyObjectAsVariant.  I cannot find an alternative method to convert the PPyObject back to an interface, nor to test the type of the PPyObject.

**Comment by vanners** [comment]
I have determined that it is PyObjectAsVariant that fails to collect the varUnknown variant type.  The PPyObject identifies as PascalInterface.  Now the problem is, how to get the interface.  PPyObject is just a record.

**Comment by pyscripter** [comment]
Indeed PyObjectAsVariant does not support varUnknown.

**Comment by vanners** [comment]
Thanks for letting me know how not to access the interface.  The question still remains: how to get the interface?  In particular, given the PPyObject, how can I get the wrapped interface?  Alternatively, is there any documentation for this topic and if so, where?

**Comment by pyscripter** [comment]
> given the PPyObject, how can I get the wrapped interface

You use PythonToDelphi to get the TPyPascalInterface object and then use the Value property to get a TValue containing the interface.
