### ISSUE TITLE
Installation Error Delphi 10.4

### ISSUE THREAD

**Issue by Clarisecas** [pyscripter/python4delphi#266]
Delphi 10.4
Installation of all design-time packages fail

e.g ...............C:\Installed_\Python4Delphi\Packages\Delphi\Delphi 10.4+\dclPython.dpk
Install Error........... Can't load package c:\users\public\documents\embarcadero\studio\21.0\bpl\dclPython270.bpl
The specified module could not be found

Althou Build Error...... File not found: 'Python.res'
Build FAILED.
MSBUILD : error E1026: E1026 File not found: 'Python.res'
C:\Installed_\Python4Delphi\Packages\Delphi\Delphi 10.4+\dclPython.dpk(39,2): error F2063: F2063 Could not compile used unit 'PythonReg.pas'

**Comment by lmbelo** [comment]
Hello, @Clarisecas! 
Unfortunately, I can't reproduce your issue. 
Please, checkout a clean copy of repo and open the "P4DComponentSuite" project group.

**Comment by pyscripter** [comment]
@Clarisecas I have also installed from the IDE without issues.

**Comment by pyscripter** [comment]
@lmbelo In any case I think {*.res} can be removed from the package files.

**Comment by Clarisecas** [comment]
I have checkout a clean copy of repo and open the "P4DComponentSuite" project group(It would be great to mention this file in installation). All installed well without any issue. Yesterday I have also tried clean copy, but never open "P4DComponentSuite" . Obviously it was not my day. Do appreciate your time and advice for solving this.

Suggested minor update for WIKI Installation guidance for your review and consideration https://github.com/pyscripter/python4delphi/wiki/Installation:
3. Add the source sub directories ( ~~e.g.,~~ D:\Components\P4D\Source ) for all targets and ~~,~~( D:\Components\P4D\Source\vcl and/or D:\Components\P4D\Source\fmx) to the IDE's library path for the targets you are planning to use.

4. Open "P4DComponentSuite" project group. Build and install the dclPython, dclPythonVcl and dclPythonFmx design-time packages. It can be found under Packages\Delphi\Delphi 10.4+ directory.

**Comment by pyscripter** [comment]
Installation instructions clarified.
