### ISSUE TITLE
some weird code in func

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#268]
```
function GetPythonVersionFromDLLName(const DLLFileName : string): string;
begin
  Result := DLLFileName[{$IFDEF MSWINDOWS}7{$ELSE}10{$ENDIF}] + '.' + DLLFileName[{$IFDEF MSWINDOWS}8{$ELSE}11{$ENDIF}];
end;
```
you use fixed str index 7 and 10. and 8 and 11. what about macOS index?

**Comment by pyscripter** [comment]
This function has been removed.

Replaced with 

function  SysVersionFromDLLName(const DLLFileName : string): string;
procedure PythonVersionFromDLLName(const LibName: string; out MajorVersion, MinorVersion: integer);
