### ISSUE TITLE
EvalString functionality gap

### ISSUE THREAD

**Issue by vanners** [pyscripter/python4delphi#269]
There appears to be no way to evaluate anything that requires importing a library to work.  I thought I had a solution, however EvalString loses the context created in the preceeding ExecString call.
Delphi code:
```delphi
engPython.ExecString(code, pyParams, pyGlobals);
  var pyVal := engPython.EvalString(command, pyParams, pyGlobals);
```
Python code:
```python
import DelphiLib
import os
               
def CountLines():
    filename = DelphiLib.ProvideFromDB('MyFile')
    file = open(filename)
    lineCount = 0
    for line in file:
        lineCount = lineCount + 1
    file.close()
    os.remove(filename)
    return lineCount
```

In this scenario code is everything in the python code above, and command is simply:
CountLines()

The call to CountLines works, however the libraries are not available in the EvalString and create errors when DelphiLib, or even os is referenced within the function call.

Further, if the python code was rewritten to avoid using libraries within the function call, there seems to be no way of transferring values from variables created in the Python main line code into the called function.

e.g.
```python
import DelphiLib
import os

filename = DelphiLib.ProvideFromDB('MyFile')
file = open(filename)
lineCount = 0
for line in file:
    lineCount = lineCount + 1
file.close()
os.remove(filename)
               
def CountLines():
    return lineCount
```

**Comment by pyscripter** [comment]
> The call to CountLines works, however the libraries are not available in the EvalString and create errors when DelphiLib, or even os is referenced within the function call.
I am not sure what you mean.  Does it work or it doesn't?


If you want the variables and imports in the script to be added to the global namespace and be accessible later, you have to execute the script with the main module globals and locals.  The easiest way is to use

engPython.ExecString(code)  or  engPython.ExecString(code, nil, nil);

You can also make imports available globally using VarPyth's  Import function, e.g. Import('os')

In your final example the code is wrong.  You need to write:

```python
def CountLines():
    global lineCount
    return lineCount
```

**Comment by vanners** [comment]
What I meant was that the mechanism of ExecString followed by EvalString worked.

e.g. Python Code:
```python
def Hypotenuse(X, Y):
    print ('Opposite', X)
    print ('Adjacent', Y)
    return pow(pow(X,2) + pow(Y,2), 0.5)
```
Command:
Hypotenuse(3, 4)

works as expected.

I have taken your advice, but I needed to pass in locals, so now my Delphi code looks like:
```delphi
  engPython.ExecString(code, pyParams, nil);
  var pyVal := engPython.EvalString(command, pyParams, nil);
```
and that works perfectly.

Thanks
