### ISSUE TITLE
Difference between pre-created interfaces, and interfaces generated within python code

### ISSUE THREAD

**Issue by vanners** [pyscripter/python4delphi#270]
There is a piece of code that converts an interface into a PPyObject:

```delphi
var
  something: PPyObject;
begin
  //...
  someInterface := TSomething.Create;
  something := wrpPython.WrapInterface(TValue.From<ISomething>(someInterface));
```
This works when used in the context:
```delphi
  var pl := engPython.PyDict_New();
// (Insert above code)
  engPython.PyDict_SetItem(pl, engPython.VariantAsPyObject('Something'), something);
  engPython.ExecString(edtScript.Lines.Text, pl, nil);
  var pyVal := engPython.EvalString(edtCommandLine.Text, pl, nil);
```
it does not work when provided through a wrapped Delphi method:
```delphi
function TForm3.MakeSomething(pself, args: PPyObject): PPyObject;
var
  someInterface: ISomething;
begin
  someInterface := TSomething.Create;
  Result := wrpPython.WrapInterface(TValue.From<ISomething>(someInterface));
end;
```
when called by
```python
import DelphiModule

s = DelphiModule.MakeSomething()
print(s.SaySomething())
```
I get the following error message:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
TypeError: "SaySomething" called with invalid arguments.
Error: Access violation at address 0040E695 in module 'PythonIntfTest.exe'. Read of address 00000065

**How do I create an interface from within Python?**  (my end goal is to populate the data inside the interface in the Python code, then pass the interface out to Delphi).  Note: when the interface is passed in (via the pl variable above), it can also be returned successfully and all methods of the interface function correctly within Python.  When it is generated nothing works except print(s).
Please note: It is important that the item created is an interface, and not an object due to the conversion required when passing it back out to Delphi.

**Comment by pyscripter** [comment]
- Firstly, yοu need to understand Interface and Python object reference counting.   

- Secondly,  WrapDelphi wrap Delphi methods converting Delphi types to Python types.  

It could wrap for example
function TForm3.MakeSomething: IInterface
but not function TForm3.MakeSomething(pself, args: PPyObject): PPyObject;

You are mixing different ways of wrapping Delphi methods.

- Thirdly.  This is an issue tracker and not a support forum.  Please address such questions to https://en.delphipraxis.net/?forumId=39
