### ISSUE TITLE
possible bug in PythonVersionFromDLLName

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#273]
https://github.com/Alexey-T/Python-for-Lazarus/commit/c4a0720a2b1b83d19cd50fe26a42efcf25f88d64

Func converts
 MajorVersion := StrToIntDef(S[NPos], 3);

for string 'libpython3.10.so'!!
@pyscripter @sikmir

**Comment by pyscripter** [comment]
I don't get it.  Could you please explain.

**Comment by Alexey-T** [comment]
I replace this issue with #274
