### ISSUE TITLE
Fails To Handle multiprocessing Properly

### ISSUE THREAD

**Issue by FMXExpress** [pyscripter/python4delphi#278]
When deploying a script using multiprocessing it opens multiple versions of the Delphi EXE.

Sample code:
```
from multiprocessing import Pool

def convert_vid(fname):
    # do the heavy lifting
    # ...

if __name__ == '__main__':
   pool = Pool(processes=4) 
   pool.map(convert_vid, [VIDEO_SET_1, VIDEO_SET_2, VIDEO_SET_3, VIDEO_SET_4])

```
[https://stackoverflow.com/questions/33518282/running-python-script-parallel](https://stackoverflow.com/questions/33518282/running-python-script-parallel)

![multiprocess](https://user-images.githubusercontent.com/7482023/105197727-c1cd2f80-5af1-11eb-87d2-a268064680f4.png)

[PRayTrace.txt](https://github.com/pyscripter/python4delphi/files/5843513/PRayTrace.txt)

**Comment by pyscripter** [comment]
You need to change sys.executable to point to the python.exe

**Comment by fjames003** [comment]
Setting the sys.executable does not fix this issue for multiprocessing.Pool.

I provided an event handler for the OnAfterInit PythonEngine event, which simply sets sys.executable equal to PythonEngine.DllPath, with the added 'python.exe' suffix.

If I then print(sys.executable) in Demo01, it correctly prints the path to the Python that the demo project is using, 
however if I then try to execute multiprocessing code, it launches more Demo01.exes.

So simply setting sys.executable is not enough to avoid this issue. Is there another work around that you can think of that may be needed to properly get multiprocessing working?


I would be happy to provide a modified Demo01 that illustrates this issue, including your proposed fix that does not seem to work, if that would be helpful.

**Comment by pyscripter** [comment]
I have looked into this and concluded that it is not possible to use multiprocessing from an in memory script.  You have to run a file physically saved on disk.  This is not related to P4D but rather to the way multiprocessing works.  The spawned processes need to have access to the script that started them and they do that by accessing the file on disk.

To convince yourself start a python interpreter and try the following:

```python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> script = """
... from multiprocessing import Pool
...
... def f(x):
...     return x*x
...
... if __name__ == '__main__':
...     with Pool(5) as p:
...         print(p.map(f, [1, 2, 3]))
... """
>>> exec(script)
```

The python interpreter will crash and go into an infinite loop.

Now save the following into a file and run it with python:
```python
script = """
from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))
"""
exec(script)
```

It will run fine.

**Comment by fjames003** [comment]
This does appear to be a limitation the multiprocessing module. However, noticing that the problem seemed related to pickling (based on the errors the interpreter gave), I thought to try [pathos.multiprocessing](https://pypi.org/project/multiprocess/) which solves some of the issues I have had with pickling in the past.

if you modify your above example to simply use the pathos module like so:
```
>>>script = """
... from pathos.multiprocessing import Pool
...
... def f(x):
...     return x*x
...
... if __name__ == "__main__":
...     with Pool(5) as p:
...         print(p.map(f, [1, 2, 3]))
... """
>>>exec(script)
[1,4,9]
>>>
```
the result is returned without any infinite loop, and without saving the script to a file.

However if you were to run the following code in Demo01 of P4D, more Demo01 executables would be launched even after modifying sys.executable. So is there a solution to avoid spawning the main application when attempting to spawn sys.executables?

Code for Demo01:
```
from multiprocessing import Pool

def f(x):
  return x*x

with Pool(5) as p:
  print(p.map(f, [1, 2, 3]))
```
Results in more Demo01.exe being launched.

So there still exists an issue with P4D that I would like to solve.

**Comment by pyscripter** [comment]
You can try the following:

Add an event handler for OnBeforeLoad and add the following
PythonEngine1.SetProgramName(PathToPythonExe)

Does it help?

**Comment by fjames003** [comment]
Unfortunately, calling SetProgramName in BeforeLoad makes no difference.
If you simply `print(sys.argv[0])` you can see its still the path to Demo01, and multiprocess will launch Demo01.

Upon further investigation, it seems that this may be an issue with embedding Python.
See [Issue Ignoring Program Name](https://bugs.python.org/issue31349) and [Issue with GetProgramFullPath](https://bugs.python.org/issue34725)

Additionally, it looks like these issues have been 'resolved' due to the addition of [PEP 587](https://www.python.org/dev/peps/pep-0587/) which introduced a way to configure the initialization of python including path related information. However, P4D would need to be extended to take advantage of this behavior.

Not sure if you have any other ideas, or think adding the configurable initialization is doable? The loss of multiprocessing in P4D is quite unfortunate. Does Pyscripter get around this issue by use of rpyc?

**Comment by pyscripter** [comment]
> Additionally, it looks like these issues have been 'resolved' due to the addition of [PEP 587](https://www.python.org/dev/peps/pep-0587/) which introduced a way to configure the initialization of python including path related information. However, P4D would need to be extended to take advantage of this behavior.

I would be happy to consider a PR that implements PEP 587 in P4D.


> Does Pyscripter get around this issue by use of rpyc?

Yes

**Comment by pyscripter** [comment]
One more thing to try: the published property VenvPythonExe.  This does set the sys.executable.  
Although it was designed for making venvs work it could also be used with standard python distributions.

**Comment by fjames003** [comment]
I printed the value of sys.executable, and its the path to the python being used, so sys.executable is correct. However sys.argv[0] is not.

**Comment by pyscripter** [comment]
sys.argv[0] should be '' .  See https://docs.python.org/3/c-api/init.html#c.PySys_SetArgvEx

**Comment by fjames003** [comment]
> Implemented in my latest commit

I'll have to catch up and see what difference, if any, that makes.
