### ISSUE TITLE
[dcc64 fatal error] Python.dpk(33): E2202 Required package 'DesignIDE' not found

### ISSUE THREAD

**Issue by khsee** [pyscripter/python4delphi#279]
Trying to rebuild all packages for Windows-64bit. Currently using Python 3.91 (64-bit) and Delphi 10.4.1. Building Windows-32bit was OK. Did I did something wrong?

**Comment by pyscripter** [comment]
You should not build design packages in 64bits.  The IDE is 32bit only.

**Comment by FMXExpress** [comment]
I was confused by this as well. A FAQ that answers questions like this could be a good idea because setting up Python4Delphi is harder than it should be.
