### ISSUE TITLE
Bug Regarding IO Redirection

### ISSUE THREAD

**Issue by fjames003** [pyscripter/python4delphi#281]
I know that after looking at Demo34, the intended idea was to Free and Create a new PythonEngine if the version of Python changes.
However, that is not strictly necessary, and if another object is managing the life cycle of PythonEngine, then Freeing and Creating a new TPythonEngine every time python changes is not ideal (and it would seem Finalize was made public to manage this lifecycle yourself).

Instead when the version of Python changes, I am calling 'Finalize' on the instance of TPythonEngine.
Subsequently, I am changing the DLL of the Engine (using TPythonVersion.AssignTo), and upon **initialization of the engine the second time**, I ran into two bugs:

1.  In TPythonEngine.Finalize, RedirectIO is set to False, but never restored to True. Which means that in order for TPythonEngine to function in the same way after calling Finalize, you need to set RedirectIO back to true after calling Finalize.
    * While this is an easy fix, I am just pointing out, because if you do not set RedirectIO back to True, you will not see bug (2).
 2. In TPythonEngine.DoRedirectIO, FIOPythonModule only has methods added to it if it was not Assigned previously, but not if it was Assigned but uninitialized. In the event that FIOPythonModule is Assigned, but not Initialized, then all of the 'pyio' methods will be missing and you will end up with a python error if you call 'print', with the error reporting a python attribute error that 'pyio' does not have a method 'write'. This is happening because TPythonEngine.Finalize is calling Finalize on all its clients (FIOPythonModule being one of them), and Finalize on TPythonModule will clear all the methods. So at the very least, DoRedirectIO should at least check MethodCount of FIOPythonModule before calling Initialize and Add the methods if the count is incorrect.

I replicated this bug in Demo34 as well. All you need to do to replicate is comment out: https://github.com/pyscripter/python4delphi/blob/52275067552d954d703efdd619692c091b1498a1/Demos/Demo34/Unit1.pas#L87
And then change: https://github.com/pyscripter/python4delphi/blob/52275067552d954d703efdd619692c091b1498a1/Demos/Demo34/Unit1.pas#L92
to:
`if not Assigned(PythonEngine1) then` 
` PythonEngine1 := TPythonEngine.Create(Self);` 
`else`
`begin`
`  PythonEngine1.Finalize;`
`  PythonEngine1.RedirectIO := True;`
`end;`

Of course you need more than one python registered to use Demo34 as is for this example.

**Comment by pyscripter** [comment]
Firstly,  unloading and reloading pythonxy dlls is in general not recommended and should be avoided.  There are many ways in which this may fail.  You also need to manually unload any dlls that python itself is loading (see how this is done in PyScripter).

Demo 34 demonstrates though, that it is possible and the way it was designed to work was to destroy and recreate the Python Engine.  I am not planning to offer support for doing that without destroying the Python Engine first.

> if another object is managing the life cycle of PythonEngine, then Freeing and Creating a new TPythonEngine every time python changes is not idea

In that case this other object should be made responsible for destroying and recreating the PythonEngine.

**Comment by fjames003** [comment]
Then why not make Finalize protected or private on the engine.

This is not obvious to a user at all.

I had to debug why all of a sudden I could not print, but everything else worked fine.

At the very least you should be restoring RedirectIO so that problem is more obvious. You are just asking for more situations like this by choosing not to fix anything.

**Comment by pyscripter** [comment]
> Then why not make Finalize protected or private on the engine.
That is not a bad idea.

> At the very least you should be restoring RedirectIO
I am not sure what you are actually suggesting

**Comment by fjames003** [comment]
> I am not sure what you are actually suggesting
I am suggesting that in TPythonEngine.Finalize, you store the current value of RedirectIO, and then at the end of them method restore RedirectIO so that if it was true before Finalize, its still true after Finalize.

Then when someone initializes the engine for a second time, they will get the pyio attribute error much quicker allowing them to realize what is wrong. By not restoring RedirectIO, all IO problems are hidden to the user.

But if Finalize is not public, this is less of an issue.

**Comment by pyscripter** [comment]
I have made TPythonEngine.Initialize and TPythonEngine.Finalize protected to avoid confusion regarding their use.
