### ISSUE TITLE
win10(64bit)+python3.85(64bit)+delphi xe10.4.1 error

### ISSUE THREAD

**Issue by guistory** [pyscripter/python4delphi#284]
i installed python4delphi follow the installtion
but when i run the demo3 with 64bit found 
`[dcc64 Fatal Error] Demo03.dpr(7): F2048 Bad unit format: 'Unit1.dcu' - Expected version: 34.0, Windows Unicode(x64) Found version: 34.0, Windows Unicode(x86) `
then i run this demo with 32bit can show the demo's form,but click 'excute script' button show
 `python is not porperly initialized`

Tpythonengines' choice like this:
```
AutoLoad = False
DLLname = python38.dll (and already copy the python38.dll from my python's home dictionary to demo's dir )
RegVision = 3.8
UseLastKnowVersion = False
```
my english is poor,please help me.
Thank you for your help.

**Comment by pyscripter** [comment]
> [dcc64 Fatal Error] Demo03.dpr(7): F2048 Bad unit format: 'Unit1.dcu' - Expected version: 34.0, Windows Unicode(x64) Found version: 34.0, Windows Unicode(x86)

Use the project Build command.
