### ISSUE TITLE
class exception 'External: SIGSEGV'.   in file 'PythonEngine.pas' row 4046: AFlag^ := 0;

### ISSUE THREAD

**Issue by esperti** [pyscripter/python4delphi#285]
with Lazarus v2.0.10 running on Ubuntu 20.10

procedure TForm1.Button1Click(Sender: TObject);
begin
  PythonEngine1.Initialize; //<-------------------------AFlag^ class exception
  PythonEngine1.ExecStrings( Memo1.lines );
end;      

on click: class excetion 'External: SIGSEGV'.   in file 'PythonEngine.pas' row 4046: AFlag^ := 0;

python --version --> Python 2.7.18

**Comment by pyscripter** [comment]
I am closing this since you are using the Lazarus fork.  I will monitor https://github.com/Alexey-T/Python-for-Lazarus/issues/30
