### ISSUE TITLE
Inconsistencies in project files

### ISSUE THREAD

**Issue by jr2804** [pyscripter/python4delphi#288]
1) The project files for Python.dproj, PythonVcl.dproj and PythonFmx.dproj do not contain all source files and rely on Delphi to find them in the directory next to them and should be included. Due to this, the non-included files are compiled next to their source path (in the folder _Source_), which is really bad style. It is common practice to have all .dcu files located at one single output directory (without .pas files), which can be added as a library project. The following structures are suggested:

![image](https://user-images.githubusercontent.com/11995439/109288706-84ad3900-7825-11eb-94d1-3c29f81b6118.png)![image](https://user-images.githubusercontent.com/11995439/109288729-8d057400-7825-11eb-9896-e2bb8fc9499f.png)![image](https://user-images.githubusercontent.com/11995439/109288772-9bec2680-7825-11eb-8ede-64d8072bfcf9.png)

Note 1: Please also have a look at the revised required packages (e.g., Vcl is not required for Python.bpl).
Note 2: I checked this issue only for Delphi 10.4 project files, don't know if it's valid also for other projects.

2) In consequence, the setting "Unit output directory" should be set to " .\$(Platform)\$(Config)" as default for all projects.

3) All units _Source\fmx\WrapFmx*.pas_ try in include `{$I Definition.Inc}`, but it should be `{$I ..\Definition.Inc}` (as in _Source\vcl\Vcl.Python*.pas_).

**Comment by pyscripter** [comment]
Could you please submit a PR for this issue?

**Comment by jr2804** [comment]
Done, see #290
