### ISSUE TITLE
Possibility of a "not released" Critical Section while terminating the application

### ISSUE THREAD

**Issue by alperyazgan** [pyscripter/python4delphi#291]
In a simple application using TPythonEngine, TPythonGUIInputOutput and a TPythonModule;
Where the TPythonEngine has the the following settings;
```
  PythonEngine.Name := 'PythonEngine';
  PythonEngine.DllName := 'python38.dll';
  PythonEngine.APIVersion := 1013;
  PythonEngine.RegVersion := '3.8';
  PythonEngine.UseLastKnownVersion := False;
  PythonEngine.InitThreads := True;
  PythonEngine.IO := PythonGUIInputOutput;
  PythonEngine.RedirectIO := True;
  PythonEngine.PyFlags := [pfDebug, pfVerbose];
```

On application termination, it gets an exception "access violation, write of address 0x00000014" which actually caused in 
the line 
```
 procedure TCriticalSection.Acquire;
begin
  FSection.Enter;
end;  <------- (Here)
```
in the module _System.SyncObjs_.

I think it is related with the options (RedirectIO, PyFlags.pfVerbose and InitThreads) triplet, while the Verbose is set to False everything goes smoothly on termination, maybe a rogue critical section causes this when this flag is on. 

Any comment will be appreciated. 
Thanks,

PS: _Using Embarcadero® C++Builder 10.3.3 Version 26.0.36039.7899_

**Comment by pyscripter** [comment]
Could you please provide a minimal project reproducing the error?

**Comment by alperyazgan** [comment]
You are fast; while I was trying to encapsulate the problem in a minimal project reproducing, you have already found and fixed/patched it. 

Thanks,

**Comment by alperyazgan** [comment]
Tested with no problems related with the issue.
