### ISSUE TITLE
exit() called from executed python code terminates the process

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/python4delphi#292]
As per title.  See also https://en.delphipraxis.net/topic/4537-exit-terminates-delphi-app/

__builtins__.exit() and sys.exit() raise the SystemExit python exception.  PyErr_Print executed in TPythonEngine.CheckError after a SystemExit exception, results in immediate process termination, without giving Delphi a chance to handle this exception or have an orderly shutdown.  Not nice.

**Comment by pyscripter** [comment]
Now SystemExit results in a EPySystemExit exception which can be handled in Delphi code.

**Comment by alperyazgan** [comment]
It was in my "ask list" :-)
