### ISSUE TITLE
Need to use TPythonVersion, TPythonVersions, and the utility functions defined in "PythonVersions.pas" in CppBuilder Project

### ISSUE THREAD

**Issue by alperyazgan** [pyscripter/python4delphi#295]
Hi,

Although these are well thought and designed to be useful as utility classes and functions and could be used in Delphi projects, yet they are not accessible (at least in a clean way) in a CppBuilder project, because they are not compiled or accessed within the normal component library of  Python_D  so there in no header files generated or object reference in the linked library.

Any comment will be appreciated, 

Thanks,

**Comment by pyscripter** [comment]
Would just adding PythonVersions to the Python package and reinstalling resolve the issue?

**Comment by alperyazgan** [comment]
Yes I was thinking the same thing, it should resolve the problem, thanks.

I am using the attached Package Building Batch with just calling dcc with of course all needed configuration setup necessary for hpp generation settings and I just changed the the file "Python_D.dpk" with addition of the line;

```
contains
  MethodCallBack in '..\..\..\Source\MethodCallBack.pas',
  PythonEngine in '..\..\..\Source\PythonEngine.pas',
  WrapDelphi in '..\..\..\Source\WrapDelphi.pas',
  PythonReg in '..\..\..\Source\PythonReg.pas',
  PythonVersions in '..\..\..\Source\PythonVersions.pas',     <---- Added 
  Vcl.PythonGUIInputOutput in '..\..\..\Source\vcl\Vcl.PythonGUIInputOutput.pas',
  Vcl.PythonReg in '..\..\..\Source\vcl\Vcl.PythonReg.pas';
```

[CompilePython4DelphiPackage4Win32.bat.txt](https://github.com/pyscripter/python4delphi/files/6075962/CompilePython4DelphiPackage4Win32.bat.txt)
