### ISSUE TITLE
FPC Package Issue

### ISSUE THREAD

**Issue by nextjob** [pyscripter/python4delphi#297]
WrapDelphiControls.pas and WrapDelphiButtons.pas are referenced in p4dlaz.lpk and p4dlaz.pas, but have been removed from /source (and into /vcl/ WrapVclControls.pas  /vcl/WrapVclButtons.pas).  What is the correct action, remove the reference from the package files  or point to the new locations?

**Comment by pyscripter** [comment]
I have removed them.  They did not register any controls anyway.  Could you please check the Lazarus packages work?

**Comment by pyscripter** [comment]
It will be fixed this in the next few days.  There is PR pending.

**Comment by pyscripter** [comment]
This has now been fixed.
