### ISSUE TITLE
AttributeError: 'PythonDelphiVar' object has no attribute 'Value'

### ISSUE THREAD

**Issue by Dak81** [pyscripter/python4delphi#300]
just installed and testing demo projects. 
All demo projects raise this error when the script try to evaluate "test.Value"

**Comment by pyscripter** [comment]
Could you please list the demos you are having this issue with?

**Comment by Dak81** [comment]
Demo03 
Demo04
Demo06
Demo07
Demo08	
Demo16a
Demo31 access violation on loading

**Comment by pyscripter** [comment]
I have tried Demo03 and Demo04 without any issues.  Are you sure you are using the latest version from Github?

**Comment by Dak81** [comment]
I have download zip from https://github.com/pyscripter/python4delphi yesterday at 9:05 AM Italian time.
I'm using delphi 10.4.1.

I'm download it again

**Comment by Dak81** [comment]
same result

Python Dll:  3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Copyright (c) 2001-2020 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'PythonDelphiVar' object has no attribute 'Value'

If you want we can do a remote session

**Comment by pyscripter** [comment]
Well here this is the output I get from Demo03 and Delphi 10.4.2 (same Python version as yours 3.9.1 64bits):

```
Python Dll:  3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Copyright (c) 2001-2020 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.

<PythonDelphiVar: 10> 10
<PythonDelphiVar: [1, 2, 3]>
```

Which version of Delphi are you using?

**Comment by Dak81** [comment]
I'm using delphi 10.4.1.

**Comment by pyscripter** [comment]
That shouldn't make a difference.  Any chance your Delphi is linking in older versions of P4D (check the Library path)?

**Comment by pyscripter** [comment]
Please try the following:
- Open the project Demo03 in Delphi
- Set breakpoints in Lines 7449 in TTypeServices.Create (FBasic := [bsGetAttrO, bsSetAttrO, bsRepr, bsStr]) and Line 8510 TPyVar.SetAttrO.
- Start debugging.
- Make sure the first breakpoint is hit.  Continue running.
- Press the button "Execute Script"
- Do hit the second breakpoint before the error, i.e. is TPyVar.SetAttrO?

**Comment by Dak81** [comment]
sorry, sorry, sorry i have checked the library path and only in win64 there was an old P4D version that i totally forget to have.
I owe you a beer.

Now all works except demo 08:
(2, 5)
Traceback (most recent call last):
  File "<string>", line 5, in <module>
AttributeError: 'Point' object has no attribute 'x'

**Comment by pyscripter** [comment]
Fixed in version control.  See: 64f1dd9ea1f9d7a96220a3e6894bc273d6b6e003
