### ISSUE TITLE
maybe you need that autodetection of macOS lib path

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#305]
It's here
https://github.com/Alexey-T/Python-for-Lazarus/commit/11b25a3f669ffeb01378aed5617c97841fb250ad

**Comment by pyscripter** [comment]
@Alexey-T Thanks.  Is it worth adding to PythonEngine.pas?

**Comment by Alexey-T** [comment]
if you have the option to auto-detect the DLL name, then yes.

**Comment by pyscripter** [comment]
Property UseLastKnownVersion.  
See TPythonEngine.DoOpenDll
We will need to enhance GetDLLPath (currently it only does something on Windows).  Could add the default DLLPath for the Mac.

**Comment by pyscripter** [comment]
@Alexey-T Please have a look and test if you can.
