### ISSUE TITLE
Missing functions build Python.Utils.pas into Pythonengine.pas

### ISSUE THREAD

**Issue by JeanYvesJonet** [pyscripter/python4delphi#308]
Hello,
I have errors when i build with delphi 10.4 32 bits
[dcc32 Erreur] Python.Utils.pas(862): E2003 Identificateur non déclaré : 'PyUnicode_FromWideString'
[dcc32 Erreur] Python.Utils.pas(867): E2003 Identificateur non déclaré : 'PyString_Check'
[dcc32 Erreur] Python.Utils.pas(889): E2003 Identificateur non déclaré : 'PyString_FromStringAndSize'
[dcc32 Erreur] Python.Utils.pas(894): E2003 Identificateur non déclaré : 'PyString_Check'
[dcc32 Erreur] Python.Utils.pas(1025): E2003 Identificateur non déclaré : 'PyInt_FromLong'
[dcc32 Erreur] Python.Utils.pas(1031): E2003 Identificateur non déclaré : 'PyInt_FromLong'
[dcc32 Erreur] Python.Utils.pas(1078): E2003 Identificateur non déclaré : 'PyNumber_Int'
[dcc32 Erreur] Python.Utils.pas(1087): E2003 Identificateur non déclaré : 'PyInt_Check'
[dcc32 Erreur] Python.Utils.pas(1097): E2003 Identificateur non déclaré : 'PyInt_AsLong'
[dcc32 Erreur fatale] untMain.pas(9): F2063 Impossible de compiler l'unité utilisée 'Python.Utils.pas'
Thanks

**Comment by pyscripter** [comment]
PythonEngine.pas dropped support for python 2.x.   Many methods have been removed and others replaced.  All the PyString_ and PyInt_ methods have been removed.  Use PyUnicode_ and PyLong_ instead.
