### ISSUE TITLE
FindingPython @ WINDOWS and @ LINUX 

### ISSUE THREAD

**Issue by ImageProcessingFMX** [pyscripter/python4delphi#310]
is page I found very useful https://github.com/pyscripter/python4delphi/wiki/FindingPython, 
bu I'm missing the LINUX, UBUNTU .....  version  :-)

**Comment by ImageProcessingFMX** [comment]
prework done : 

use a command **_which python_**, return path to python installation 
use command ldd  path_pathon_installaton should return valid path  to python lib

overall no success .-(

**Comment by pyscripter** [comment]
See https://en.delphipraxis.net/topic/4700-getregisteredpythonversions-for-linux/?tab=comments#comment-41005
There is not much that can be done.
If you find a general solution please submit a PR.
