### ISSUE TITLE
XE3 fail to load

### ISSUE THREAD

**Issue by michaelrempel** [pyscripter/python4delphi#311]
my xe3 install fails the build with the following
Checking project dependencies...
Building Python_D.dproj (Debug, Win32)
...
Can't load package Python_D150.bpl.
The system cannot find the file specified
[Fatal Error] Can't load package Python_D150.bpl.
The system cannot find the file specified

I removed the very long library call, but I know other libraries load just fine.  I moved the two folders high up un the list to make sure.

**Comment by pyscripter** [comment]
Just to make sure. The package builds OK but it does not install, with the message above "The system cannot find the file specified".  Is this the case?

**Comment by michaelrempel** [comment]
No, it does not build at all.

**Comment by pyscripter** [comment]
What are the error messages you get when you build the library?

**Comment by michaelrempel** [comment]
I gave you thhe error in the first message. I suspect that the bpl file is not compatiable with older compilers like mine but I dont know how to fix it. Making this work would be sweet if it can be done.

**Comment by pyscripter** [comment]
Python_D150.bpl is the name of the compiled package file that Delphi is looking to load. It is not part of the distribution. The package file Python_D.dpk contains a series of IFDEFs with LIBSUFFIX directives, For XE3 the following should apply
{$IFDEF VER240}{$LIBSUFFIX '170'} {$ENDIF}
and the generated package should be called Python_D170.bpl
Can you check C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl for Python_D*.bpl.

A workaround is to replace all the IFDEFS in the package file with {$LIBSUFFIX '170'} using an editor and then load and compile the package again.

**Comment by pyscripter** [comment]
See also #313.

I will not be creating separate packages for older Delphi versions. Please use the workaround above.

**Comment by yonojoy** [comment]
... same problem with XE4.

Solution is provided in [comment above](https://github.com/pyscripter/python4delphi/issues/311#issuecomment-882434585): define {$LIBSUFFIX '...'} without IFDEFs.

If interested, I can create a pull request from [my fix](https://github.com/yonojoy/python4delphi/commit/08a87e7561d9874e75aa0d2b1e69d83e322d288d).
