### ISSUE TITLE
xe2 bpl installation problem , need help

### ISSUE THREAD

**Issue by mitchellhu** [pyscripter/python4delphi#313]
Windows10
Delphi Xe2 update 4
libarary path is added
while installation Python_D150.bpl
IDE raise Error: [DCC Error] WrapDelphi.pas(2789): E2003 Undeclared identifier: 'TypeData'
and point to Error line: WarpDelphi.pas line 278:
if (RttiParam.ParamType = nil) or (RttiParam.ParamType.Handle = nil) or (RttiParam.ParamType.Handle.TypeData = nil) then
  Exit;

I check out the Unit Sytem.Typinfo found a Strange place:

PPTypeInfo = ^PTypeInfo;
  PTypeInfo = ^TTypeInfo;
  TTypeInfo = record
    Kind: TTypeKind;
    Name: ShortString;
   {TypeData: TTypeData}
  end;

the TypeData section is be marked with a curly bracket in Delphi Xe2 !!! 
I'm not sure if it makes trouble.

**Comment by pyscripter** [comment]
Does it help to replace

`RttiParam.ParamType.Handle.TypeData`

with

`GetTypeData(RttiParam.ParamType.Handle)`

**Comment by mitchellhu** [comment]
pyscripter ：
   1.compile pass with Replace with GetTypeData(RttiParam.ParamType.Handle) and GetTypeData(RttiParam.ParamType.Handle).eltype.
   2.But now IDE debugger shows : Can't load package Python_D150.bpl.
   I can't find Python_D150.bpl. in the python4delphi-master.zip files,!!!
   Where can I get the python4delphi-master?
   Thanks

**Comment by pyscripter** [comment]
Python_D150.bpl is the name of the compiled package file that Delphi is looking to load.   It is not part of the distribution.   The package file contains a series of IFDEFs with LIBSUFFIX directives,  For XE2 the following should apply
{$IFDEF VER230}{$LIBSUFFIX '160'} {$ENDIF}
and the generated package should be called Python_D160.bpl 
Can you check C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl for Python_D*.bpl.

A workaround is to replace all the IFDEFS in the package file with {$LIBSUFFIX '160'} using an editor and then load and compile the package again.

**Comment by mitchellhu** [comment]
Pyscripter:
I do not flow your instruction very clearly.
I found Python_D160.bpl in path  C:\Users\Public\Documents\RAD Studio\9.0\Bpl。this path is a little different from your point out one.
I open the Python_D.dpk with NotePad++ , then it shows as below:
package Python_D;

{$R '..\..\..\Source\PythonEngine.dcr'}
{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}
{$ALIGN 8}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS ON}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION OFF}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO ON}
{$SAFEDIVIDE OFF}
{$STACKFRAMES ON}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST OFF}
{$MINENUMSIZE 1}
{$IMAGEBASE $400000}
{$DEFINE DEBUG}
{$ENDIF IMPLICITBUILDING}
{$DESCRIPTION 'Components for Python'}
{$IMPLICITBUILD OFF}

{$IFDEF VER200}{$LIBSUFFIX '120'} {$ENDIF}
{$IFDEF VER210}{$LIBSUFFIX '140'} {$ENDIF}
{$IFDEF VER220}{$LIBSUFFIX '150'} {$ENDIF}
{$IFDEF VER230}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER240}{$LIBSUFFIX '170'} {$ENDIF}
{$IFDEF VER250}{$LIBSUFFIX '180'} {$ENDIF}
{$IFDEF VER260}{$LIBSUFFIX '190'} {$ENDIF}
{$IFDEF VER270}{$LIBSUFFIX '200'} {$ENDIF}
{$IFDEF VER280}{$LIBSUFFIX '210'} {$ENDIF}
{$IFDEF VER200}{$LIBSUFFIX '220'} {$ENDIF}
{$IFDEF VER300}{$LIBSUFFIX '230'} {$ENDIF}
{$IFDEF VER310}{$LIBSUFFIX '240'} {$ENDIF}
{$IFDEF VER320}{$LIBSUFFIX '250'} {$ENDIF}
{$IFDEF VER330}{$LIBSUFFIX '260'} {$ENDIF}
{$IFDEF VER340}{$LIBSUFFIX '270'} {$ENDIF}

requires
  {$IFDEF WIN32}
  DesignIDE,
  {$ENDIF}
  rtl,
  vcl;

contains
  MethodCallBack in '..\..\..\Source\MethodCallBack.pas',
  PythonEngine in '..\..\..\Source\PythonEngine.pas',
  WrapDelphi in '..\..\..\Source\WrapDelphi.pas',
  PythonReg in '..\..\..\Source\PythonReg.pas',
  Vcl.PythonGUIInputOutput in '..\..\..\Source\vcl\Vcl.PythonGUIInputOutput.pas',
  Vcl.PythonReg in '..\..\..\Source\vcl\Vcl.PythonReg.pas';

end.

Should I replace all $LIBSUFFIX '120' with $LIBSUFFIX '160'  then save it.
and load Python_D.dpk and compile it?
Sorry for my bad English ability.
Thanks

**Comment by pyscripter** [comment]
> Should I replace all $LIBSUFFIX '120' with $LIBSUFFIX '160' then save it.
> and load Python_D.dpk and compile it?

Yes that is what I was suggesting.  It appears that the package is compiled to Python_D160.bpl but then Delphi tries to load Python_D150.bpl.  Don't know why.

**Comment by mitchellhu** [comment]
pyscripter:
Even modify Python_D.dpk  as below still does not work.
{$IFDEF VER090}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER170}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER160}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER200}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER210}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER220}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER230}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER240}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER250}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER260}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER270}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER280}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER200}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER300}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER310}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER320}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER330}{$LIBSUFFIX '160'} {$ENDIF}
{$IFDEF VER340}{$LIBSUFFIX '160'} {$ENDIF}

While you load it, you will seed the Python_D150.bpl in the project manager.
I think the old versions may not be proved they can work fine!!!

**Comment by pyscripter** [comment]
Please replace all {$IFDEF VERxyz} with just one line

`{$LIBSUFFIX '160'}`

**Comment by mitchellhu** [comment]
pyscripter:
still does not work, the bpl name does  not change to Python_D160.bpl .
Why LibSuffix '160' does not work !!!!   
change as below:
package Python_D;

{$R '..\..\..\Source\PythonEngine.dcr'}
{$IFDEF IMPLICITBUILDING This IFDEF should not be used by users}
{$ALIGN 8}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS ON}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION OFF}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO ON}
{$SAFEDIVIDE OFF}
{$STACKFRAMES ON}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST OFF}
{$MINENUMSIZE 1}
{$IMAGEBASE $400000}
{$DEFINE DEBUG}
{$ENDIF IMPLICITBUILDING}
{$DESCRIPTION 'Components for Python'}
{$IMPLICITBUILD OFF}
{$LIBSUFFIX '160'} <=====  is it right ?
requires
  {$IFDEF WIN32}
  DesignIDE,
  {$ENDIF}
  rtl,
  vcl;

contains
  MethodCallBack in '..\..\..\Source\MethodCallBack.pas',
  PythonEngine in '..\..\..\Source\PythonEngine.pas',
  WrapDelphi in '..\..\..\Source\WrapDelphi.pas',
  PythonReg in '..\..\..\Source\PythonReg.pas',
  Vcl.PythonGUIInputOutput in '..\..\..\Source\vcl\Vcl.PythonGUIInputOutput.pas',
  Vcl.PythonReg in '..\..\..\Source\vcl\Vcl.PythonReg.pas';

end.

**Comment by pyscripter** [comment]
Libsuffix if probably set wrongly in the project file.  You can either
-  Change libsuffix in the project file or
-  Delete all files in the package folder except Python_D.dpk and open the above file in Delphi.

**Comment by mitchellhu** [comment]
pyscripter :
1. About the fisrt suggestion, I can not find any option with libsuffix.
2. Second suggestion works, it is  Python_D160.bpl now, and can be installed.
3. Test Demo1, but IDE shows [DCC Fatal Error] Unit1.pas(11): F1026 File not found: 'PythonEngine.dcu',
    How come?  already set the lib_path D:\Components\P4D\Source and D:\Components\P4D\Source\vcl,

**Comment by pyscripter** [comment]
> 3\. already set the lib_path D:\Components\P4D\Source and D:\Components\P4D\Source\vcl,
>     This is a very strange problem to me.

Have you set it for all targets (32 bits, 64bits)?

**Comment by mitchellhu** [comment]
Pyscripter:
I set the libPath both 32 bits and 64bis. See. Pics as below.
source path:
![PY4DsourcePath](https://user-images.githubusercontent.com/3622274/126480120-084891cd-0528-4f0e-926d-13b315161cad.PNG)
32bits libpath:
![32bitlibPath](https://user-images.githubusercontent.com/3622274/126480159-5625c116-53ce-4c7a-bcc1-2643e8cc75bb.PNG)
64bits:libpath
![64bitlibPaty](https://user-images.githubusercontent.com/3622274/126480185-011c8470-770c-4af0-8ee5-005057fbe4a7.PNG)

**Comment by pyscripter** [comment]
Check Project, Options, Compiler, Unit Output directory.
Can you locate PythonEngine.dcu in the P4D subfolders?

**Comment by mitchellhu** [comment]
pyscripter:
1. I add unit Output directory and compile the project, then got an Error again, 
[DCC Fatal Error] Unit1.pas(11): F2048 Bad unit format: 'D:\Components\P4D\Source\PythonEngine.dcu' - Expected version: 23.0, Windows Unicode(x64) Found version: 23.0, Windows Unicode(x86) : see the picture as below
![unitoutput](https://user-images.githubusercontent.com/3622274/126593959-baf7769e-2cc6-491f-94b0-861ac8dde02c.PNG)
2. According to the Error. I switch the Target platform from 64bit to 32bit. then IDE seems to find those Pythonxxx.dcu files.
   but raise a new Error: Error 87: Could not open Dll "python33.dll", close the Error message,
   IDE raise another Error:  python could not be properly initialized, We must quit;
   
![notopen_python33dll](https://user-images.githubusercontent.com/3622274/126594427-7d784e23-2bfe-45ba-83e4-9fa75fc6d912.PNG)

**Comment by pyscripter** [comment]
> 1. I add unit Output directory and compile the project, then got an Error again,
>    [DCC Fatal Error] Unit1.pas(11): F2048 Bad unit format: 'D:\Components\P4D\Source\PythonEngine.dcu' - Expected version: 23.0, Windows Unicode(x64) Found version: 23.0, Windows Unicode(x86) : see the picture as below

You need to build the project to avoid this error.

**Comment by mitchellhu** [comment]
pyscripter:
  I do build the project with 64bit platform and seems fine with no error message again.
  but run the project, the IDE raise Error: disconnected session: 
  the error and details as below;
 ![py4dlphix2compleError](https://user-images.githubusercontent.com/3622274/126730619-d824304b-7966-4120-87ca-5aaeac6a2b01.PNG)
 google this error found: https://codeverge.com/embarcadero.delphi.ide/disconnected-session-in-xe2-64-bit/1061220
 it says debugger problem for 64bit project cause the Error raises. Then run it with no debugger will be fine. 
 I think I should upgrade xe2 to a higher version.
 Anyway, Thank you very very much, you teach me a lot of things.

**Comment by pyscripter** [comment]
Implemented the change with GetTypeData.  The code should now be XE2 compatible.

**Comment by mitchellhu** [comment]
You mean even implemented with GetTypeData in Python_D.dpk (version Xe3) then it still can not load？
I repot WarpDelphi.pas has TypeData Error due to the  Unit Sytem.Typinfo (Verion Xe2) cross out {TypeData: TTypeData}.
I changed the WarpDelphi.pas  Error part with casting  GetTypeData(xxxxx) then it can get .eltype correctly.

**Comment by Uefi1** [comment]
Одним словом ХУЕТА  а не компонент не ставьте !
