### ISSUE TITLE
Creating Python DLL for Linux with Lazarus

### ISSUE THREAD

**Issue by prabhatM** [pyscripter/python4delphi#316]
Hi,

I want to create a few python DLL for my python (3.8 ) application on Linux. Is it possible to do with Lazarus plus Python4Delphi?

Regards

Prabhat

**Comment by pyscripter** [comment]
Please watch https://github.com/pyscripter/python4delphi/tree/master/Tutorials/Webinar%20I to see how you can create extension modules using Delphi.  You would need to adapt it to fpc.
