### ISSUE TITLE
Does python3delphi support egg files

### ISSUE THREAD

**Issue by bubblegumsoldier** [pyscripter/python4delphi#323]
Hello,

we are currently working with `python3delphi` and are working with single python files that we are using. As code naturally grows we wanted to switch to [egg-files](https://python101.pythonlibrary.org/chapter38_eggs.html) and interact with these rather than pure python files. Does `python4delphi` support egg files?

Thank you very much in advance.

**Comment by pyscripter** [comment]
Egg files are an old distribution format for python packages (superseded by by wheels).  You need to install them before they become usable,   Once you install packages (egg files or other formats) they are usable by Python4Delphi.
