### ISSUE TITLE
Error 127: could not map symbol "PyRun_String"

### ISSUE THREAD

**Issue by lucasbelkys** [pyscripter/python4delphi#325]
I checked everything a programmer can check for dependency and I didn't find the problem. Would anyone know?
![erroP4D](https://user-images.githubusercontent.com/54689861/133175644-bad79444-2ab0-4925-aa5b-1269058d9797.png)

Delphi 10.4

**Comment by pyscripter** [comment]
Strange.  Which version of Python are you using?  On which platform?

**Comment by lucasbelkys** [comment]
Resolved: Thanks!

**Comment by pyscripter** [comment]
What was the problem and how did you resolve it?
