### ISSUE TITLE
Error 87: Could not open Dll "python33.dll"

### ISSUE THREAD

**Issue by wg0517** [pyscripter/python4delphi#330]
I installed 32-bit Python 3.10 in Win10 (64-bit), and compiled the demo with Error 87: Could not open Dll "python33.dll", after a single step, I found that there was a problem with the MinorVersion obtained in the IsPythonVersionRegistered function. MinorVersion := StrToInt(PythonVersion[3]); to MinorVersion := StrToInt(Copy(PythonVersion, 3)); then we can get Python310.dll normally.

**Comment by pyscripter** [comment]
Please change line 9077 to:

MinorVersion := StrToInt(Copy(PythonVersion, 3));

Does this fix the issue?

**Comment by noseparaquesirve** [comment]
Hi, 
I got the same problem. Could you please explain how to find the line 9077?

**Comment by pyscripter** [comment]
This has been already fixed.  No need to find a line or change anything.   

Reading and applying https://github.com/pyscripter/python4delphi/wiki/FindingPython usually resolves such problems.
