### ISSUE TITLE
header-comments in various files are chaotic and different, make them using single format

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#337]

**Comment by pyscripter** [comment]
I am suggesting the following header for all project files:
```
(**************************************************************************)
(*  This unit is part of the Python for Delphi (P4D) library              *)
(*  Project home: https://github.com/pyscripter/python4delphi             *)
(*                                                                        *)
(*  Project Maintainer:  PyScripter (pyscripter@gmail.com)                *)
(*  Original Authors:    Dr. Dietmar Budelsky (dbudelsky@web.de)          *)
(*                       Morgan Martinet (https://github.com/mmm-experts) *)
(*  Core developer:      Lucas Belo (lucas.belo@live.com)                 *)
(*  Contributors:        See contributors.md at project home              *)
(*                                                                        *)
(*  LICENCE and Copyright: MIT (see project home)                         *)
(**************************************************************************)
```

Also creating contributors.txt with the following content:

## Contributors

### Fpc and Lazarus support:                                       
- Alexey-T (https://github.com/Alexey-T)                        
### Early Contributors:                                             
-  Grzegorz Makarewicz (mak@mikroplan.com.pl)                  
-  Andrew Robinson (andy@hps1.demon.co.uk)                     
-  Mark Watts(mark_watts@hotmail.com)                          
-  Olivier Deckmyn (olivier.deckmyn@mail.dotcom.fr)            
-  Sigve Tjora (public@tjora.no)                               
-  Mark Derricutt (mark@talios.com)                            
-  Igor E. Poteryaev (jah@mail.ru)                             
-  Yuri Filimonov (fil65@mail.ru)                              
-  Stefan Hoffmeister (Stefan.Hoffmeister@Econos.de)           
-  Michiel du Toit (micdutoit@hsbfn.com) - Lazarus Port        
-  Chris Nicolai (nicolaitanes@gmail.com)                      
-  Andrey Gruzdev (andrey.gruzdev@gmail.com)                 

More recent contributors can be seen at the [project contributors graph](https://github.com/pyscripter/python4delphi/graphs/contributors).

**Comment by Alexey-T** [comment]
It is OK suggestion, agree.

**Comment by lmbelo** [comment]
@pyscripter sounds great, I too agree. Thanks!
