### ISSUE TITLE
Memory increases about 2 MB after executing a script each time. such as “python4delphi\Tutorials\Webinar II\VizDemo”

### ISSUE THREAD

**Issue by GitContainer** [pyscripter/python4delphi#341]
When I executed your demo（“python4delphi\Tutorials\Webinar II\VizDemo”）,I found that memory was increasing (about 2MB each time) when I clicked the run-button several times.  This is a problem when execute scripts periodically.   Is there a function to free the memory?

**Comment by pyscripter** [comment]
This is not a P4D issue.  There are no memory leaks when you exit the program.

You need to add the following at the end of the scripts.

```python
plt.clf()
plt.close()

```
and optionally
```
import gc
gc.collect()
```

See also https://stackoverflow.com/questions/64451628/memory-leak-using-seaborn-pyplot-savefig
https://stackoverflow.com/questions/28757348/how-to-clear-memory-completely-of-all-matplotlib-plots

**Comment by GitContainer** [comment]
Hi， Pyscripter.   Thanks for your reply. But it doesn't work .
The Capture1~Capture4  shown the application memory changed   when I clicked one\two\ three "run button"  with closing the demo application.
![Capture1](https://user-images.githubusercontent.com/32828619/141735994-8b1f816c-fddf-49ca-a4db-65fab6a851b9.PNG)
![Capture2](https://user-images.githubusercontent.com/32828619/141736010-f10b4871-8e0b-4222-b757-b1828fdb1e4a.PNG)
![Capture3](https://user-images.githubusercontent.com/32828619/141736030-4afcf376-df50-4cf7-a5ba-c0767d05c13a.PNG)
![Capture4](https://user-images.githubusercontent.com/32828619/141736046-5e6d7cb9-1112-47be-b11c-db62d7302bac.PNG)

**Comment by pyscripter** [comment]
The way python (and matplotlib) cleans up memory is kind of complex.  I was using the seaborn demo and memory was going up and after 6-7 repeats it would suddenly go down again.

In any case, there is no leak on the Delphi side.   The issue exists in pure python as you see in the provided links If you want more info please ask in the python forums.

**Comment by GitContainer** [comment]
yes，There is no python4delphi memory leak .

**Comment by pyscripter** [comment]
I tried again with the matplotlib demo.   After rerunning 10-15 times memory stabilizes at just above 100 Mb.  It goes up but then goes down again.

I just added

plt.clf()
plt.close()

at the end.
