### ISSUE TITLE
How Can I run multi Python code at a same time

### ISSUE THREAD

**Issue by beginner1393** [pyscripter/python4delphi#343]
Hello, 
I want to run multi simple Python code in Delphi at a same time, How can I do it ?
I have IdHttpServer and I want to run Python code per http requests and get result from Python code.

Thanks

**Comment by pyscripter** [comment]
Please address such questions at the support forum: https://en.delphipraxis.net/?forumId=39
Look at the answers to similar questions before asking your question.  You may find the answers you want.
e.g.

https://en.delphipraxis.net/topic/5287-running-python-scripts-in-threads/

**Comment by beginner1393** [comment]
Thanks
