### ISSUE TITLE
Error 126: Could not open Dll 'python32.dll'

### ISSUE THREAD

**Issue by informaresolutions** [pyscripter/python4delphi#344]
I just installed Python 32-bits (3.10 ver) on my computer and my application on Delphi (10.3 ver) is set to Win32 Platform. 
When I drop the PythonEngine on my form with default settings, this error occurs. I did the "_specific registered version_" and "_specific unregistered version_" tryout from the [FindingPython page](https://github.com/pyscripter/python4delphi/wiki/FindingPython) but still same issue.

Specifications of Python install:
Directory: C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32
DLLs on this dir: python3.dll, python310.dll and vcruntime140.dll

Registry keys on HKCU\Software\Python\PythonCore\3.10-32\InstallPath
Default = C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32\
ExecutablePath = C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32\python.exe
WindowedExecutablePath = C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32\pythonw.exe

Note that on the install dir, there's not python32.dll as the PythonEngine tries to load. 
Tried settings for "_specific registered version_":
DllName: python310.dll and python3.dll
RegVersion: 3 and 3.10
UseLastKnownVersion: False

Tried settings for "_specific unregistered version_":
Autoload: False
DllName: python310.dll = Error 127: could not map symbol "Py_DivisionWarningFlag"
DllName: python3.dll = '.' is not a valid integer value
RegVersion 3 and 3.10 same errors
DllPath = C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32

OnBeforeLoad
PythonEngine1.SetPythonHome('C:\Users\userAdmin\AppData\Local\Programs\Python\Python310-32')

Hope this helps to get it fixed. Thank you guys.

**Comment by pyscripter** [comment]
> DllName: python310.dll = Error 127: could not map symbol "Py_DivisionWarningFlag"

You are probably using an old version of P4D.  Please download or clone the current version from this repo.

Py_DivisionWarningFlag has been removed.
