### ISSUE TITLE
P4D for Delphi7 

### ISSUE THREAD

**Issue by Sambouss** [pyscripter/python4delphi#346]
Can i use python4delphi in delphi7

**Comment by pyscripter** [comment]
I am afraid not.

**Comment by Alexey-T** [comment]
In the SynWrite project (Delphi7) I did use it.

**Comment by pyscripter** [comment]
> In the SynWrite project (Delphi7) I did use it.

The current version requires a unicode version of Delphi (string = UnicodeString).   Look at the releases for the pre-Unicode version, but that could not be used with recent versions of Python.

**Comment by Sambouss** [comment]
> > Dans le projet SynWrite (Delphi7), je l'ai utilisé.
> 
> La version actuelle nécessite une version unicode de Delphi (prise en charge de UnicodeString). Regardez les versions de la version pré-Unicode, mais cela n'a pas pu être utilisé avec les versions récentes de Python.

I'll try it

**Comment by Sambouss** [comment]
> > In the SynWrite project (Delphi7) I did use it.
> 
> The current version requires a unicode version of Delphi (support for UnicodeString). Look at the releases for the pre-Unicode version, but that could not be used with recent versions of Python.

I'll try it
