### ISSUE TITLE
to support Delphi 7

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#347]
>The current version requires a unicode version of Delphi (support for UnicodeString). 

let's add definition of UnicodeString for D7 version, like:
```
{$IFNDEF DELPHI2010_OR_HIGHER}
type
  UnicodeString = WideString;
{$endif}
```

**Comment by pyscripter** [comment]
I am not sure it is just as simple to provide backward compatibility.  Supporting older versions takes time and effort.  Plus every time you use a new feature of the language (generics etc.) you have to IFDEF the code.

I am not inclined to do that.  Non-commercial users can use the Community edition of Delphi or just switch to Fpc like you did.  I can't imagine many commercial users using versions of Delphi more than 15 years old.
