### ISSUE TITLE
(Help!) Error in Installing dclPythonVcl280.bpl, etc on Delphi 11

### ISSUE THREAD

**Issue by MuhammadAzizulHakim** [pyscripter/python4delphi#349]
(Help!) Error in Installing dclPythonVcl280.bpl, etc on Delphi 11

I can successfully compile, build, and install Python280.bpl and dclPython280.bpl on RAD Studio Delphi 11.

But, when I am doing the same thing to PythonVcl280.bpl, dclPythonVcl280.bpl, PythonFmx280.bpl, and dclPythonFmx280.bpl, these errors are occured:
[dcc64 Error] WrapVclThemes.pas(145): E2003 Undeclared identifier: 'DEFAULT_CALLBACK_TYPE'
[dcc64 Fatal Error] WrapDelphiVCL.pas(30): F2063 Could not compile used unit 'WrapVclThemes.pas'

*Note: I already put the Sources subdirectories (\Python4Delphi\Source, \Python4Delphi\Source\vcl, Python4Delphi\Source\lcl, and \Python4Delphi\Source\fmx) into the Library paths, but it still doesn't work. 

Thank you!

**Comment by pyscripter** [comment]
This should now be fixed.  Please check.

**Comment by MuhammadAzizulHakim** [comment]
It works perfectly now! Thank you very much @pyscripter!
