### ISSUE TITLE
working with COM(Excel) in DLL written with Delphi for python

### ISSUE THREAD

**Issue by heilong0** [pyscripter/python4delphi#35]
I wrote simple function which returns list of opened Excel workbooks names on the basis of the demodll example:

``` delphi
function getOpenedWorkbooks(Self, Args : PPyObject) : PPyObject; cdecl;
var
  i: integer;
begin

with GetPythonEngine do
begin
  try
      Excel := GetActiveOleObject('Excel.Application');
      Result := PyList_New(Excel.workbooks.count);
      for i := 1 to Excel.workbooks.count do
      begin
        PyList_SetItem(Result, i-1, VariantAsPyObject(Excel.workbooks[i].Name));
      end;

  except
    on E:Exception do
    begin
       PyErr_SetString(PyExc_IndexError^, PAnsiChar(E.Message));
       Result := nil;
    end;
  end;

end;
end;
```

in python script I call it successfully and got valid results:

``` python
import xlslib
print(xlslib.getOpenedWorkbooks())
print(xlslib.add(10,15))
```

But after that process python.exe is not responding(console window didn't disappear). If I call only function Add(imported from demodll), everything works good. I used python 3.5.

Up:
I set Excel := 0 in finalization block of module and here program hanged up. Interesting thing, if I set Excel := 0 in particular function everything works good.

**Comment by pyscripter** [comment]
VariantAsPyObject does not support COM variants.  However you can use the xlslib if you want.

```
Var 
  xlslib : Variant;
begin
  xlslib := Import('xsllib');
  xlslib.add(10,15);
```

etc.
