### ISSUE TITLE
Delphi 11 Professional IDE Freezing

### ISSUE THREAD

**Issue by OmerGozlek** [pyscripter/python4delphi#352]
I am using Delphi 11 Professional Edition. All of patches of Delphi 11 are installed. After, opening component suite to install packages,  every time when I right click on a project in the project manager to build or to install package, Delphi IDE is frozen. I have to kill Delphi process from Task Manager. But I am able to build all projects using Project menu. I  installed components using Install Component menu item and adding design time packages. However, unfortunately, when I open a demo project, during opening pas file Delphi IDE freezes again. When IDE freezes, bds.exe at the task manager is shown as not responding and  there is no CPU usage and no memory usage change for  it.

**Comment by pyscripter** [comment]
Cannot reproduce here with 11.1.   I can right click on packages and build them without any issues.

**Comment by OmerGozlek** [comment]
I installed 11.1 and problem continues. I am able to build and install other components.
