### ISSUE TITLE
Does the selenium plugin for python?

### ISSUE THREAD

**Issue by sdzccs** [pyscripter/python4delphi#354]
Does the selenium plugin for python?The code for the selenium plugin does not run

**Comment by halilhanbadem** [comment]
I tried the following method for this. When the application started, I successfully ran my script with the command `pip install selenium` in the command system. It will be enough to do this only on installation.

![Adsız](https://user-images.githubusercontent.com/17130294/163828893-801f2e8d-3766-4295-899b-74a5a4ba2c30.png)
