### ISSUE TITLE
how to distribute python library with your app?

### ISSUE THREAD

**Issue by raelb** [pyscripter/python4delphi#355]
Hi,
If I install a python library such as bs4 on my pc, I can easily use it in a p4d app. But what if I want to distribute my app to another pc which doesn't have this library (or even python) installed. I can include an embedded python dll, but what about additional libraries such as bs or pandas? Can this be achieved? Is there a demo or tutorial explaining how to achieve this?
Thanks

**Comment by Alexey-T** [comment]
Put the lib into the relative folder of your app. Ie in the subfolder "py".
In the app, make python's sys.path point to that "py" subdir.
Example

OnAfterInit event
```
procedure TfmMain.PythonEngineAfterInit(Sender: TObject);
var
  Dirs: array of string;
  {$ifdef windows}
  dir: string;
  {$endif}
  PathAppend: boolean;
begin
  AppPython.Initialize;
  AppVariantInitializePython;
  Dirs:= nil;

  {$ifdef windows}
  PathAppend:= false;
  dir:= ExtractFileDir(Application.ExeName)+DirectorySeparator;
  SetLength(Dirs, 2);
  Dirs[0]:= dir+ChangeFileExt(UiOps.PyLibrary, 'dlls');
  Dirs[1]:= dir+ChangeFileExt(UiOps.PyLibrary, '.zip');
  {$else}
  PathAppend:= true;
  {$endif}

  //add to sys.path folders py/, py/sys/
  Dirs:= Concat(Dirs, [AppDir_Py, AppDir_Py+DirectorySeparator+'sys']);

  AppPython.SetPath(Dirs, PathAppend);
end;
```

SetPath:
```
procedure TAppPython.SetPath(const Dirs: array of string; DoAdd: boolean);
var
  Str, Sign: string;
  i: Integer;
begin
  Str:= '';
  for i:= 0 to Length(Dirs)-1 do
    Str:= Str + 'r"' + Dirs[i] + '",';
  if DoAdd then
    Sign:= '+='
  else
    Sign:= '=';
  Str:= Format('sys.path %s [%s]', [Sign, Str]);

  Exec(Str+';print("Python %d.%d.%d"%sys.version_info[:3])');
end;

```

**Comment by Alexey-T** [comment]
Example also puts to sys.path

- python36.dll
- folder 'dlls' with *.pyd files (DLLs)

**Comment by raelb** [comment]
What do you mean by:
> Put the lib into the relative folder of your app.

What lib are you referring to?

I am trying to get a minimal example running, using beautifulsoup4.

    from bs4 import BeautifulSoup
    html_doc = """<html><head><title>The Dormouse's story</title></head>
    <body>
    <p class="title"><b id = "boldest"> The Dormouse's story</b></p>
    <p class="story">...</p>
    """
    soup = BeautifulSoup(html_doc,'html.parser')
    print(soup.title)

with pipenv, I can see it installs following packages:
![image](https://user-images.githubusercontent.com/13108198/162588493-f6a34068-846d-49ca-bc91-e71c18908e4d.png)

I copied those to a py subfolder:
![image](https://user-images.githubusercontent.com/13108198/162588522-c0cfd552-6fa0-40c1-b58c-7b30aeec0535.png)

python37.dll is in same folder as exe. (my system is using 3.7.2)

if i try to run the script i get error:
![image](https://user-images.githubusercontent.com/13108198/162588572-c5cac879-962e-43c8-93a6-3d0b2ad572ba.png)

**Comment by Alexey-T** [comment]
>What lib are you referring to?

The SUBJECT tells what is the 'lib' - e.g. if it is NNN folder with `__init__.py` then lib is the folder NNN.

**Comment by Alexey-T** [comment]
example for BS4 lib. The folder bs4 (with Py codes) must be placed in the folder which you add to `sys.path`.

**Comment by raelb** [comment]
hmmm, I think I am doing that correctly.

However I still get this error:
![image](https://user-images.githubusercontent.com/13108198/162592150-8b62e30b-91df-4898-acbb-a0be68d8a12d.png)

Can you take a look at this demo:
(you need to change dllpath)
[Demo01_embed.zip](https://github.com/pyscripter/python4delphi/files/8457784/Demo01_embed.zip)

**Comment by Alexey-T** [comment]
soemthing wrong. 'collections' is in the puthon37.zip, right? so it must be found. check that you escaped '\' when setting sys.path

**Comment by Alexey-T** [comment]
Also try to execute small script which does "print(sys.path)".

**Comment by raelb** [comment]
It is working now. I didn't realise I need to include the zip file as well.
Thanks for your help

**Comment by kazuser** [comment]
https://github.com/Embarcadero/PythonEnviroments? 😶
