### ISSUE TITLE
Missing Python33.dll

### ISSUE THREAD

**Issue by limelect** [pyscripter/python4delphi#356]
D10.2.3
Demo 1
Missing Python33.dll from my system
How to get it and where to put it?
Do i need more DLL's?

**Comment by limelect** [comment]
ups 
Note that Python 3.9+ cannot be used on Windows 7 or earlier.
and I have window 7

**Comment by limelect** [comment]
from python.org, get 'embedded python 3.10'. unpack files python310.dll, python310.zip to demo folder.
But your demo asks for Python33.dll

**Comment by halilhanbadem** [comment]
If you installed Python from the Windows Store, it is normal to encounter this problem.
Download Python and just add "python310.the dll is" next to the project executable.
https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe
Please make sure it is set up correctly. Restart your system as a suggestion.
I have encountered the same problem and solved it this way.

**Comment by pyscripter** [comment]
Install a python distribution before running the demos.  The demos set the "UseLastKnownVersion" property to True, and the installed version will be used without issues.
