### ISSUE TITLE
How can I compile script to bytecode then exec it later?

### ISSUE THREAD

**Issue by avpnvpn** [pyscripter/python4delphi#358]
Hi, I tried to embed python4delphi as one of the scripters in my project recently. 
The scripts may be run multiple times and I was thinking about how I could pre-compile script.py into bytecode (Py_CompileString) the first time then exec() it without compiling again later. This will surely make the scripts run faster but I don't know how to do that in python4delphi.  Any help is appreciated.

TIA

**Comment by pyscripter** [comment]
You can use Py_CompileString to get a code object and then PyObject_CallObject to run the compiled code.  You can look these function up in the python documentation: 

https://docs.python.org/3/c-api/veryhigh.html
https://docs.python.org/3/c-api/call.html#c.PyObject_Call

**Comment by avpnvpn** [comment]
Thank you and I will give it a try.

**Comment by avpnvpn** [comment]
Sorry for the inconvenience. I am new to Github.
I did read the doc and I will try the support forum if I can not solve the problem.
Thanks

**Comment by pyscripter** [comment]
If you have red the [docs](https://docs.python.org/3/c-api/call.html) you would know that PyObject_CallObject expects a tuple and not a string.

Please submit questions to the the [P4D Support Forum](https://en.delphipraxis.net/?forumId=39).  This is an issue tracker, not a support forum.
