### ISSUE TITLE
TPyDelphiObject.SetAttrO implemenation ignores setters defined by AddGetSet

### ISSUE THREAD

**Issue by cosina** [pyscripter/python4delphi#360]
SetAttrO  will never call defined setter:
  // Only call the inherited method if the attribute exists
  if GetPythonEngine.PyObject_HasAttrString(GetSelf, PAnsiChar(key)) = 1 then
    Result := inherited SetAttrO(key, value);
    
While GetAttrO always calls at the beginning:
begin
  Result := inherited GetAttrO(key);

As result setter always use RTTI while getter can use user define metod.

**Comment by pyscripter** [comment]
I will look into this.  But could you please provide a simple demo that demonstrates the issue?

**Comment by pyscripter** [comment]
PyObject_HasAttrString should return true for properties defined with AddGetSet as the following python script demonstrates.  

```python
class C:
    def __init__(self):
        self._x = None

    @property
    def x(self):
        """I'm the 'x' property."""
        return self._x

    @x.setter
    def x(self, value):
        self._x = value

c = C()

print(hasattr(c, 'x'))
```

**Comment by pyscripter** [comment]
Maybe your issue was due to #368 which is now fixed.
inherited SetAttrO was never called and leaking memory.
