### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by peardox** [pyscripter/python4delphi#363]
All I can seem to find is some YouTube videos and the included demos

Looking for API references

**Comment by fastbike** [comment]
Pull down the repo, run the installation.

Use the source
https://github.com/pyscripter/python4delphi/tree/master/Source

**Comment by peardox** [comment]
Ahh, the comments are for people who can't read code school of documentation

**Comment by pyscripter** [comment]
What we provide at the moment is a large number of demos from simple to more complex ones, and a large number of video and other tutorials.  Contributions such as to API reference or other documentation are very welcome.
