### ISSUE TITLE
Definition and 64x Unicode. Please help

### ISSUE THREAD

**Issue by Kristofer1212** [pyscripter/python4delphi#364]
Hello, i'm having this error's trying to compile demo1:

Delphi 10.4

[dcc64 Fatal Error] Unit1.pas(11): F2048 Bad unit format: 'C:\python4delphi\Packages\Delphi\Delphi 10.4+\Win32\Debug\Vcl.PythonGUIInputOutput.dcu' - Expected version: 34.0, Windows Unicode(x64) Found version: 34.0, Windows Unicode(x86)

[dcc64 Fatal Error] Vcl.PythonGUIInputOutput.pas(1): F1026 File not found: '..\Definition.Inc'

Please help. Thanks

**Comment by pyscripter** [comment]
The source subdirectories (e.g., 'C:\python4delphi\\Source and 'C:\python4delphi\\Source\vcl) are not on the 64 bit library path.  You need to add them.
