### ISSUE TITLE
Demo 16 example 2

### ISSUE THREAD

**Issue by Kristofer1212** [pyscripter/python4delphi#365]
WORKING python4delphj Demo 16 - Pastebin.com
https://pastebin.com/EaJCNa3N
https://ibb.co/VV53Kg5
show props.Age

NOT working
https://pastebin.com/vLfZA28k
https://ibb.co/WpyY1TL
doesnt show props.Age

Please help. I googled it, but still cant do it. i think maybe can be easy, its an short code. But im not getting it.

Maybe i need to import the class to call it from another file ? Thanks very much !!!

**Comment by peardox** [comment]
Yeah, I'm fighting with this stuff too and looking at the response to #363 we're on our own (but I do intend to document what I work out)

From what I can observe the module imported at the start of the Python is created dynamically by Delphi.

Adding the following to the end of the Python helps a little...

```
for i in props.GetPropertyList():
  print(i, props.GetProperty(i))
print(type(props))
print(dir(props))

```

Your pAge thing doesn't seem to actually do anything useful, I guess what you want to do is assign props.Age = \<something\>

**Comment by pyscripter** [comment]
Your TProperties 

```python
class TProperties:
  def getattr(Self, Key):
      return props.GetProperty(Key)
 
  def setattr(Self, Key, Value):
      props.SetProperty(Key, Value)
 
  def repr(Self):
    tmp = ""
    for i in props.GetPropertyList():
      if tmp:
        tmp = tmp + ", "
      tmp = tmp + i + " = " + str(getattr(Self,i))
    return tmp
```

Instead it should be as in the demo:

```
class TProperties:
  def __getattr__(Self, Key):
      return props.GetProperty(Key)

  def __setattr__(Self, Key, Value):
      props.SetProperty(Key, Value)

  def __repr__(Self):
    tmp = ""
    for i in props.GetPropertyList():
      if tmp:
        tmp = tmp + ", "
      tmp = tmp + i + " = " + str(getattr(Self,i))
    return tmp
```

Notice the double underscores in the names.

This is an issue tracker.   You should be asking such questions at the forum: https://en.delphipraxis.net/?forumId=39
