### ISSUE TITLE
Non-Windows FMX won't install on Community Edition

### ISSUE THREAD

**Issue by peardox** [pyscripter/python4delphi#367]
@lmbelo requested issue be noted here (attemped with Embarcadero branch)

The Multi-Installer just throws up a dialog box saying there's no install directory when run

Installing via Delphi from project group compilation fails as the non-Windows targets try to compile source that includes the Windows unit

The result of this is that no down-stream projects (Python Environments, Lightweight wrappers, P4D Data Sciences can be installed on non-Wondows targets either).

I will stress that this is observed using Delphi 10 Sydney Community Edition so if you have a 'Real' Delphi on system this may result in different experiences.

Suggested replication - use a clean Windows install and Delphi Community Edition, easiest way to achieve this without spare kit is to use a VMWare Player with fresh install of Win10 + Delphi Community then this try to install this and dependant libraries.

If resolution is found very clear documentation would help (I'd write it myself if I could get the stuff to install)

**Comment by lmbelo** [comment]
@peardox, 
you can move this issue to the Embarcadero repo instead:
https://github.com/Embarcadero/python4delphi/issues

**Comment by peardox** [comment]
@lmbelo I did say in Discord there wasn't a issue tracker - now there is I see so moving + closing
