### ISSUE TITLE
TPyDelphiObject.SetAttrO causes memory leak

### ISSUE THREAD

**Issue by pyscripter** [pyscripter/python4delphi#368]
As per title.

See https://en.delphipraxis.net/topic/7112-strange-memory-leak-with-checkbox/ for a description and a test project.

Related:

https://github.com/pyscripter/python4delphi/issues/360

**Comment by pyscripter** [comment]
inherited SetAttrO was never called and leaking memory.
Fixed now.

@lmbelo This was serious.  Please have a look and make sure it is fixed on your side.

**Comment by lmbelo** [comment]
> inherited SetAttrO was never called and leaking memory. Fixed now.
> 
> @lmbelo This was serious. Please have a look and make sure it is fixed on your side.

@pyscripter thanks, I surely will.
