### ISSUE TITLE
Problem with Python 2.7.x

### ISSUE THREAD

**Issue by Jens01** [pyscripter/python4delphi#37]
When I want to use Python 2.7.x I have to insert some lines in PythenEngine.pas :

In line 4794 :

``` Delphi
  AssignPyFlags;
  if DirectoryExists('C:\Python27') then
    Py_SetPythonHome('C:\Python27')
  else
    raise Exception.Create('Pythonfolder not found : "C:\Python27"');
  Py_Initialize;
```

and before `Py_Initialize: procedure; cdecl;`  in line 1683:
`Py_SetPythonHome:   procedure ( s: PAnsiChar); cdecl;`

and before `Py_Initialize := Import('Py_Initialize');` in line 3742 :
`Py_SetPythonHome          := Import('Py_SetPythonHome');`

**Comment by pyscripter** [comment]
None of the above is needed.
If you are using a  registered Python 2.7 from www.python.org all you have to do is
Uncheck Use last known version.
Set RegVersion to 2.7
and DLLName to python27.dll

If you are using some other installation of python (I see you have it in "C:\Python27") you need to also fill the DLLPath.  For example you can set it to "C:\Python27".
