### ISSUE TITLE
Can't create TPythonEngine at run-time. Why??

### ISSUE THREAD

**Issue by denpoon** [pyscripter/python4delphi#374]
Since I need to run Python4Delphi in a separate thread. I first try to modify demo01 of Python4Delphi to  create TPythonEngine and TPythonGUIInputOutput at run time instead of design time.

procedure TForm1.FormCreate(Sender: TObject);
begin
  PythonGUIInputOutput1:= TPythonGUIInputOutput.Create(self);
  PythonGUIInputOutput1.Name := 'PythonGUIInputOutput1';
  PythonGUIInputOutput1.Output := Memo2;

  PythonEngine1 := TPythonEngine.Create(self);
  PythonEngine1.Name := 'PythonEngine1';
  PythonEngine1.IO := PythonGUIInputOutput1;
end;

However, when I run the demo01.exe now, it pops up the error "**Python is not properly initialized**"!!!

How do fix it?

My eventual goal is to create TPythonEngine , TPythonGUIInputOutput and other python4delphi components in a separate thread at run time, so as to make python run in its own thread.

**Comment by pyscripter** [comment]
Please ask questions at the support forum.
You are not calling PythonEngine1.Load.   
Demo34 shows how to load a python engine dynamically,  but please note that this is very tricky and things can go wrong.

**Comment by denpoon** [comment]
pyscripter wrote:
>
> Please ask questions at the support forum.
>

Please excuse my ignorance. What is the url of the support forum?

Dennis

**Comment by pyscripter** [comment]
https://en.delphipraxis.net/?forumId=39
You have already posted your questions there.
