### ISSUE TITLE
Potential AV on TPythonEngine.DoOpenDll (Linux)

### ISSUE THREAD

**Issue by cosina** [pyscripter/python4delphi#376]
DoOpenDl loop for all PYTHON_KNOWN_VERSIONS defined versions. But if the version is not found then inherited is called with an empty name which causes AV. Inherited should be called only if UseLastKnownVersion  is false.

`procedure TPythonEngine.DoOpenDll(const aDllName : string);
var
  i : Integer;
begin
  if UseLastKnownVersion then
    for i:= Integer(COMPILED_FOR_PYTHON_VERSION_INDEX) downto 1 do
    begin
      RegVersion := PYTHON_KNOWN_VERSIONS[i].RegVersion;
      inherited DoOpenDll(PYTHON_KNOWN_VERSIONS[i].DllName);
      if IsHandleValid then
      begin
        DllName := PYTHON_KNOWN_VERSIONS[i].DllName;
        APIVersion := PYTHON_KNOWN_VERSIONS[i].APIVersion;
        Exit;
      end;
    end
  else begin
    RegVersion := SysVersionFromDLLName(aDllName);
    inherited;  <--- HERE
  end;
end;'

**Comment by pyscripter** [comment]
In Linux you have to specify the DllName and DllPath.  The  auto-detection does not work.

**Comment by cosina** [comment]
Actually autodetection works for me on Linux and macOS as well. The only problem is that if it fails (eg no libpython installed) then the reported condition raised

**Comment by cosina** [comment]
It seems that empty DLLName is a problem on Linux

**Comment by pyscripter** [comment]
How come it is empty?  The constructor adds a default value (the dll name of the latest version).

**Comment by cosina** [comment]
I added some trace messages into TDynamicDll.OpenDll:

```
procedure  TDynamicDll.OpenDll(const aDllName : string);
var
  s : string;
begin
  UnloadDll;

  BeforeLoad;

  FDLLHandle := 0;

  WriteLn(ErrOutput, 'name= '+aDllName);
  DoOpenDll( aDllName);

  if not IsHandleValid then begin
    {$IFDEF MSWINDOWS}
    s := Format('Error %d: Could not open Dll "%s"',[GetLastError, DllName]);
    {$ELSE}
    s := Format('Error: Could not open Dll "%s"',[DllName]);
    {$ENDIF}
    if FatalMsgDlg then
      {$IFDEF MSWINDOWS}
      MessageBox( GetActiveWindow, PChar(s), 'Error', MB_TASKMODAL or MB_ICONSTOP );
      {$ELSE}
      WriteLn(ErrOutput, s);
      {$ENDIF}

    if FatalAbort then
      Quit;
  end else
    AfterLoad;
  WriteLn(ErrOutput, 'Success');
end;

```


**Ubuntu 20.04**
DllName="libpython3.11.so"
DllName="libpython3.10.so"
DllName="libpython3.9.so"
DllName="libpython3.8.so"
DllName="libpython3.7m.so"
DllName="libpython3.6m.so"
DllName="libpython3.5m.so"
DllName="libpython3.4m.so"
DllName="libpython3.3m.so"
DllName=""
Error: Could not open Dll “”
Python could not be properly initialized. We Must quit.

**Ubuntu 18.04**
DllName="libpython3.11.so"
DllName="libpython3.10.so"
DllName="libpython3.9.so"
DllName="libpython3.8.so"
DllName="libpython3.7m.so"
DllName="libpython3.6m.so"
DllName="libpython3.5m.so"
DllName="libpython3.4m.so"
Crash! 

**Ubuntu 20.04 after “sudo apt-get -y install libpython3.8-dev”**
_Proof that LastKnowVersion works_
DllName="libpython3.11.so"
DllName="libpython3.10.so"
DllName="libpython3.9.so"
DllName="libpython3.8.so"
Success

**Comment by pyscripter** [comment]
I don't get it.  
1.  OpenDLL should be called just once, by LoadDLL.
2.  Your write statement is   `WriteLn(ErrOutput, 'name= '+aDllName);` but in the output I see 'DLLName'.   So this comes from another write statement.  And I see no output from this statement!
3.  Where is DLLName set to an empty string?
4. Where does the crash occur?

**Comment by pyscripter** [comment]
I am thinking of changing TPythonEngine.DoOpenDll to

```
procedure TPythonEngine.DoOpenDll(const aDllName : string);
var
  i : Integer;
begin
  if UseLastKnownVersion then
    for i:= Integer(COMPILED_FOR_PYTHON_VERSION_INDEX) downto 1 do
    begin
      RegVersion := PYTHON_KNOWN_VERSIONS[i].RegVersion;
      inherited DoOpenDll(PYTHON_KNOWN_VERSIONS[i].DllName);
      if IsHandleValid then
      begin
        DllName := PYTHON_KNOWN_VERSIONS[i].DllName;
        APIVersion := PYTHON_KNOWN_VERSIONS[i].APIVersion;
        Exit;
      end;
    end
  else begin
    RegVersion := SysVersionFromDLLName(aDllName);
    inherited;
  end;
end;
```

Does this work OK?

**Comment by cosina** [comment]
Sorry I copy edited code 'name'->'DllName'.  The crash happens in 'inherited' so the output is not recorded

My initial proposal is the same as yours and it fixed the problem.

**Comment by pyscripter** [comment]
> Sorry I copy edited code 'name'->'DllName'. The crash happens in 'inherited' so the output is not recorded

Still I am still puzzled.  See above.

**Comment by pyscripter** [comment]
I am reluctant to change the code since as it stands, it gives P4D an extra chance of finding a python dll with a DLLName different than then standard names, which could be useful in Linux.

**Comment by pyscripter** [comment]
I eventually implemented the suggested change.
