### ISSUE TITLE
Outputs from Python script do not match outputs from Terminal/Jupyter

### ISSUE THREAD

**Issue by arnyziukas** [pyscripter/python4delphi#378]
Hi,

The issue I have with P4D is that unassigned variable outputs don't seem to be printed/caught and returned to Delphi. I am aware that the issue might be my configuration/lack of python knowledge.

minimum implementation would be:
```
S = "Test String"
print( S )
str( S )
```
Terminal and Jupyter based applications would print out 2 outputs while  P4D seems to only return the "print" output...

Did consider using "sys.settrace" to assign a trace print for every single return, but am not sure whether the result would be same or would just end up with being cluttered since it will output all of the returns.

P4D PythonEngine is setup with [ pfDebug, pfInteractive, pfVerbose ] PyFlags...

Any help would be appreciated.

Thank you

**Comment by Alexey-T** [comment]
>Terminal and Jupyter based applications would print out 2 outputs while P4D seems to only return the "print" output...

It's normal, P4D is not assiming 'print' when you enter the expression. CudaText has workaround for this. It detects that you entered the expression

```
function IsPythonExpression(const S: string): boolean;
```
https://github.com/Alexey-T/CudaText/blob/master/app/proc_str.pas

and then it adds 'print( ... )'.
