### ISSUE TITLE
PythonEngine.ExecStrings freezes all running threads until the script is executed.

### ISSUE THREAD

**Issue by unununununununun** [pyscripter/python4delphi#380]
PythonEngine.ExecStrings freezes all running threads until the script is executed.
For example, I have a lot of threads working with an interface, and not only.
I run the script, it runs for 10 seconds, all my threads are suspended until PythonEngine.ExecStrings is executed.
Is this how it should be?

**Comment by pyscripter** [comment]
If you mean that it freezes Delphi threads (threads running Delphi code), then this is not the case.

If on the other hand you are trying to run Python code in threads, please study the threading demo and read numerous related topics in the support forum.

**Comment by unununununununun** [comment]
Thank you.
