### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by dominiced** [pyscripter/python4delphi#381]
Hello,

When I run the following script a number of times (5 times, sometimes 6) within my application in Python 3.10, it soon causes an AV to occur from within the Python Engine when calling ExecStrings.

```
import xml.etree.ElementTree as xml
tree = xml.parse(r"C:\Program Files (x86)\Springfield.xml")
print(tree.getroot())
del tree
```

I cannot share the XML file I'm using for confidential reasons, but I'm sure if you was to use any XML file you'll eventually hit the same issue (my XML file is 285KB, you may need something of a similar size, because I suspect it could be a memory issue considering it takes a number of attempts to reach the error).

I **don't** exhibit such behavior in earlier versions of Python, _only_ in 3.10!

If anyone has any ideas or suggestions, I'd greatly appreciate the help!

**Comment by pyscripter** [comment]
It does not sound like a P4D issue.  
Please ask such questions in the support forum.
