### ISSUE TITLE
Subclassing not properly defined

### ISSUE THREAD

**Issue by cosina** [pyscripter/python4delphi#382]
if issubclass( Form, CustomForm ):
  print('yeee')
else:
  print('nope')  # always here
  
It seems that _tp_base_ of the inherited class is not set.

**Comment by pyscripter** [comment]
Indeed.  Is it important?

Could be fixed in a couple of ways.

1. RegisterDelphiWrapper should try to find the nearest parent class registered and set tp_base accordingly
2. Implement __subclasshook__ in TPyDelphiObject

**Comment by pyscripter** [comment]
Could you please confirm it is now working as expected?
