### ISSUE TITLE
compatability with FPC 3.2.3

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#385]
MethodCallback.pas
ARM CPU don't have define CPUARM32, so I must add this:
```
{$I Definition.Inc}
{$IFDEF CPUARM}
  {$DEFINE CPUARM32}
{$ENDIF}

unit MethodCallBack;    
```

**Comment by Alexey-T** [comment]
Let's add this block to definitions.inc
```
{$IFDEF FPC}
  {$IFDEF CPUARM}
    {$DEFINE CPUARM32}
  {$ENDIF}

  {$IFDEF UNIX}
    {$DEFINE POSIX}
  {$ENDIF}
{$ENDIF}
```

Why 'posix'? PythonEngine uses this ifdef.

**Comment by pyscripter** [comment]
Why you opened two issues?  Is this not the same issue as #386?   Let's confine the discussion in one of the two.

**Comment by Alexey-T** [comment]
Closing.
