### ISSUE TITLE
updated MethodCallback unit: now it don't work on FPC ARM64

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#387]
I sync'ed this unit (in python4lazarus) and now CudaText ARM64 don't work. it shows py error on start.
`ValueError: module functions cannot set METH_CLASS or METH_STATIC`

I am comparing the new unit with old one (in Python4Lazarus before sync with you).
old unit did not have all variants of `function  GetCallBack`.
attached this old unit.
[MethodCallBack.zip](https://github.com/pyscripter/python4delphi/files/9944611/MethodCallBack.zip)

can you please make sure FPC ARM64 works now?

My device: Raspberry Pi-3, OS: Manjaro ARM.

**Comment by Alexey-T** [comment]
Seems old version did not have this variant of func:
```
{$IFDEF CPUARM64}
function  GetCallBack(Self: TObject; Method: Pointer; ArgNum: Integer;
  CallType: TCallType): Pointer;
```

**Comment by pyscripter** [comment]
The changes provided Delphi support for Andoid and the Apple M2 chip.
Before there was no support whatsoever for CPUARM.
They have been tested extensively with Delphi on Android.

I do not use CPUARM so I am not in a position to test with either fpc or Delphi.   But if you can make work with fpc that would be great.

**Comment by Alexey-T** [comment]
My situation: I compile app for Linux aarch64. I guess it must work because it works for you on Adroid(==Linux). but it doesn't.

**Comment by pyscripter** [comment]
@Alexey-T Is it picking the correct GetCallBack?  {$IFDEF CPUARM64}   What is your target CPU?  Is it the Apple M2?
@lmbelo Any ideas why GetCallBack is not working on fpc?

**Comment by Alexey-T** [comment]
Yes, it is picking GetCallback from CPUARM64, I added 'dd' and then it cannot compile.
No, it is not Apple M2, it is Raspberry Pi-3 with OS Manjaro ARM (arm64).

**Comment by pyscripter** [comment]
> I added 'dd'

What do you mean?

**Comment by Alexey-T** [comment]
I mean I added some 'crap' inside the block
```

{$IFDEF CPUARM64}
function  GetCallBack(Self: TObject; Method: Pointer; ArgNum: Integer;
  CallType: TCallType): Pointer;
const                            
```
and crap breaks the compiling for CPU ARM64. so this block is used!

**Comment by lmbelo** [comment]
@Alexey-T arm support was introduced as part of the Android support by Embarcadero. P4D does not support ARM processors before this exension. So, I'm not sure what you meant with "it is now broken after sync...".

**Comment by pyscripter** [comment]
> Raspberry Pi-3

This not a Delphi target, so I do not think you will get much help on this, but it would be nice to get it working.

Would be good to know whether it works with the Apple M2.


Both Delphi and fpc now support TMethodImplementation (see https://wiki.freepascal.org/FPC_New_Features_3.2.0#Rtti_unit).  This would allow to create callbacks without using assembly (see https://wiki.freepascal.org/FPC_New_Features_3.2.0#Rtti_unit).   But the announcement says that it is not supported on all platforms.  Can you find out for which platforms it is supported?

**Comment by pyscripter** [comment]
@lmbelo 
> So, I'm not sure what you meant with "it is now broken after sync...".

Indeed.  I have made the same point above.

Lucas.  has the code been tested with the Apple M2?  Would you expect the code to work with any ARM64 processor?

**Comment by pyscripter** [comment]
> ValueError: module functions cannot set METH_CLASS or METH_STATIC

This is coming from python.  (see for instance https://github.com/pandas-dev/pandas/issues/23040) .  Why do you think methodcallback.pas is at fault.   

You could try the MethodCallback tests to see whether it works correctly on your platform.

**Comment by Alexey-T** [comment]
>Did it ever work? 

Yes, with the old version of Python4Lazarus (latter I tried to sync with P4D, and maybe I made mistake) CudaText 1.172 worked on R-Pi-3.


>Is it using MethodCallBack?

It is used in PythonEngine unit:

1)
```
      if tpfBaseType in TypeFlags then
      begin
        tp_init             := TPythonType_InitSubtype;
        tp_alloc            := TPythonType_AllocSubtypeInst;
        tp_new              := GetCallBack( Self, @TPythonType.NewSubtypeInst, 3, DEFAULT_CALLBACK_TYPE);
        tp_free             := FreeSubtypeInst;
        tp_methods          := MethodsData;
        tp_members          := MembersData;
        tp_getset           := GetSetData;
      end;
```
2) 3 places with `GetOfObjectCallBack`.

**Comment by Alexey-T** [comment]
>You could try the MethodCallback tests to see whether it works correctly on your platform. Also you could try and run a simple console application with P4D, executing some simple code (e.g. "print('Hi') to see whether it works.

Will try !

**Comment by pyscripter** [comment]
> It is used in PythonEngine unit:

It is, but you don't use it in CudaText.  You don't create new types and you only use AddMethod.  Put a breakpoint in GetMethodCallback and see whether you hit it.

**Comment by Alexey-T** [comment]
Right, IDE don't stop inside GetCallback. False alarm. my mistake in aother one. Closing.
