### ISSUE TITLE
pythone dll

### ISSUE THREAD

**Issue by limelect** [pyscripter/python4delphi#388]
D10.2.3
My python is C:\Python\Python36-32
My Dll is python36.dll
However, running your very basic demo 01
I get an error 
error 87 could not open dll pythone34.dll

**Comment by pyscripter** [comment]
Please read https://github.com/pyscripter/python4delphi/wiki/FindingPython

**Comment by limelect** [comment]
f you want a specific registered version you need to set the following properties:
DLLName e.g. python38.dll
RegVersion e.g 3.8
Set UseLastKnownVerion property to False

i changed the dll to 36
put my path
last known to false.
ERROR could not open 36

**Comment by pyscripter** [comment]
Is your python  32 bits or 64 bits?  
Is your app 32 bits or 64 bits?

They need to match.

**Comment by limelect** [comment]
32
32
