### ISSUE TITLE
I can not install python4delphi ImportError: DLL load failed while importing DelphiVCL: The specified module could not be found

### ISSUE THREAD

**Issue by izac3d** [pyscripter/python4delphi#390]
> pip install delphivcl
Collecting delphivcl
  Using cached delphivcl-0.1.24-cp311-cp311-win_amd64.whl
Installing collected packages: delphivcl
Successfully installed delphivcl-0.1.24

> Python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from delphivcl import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>﻿
  File "C:\Program Files\Python311\Lib\site-packages\delphivcl\__init__.py", line 22, in <module>
    package = new_import()
              ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\delphivcl\__init__.py", line 15, in new_import
    ld = loader.create_module(spec)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing DelphiVCL﻿: The specified module could not be found.

**Comment by pyscripter** [comment]
Please submit the issue to https://github.com/Embarcadero/DelphiVCL4Python

**Comment by pyscripter** [comment]
@lmbelo Please have a look.
