### ISSUE TITLE
Numpy C-extensions failed

### ISSUE THREAD

**Issue by 7drSlump9** [pyscripter/python4delphi#392]
I open Demo01 project on i386 Lazarus 2.2.4 Fpc 3.2.2; with pip command i downloaded into a directory matplotlib and numpy;
My goal is run matplotlib script into lazarus, for example :

`
import matplotlib.pyplot as plt
import numpy as np

plt.style.use('_mpl-gallery')

x = np.linspace(0, 10, 100)
y = 4 + 2 * np.sin(2 * x)
fig, ax = plt.subplots()
ax.plot(x, y, linewidth=2.0)
ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()
`
when import numpy I obtain a error like photo
![pyerror1](https://user-images.githubusercontent.com/46600156/208914097-8de6bf81-9a4f-48f6-9853-0a514e86bddd.jpg)

If I try to import numpy I has same error.
Same error in Delphi 32 bit.

**Comment by pyscripter** [comment]
Please read https://github.com/pyscripter/python4delphi/wiki/MaskFPUExceptions.
