### ISSUE TITLE
distribute the final delphivcl project issue

### ISSUE THREAD

**Issue by alas82** [pyscripter/python4delphi#394]
hello , 
i follow all the steps mentioned in your tutorials , and export a form from delphi ide to python project then i tried to make the python as distributed exe using pyinstaller , the exe and dependencies as per attachment
![Capture](https://user-images.githubusercontent.com/65008114/209223088-56270ac4-4708-450c-97d6-a7b36e29cc4a.PNG)

but when you run the exe it doesnt run , please advise what is wrong

thanks

**Comment by pyscripter** [comment]
You are submitting this at the wrong place.  Shouldn't it be https://github.com/Embarcadero/PythonEnviroments?
