### ISSUE TITLE
some help withsetting up miniconda environement

### ISSUE THREAD

**Issue by BaderTalal** [pyscripter/python4delphi#395]
sorry for asking this, I tried all proposed solutions to get my  Miniconda environment to work without luck.
I have a scientific package for python which is only available as environment installed with conda. I tried many combination and using some direction found in the help for python4delphi but it did not work.
if someone can provide me with working example will be highly appreciated.
setting dllpath to the env, seams not working for me.

thanks in advance

**Comment by pyscripter** [comment]
This is an Issue tracker.
Please ask questions at the [support forum](https://en.delphipraxis.net/?forumId=39)
