### ISSUE TITLE
I couldn't install the PythonGUIInputOutput component

### ISSUE THREAD

**Issue by noseparaquesirve** [pyscripter/python4delphi#400]
Hi,
I followed the instructions in https://www.youtube.com/watch?v=aCz5h96ObUM and https://www.youtube.com/watch?v=hjY6lBgrHhM , installing successfully the engine, the wrapper and other components, but PythonGUIInputOutput doesn't show up in the palette. Also, when I try to open a demo (i.e. Demo 31), I have an error message signalling that the PythonGUIInputOutput class was not found.
What do you suggest to do?

**Comment by pyscripter** [comment]
The structure of the repo has changed since those videos.   There are now separate packages for the visual components.  Please follow the instructions at https://github.com/pyscripter/python4delphi/wiki/Installation.
