### ISSUE TITLE
Visual components don't work when you create it on the fly.

### ISSUE THREAD

**Issue by juanccilleruelo** [pyscripter/python4delphi#402]
I've taken one of your demos and saved it in another directory.
I've cleaned it. Finally, I have only three components on the form.

I've created a program that defines alternates the use of the visual components with the use of the same components created on the fly.

As you can see, if we use the version with the visual components, all works ok when executing the Script.

If we use the version with the components created on the fly, **_nothing of the created things inside the script is recognized._**

I include the three parts of the code to reproduce this issue.

**Comment by pyscripter** [comment]
Please remove the code from your report and add your project as a zip attachment.

**Comment by juanccilleruelo** [comment]
[Demo on The Fly.zip](https://github.com/pyscripter/python4delphi/files/10405304/Demo.on.The.Fly.zip)
I have included the code in this new message.

**Comment by juanccilleruelo** [comment]
> Please remove the code from your report and add your project as a zip attachment.
 
   I made it. 

 
> Moreover this issue is of the type "my program does not work, tell me why"". You are better off asking in the support forum.

   Really no. I've checked many times. This is an issue.  In the moment you use a component created on the fly the script doesn't recognize any of the external functions or variables. 

Check it, please. Is not a failure in the programing style.

**Comment by juanccilleruelo** [comment]
I previously, before creating the demo program, pushed this question in the forum. Without response.

**Comment by juanccilleruelo** [comment]
Closed without solve it!

**Comment by pyscripter** [comment]
Please do not submit support requests in the Issue Tracker.
