### ISSUE TITLE
Problem compiling in non-windows mode

### ISSUE THREAD

**Issue by Gronfi** [pyscripter/python4delphi#41]
Hi, 
if you compile in non-mswindows mode, the unit MethodCallback.pas complains in line 182 that says:
page := getmem(pagesize);

but maybe you wanted to write?: 
page := getmemory(pagesize);

Regards

**Comment by pyscripter** [comment]
Are you using Delphi or FPC?
This was changed in a patch I have recently applied.  See 
https://github.com/pyscripter/python4delphi/commit/bf1c1f8524eb47162b5144709c654ce0ab345082#diff-acb9264e223554ca66ed5362f31ecc78
and tell me whether the previous version works.

**Comment by Gronfi** [comment]
Hi,
I'm using Delphi

**Comment by Gronfi** [comment]
I should comment that I have extracted part of this unit for doing a test with the linux platform (so I don't compile the rest of the units), because my interest is at the contents of this unit. The test almost has all the code of this unit copy/pasted from the original. So, compiled with Delphi, Linux target, and used the code from this unit. Using previous code, compiles (still didn't run the test so can't say if there are running issues)

**Comment by Gronfi** [comment]
Hi,
with previous version works under Linux with Dephi. Tested

**Comment by pyscripter** [comment]
Would it be possible to submit a PR to make the code to compile with both FreePascal and Delphi on Linux?

**Comment by Gronfi** [comment]
Hi!
what do you mean with PR (a project?)

**Comment by pyscripter** [comment]
I think 88c06f11e70d471fc5dfd3b1e7e446c09eb5ab9a fixes Delphi Linux (not tested) and FPC (tested) compatibility.
