### ISSUE TITLE
 Using the DelphiVCL4Python library in Python Integerpreter causes ide to crash.

### ISSUE THREAD

**Issue by fansxs** [pyscripter/python4delphi#415]
In Python Interpreter, like this:
>>>import delphivcl as vcl
>>>btn = vcl.Button(None)
>>>btn.Caption = 'hello world'

Then the ide doesn't respond.

Test environment: windows7 x64 and windows10 x64
PyScripter version: 4.0.0.6 x64
Python version: 3.9 x64

**Comment by pyscripter** [comment]
This could be a PyScripter issue.  Please update PyScripter to the latest version and report back if the error persists.

**Comment by fansxs** [comment]
I updated to 4.2.5.0 and have the same problem.

**Comment by pyscripter** [comment]
@lmbelo Is this a delphivcl or a PyScripter issue?

**Comment by pyscripter** [comment]
@fansxs For the Windows 7 see also https://github.com/pyscripter/pyscripter/issues/1200.

Please try the update in that issue.

**Comment by fansxs** [comment]
I tested the same in win10,  importing other modules in Python Interpreter is normal, but importing delphivcl will cause a crash.

![aaaa](https://user-images.githubusercontent.com/17403815/225403529-3d2fb9a8-1946-4c4a-98b4-730d3cc17239.jpg)

**Comment by fansxs** [comment]
![cccc](https://user-images.githubusercontent.com/17403815/225405802-9c5c868f-f915-44f2-8e39-aa4964a1ae3d.jpg)
![bbbb](https://user-images.githubusercontent.com/17403815/225405820-5ef170f0-5c84-4d0e-ac2d-f906d284b17b.jpg)

**Comment by fansxs** [comment]
ok, submit it to that issue.
