### ISSUE TITLE
cannot find dll

### ISSUE THREAD

**Issue by limelect** [pyscripter/python4delphi#419]
D10.2.3
GuiPy find my Python dll python38
So why not this component?
It wants Python33
I give the name and path to the component does not help
I disabled autoload and now it says python not initialized

First demo

**Comment by pyscripter** [comment]
Is this related to https://github.com/pyscripter/python4delphi/issues/417?

**Comment by limelect** [comment]
Last download

**Comment by pyscripter** [comment]
Please read https://github.com/pyscripter/python4delphi/issues/417?

**Comment by limelect** [comment]
F7 shows
![Screenshot - 29_04_2023 , 09_57_36](https://user-images.githubusercontent.com/4199131/235288599-936ea269-5163-4c8c-9cdc-0d337e51653f.jpg)

**Comment by pyscripter** [comment]
Is this an issue related to PyScripter or P4D?
This is the P4D issue tracker.

**Comment by pyscripter** [comment]
Please see https://github.com/pyscripter/python4delphi/wiki/FindingPython
