### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by ClintPark** [pyscripter/python4delphi#42]
Hi 
 
Compiled error at python 3.6
Can you fix it as following.

{$IFDEF PYTHON36}
  COMPILED_FOR_PYTHON_VERSION_INDEX = 12;
{$ENDIF}
{$IFDEF PYTHON36} ==> {$IFDEF PYTHON37}
  COMPILED_FOR_PYTHON_VERSION_INDEX = 13;

Another question.
Do you have any reason for gPythonEngine and gVarType  as global variables in PythonEngine.pas?
(3141 line in PytonEngine.pas)

I cannot make it more one pythonengine component because of these global variables.

Thanks.

**Comment by pyscripter** [comment]
I have corrected this. 
Please note that, even if the library is compiled with the defaults, it can still load the python 3.6 (and 3.7) dll without any issues.  Just change the RegVerision and DLLName properties of the component.  The defines PYTHONxx are really about the minimum Python version that can be loaded.

I am not sure whether it is possible and definitely not advisble to load more than one Python dll at the same time.   The global variable is essential for many of the library modules to work (e.g Varpyth).  You typically access the Engine with the GetPythonEngine function which relies on the global variable.
