### ISSUE TITLE
Installing a Library

### ISSUE THREAD

**Issue by Eezygzy** [pyscripter/python4delphi#421]
Hi there are you able to install a python library like PyPDF to Python4Delphi and use it in delphi?

**Comment by pyscripter** [comment]
Please use the [support forum](https://en.delphipraxis.net/forum/39-python4delphi/) for such questions.

**Comment by kazuser** [comment]
Eezygzy, try [this](https://github.com/Embarcadero/Lightweight-Python-Wrappers/issues/18) ;)
