### ISSUE TITLE
Less dramatic error handling if incorrect dll?

### ISSUE THREAD

**Issue by wilkojohnny** [pyscripter/python4delphi#423]
Hi,

I'm trying to use python4delphi within a much larger program, and I think a tweak is needed. If an incorrect dll is given to python4delphi and it fails to load it in, it gives the error 'Python could not be properly initialized. We must quit', and proceeds to shut down the entire program.

Is there any chance this could please be changed to be less dramatic, e,g. by raising an exception which I could handle somewhere else in the code? In our case, shutting down the entire program just because one component won't load would be very irritating to the end user.

**Comment by pyscripter** [comment]
Set FatalAbort to False.
