### ISSUE TITLE
Create wsgi gateway with p4d

### ISSUE THREAD

**Issue by rpijnacker** [pyscripter/python4delphi#427]
To combine web projects in delphi and python it would be interesting to have a delphi webserver (for example escegece) that
can be combined with python scripting. To use an python flask app could then be used to add endpoints through an wsgi 
gateway. We already explored the options to have P4D as scripting engine behind a escegece webserver that works with normal setup
and also with venv. Things like docx2pdf are now easy to implement and work better than any paid delphi docx2pdf converter i have tried

**Comment by pyscripter** [comment]
I am not sure what is your suggestion for this project.  In any case, adding a Delphi webserver is not in the scope of this project.  There is nothing preventing you from doing that in your own projects, or finding other innovative ways of combining python and Delphi.
