### ISSUE TITLE
PythonFMX.res not found

### ISSUE THREAD

**Issue by Eezygzy** [pyscripter/python4delphi#429]
HI there.

When I try to build or install dclPythonFmx280.bpl, during the installation process, I am met with the error "[dcc32 Error] E1026 File not found: 'PythonFmx.res' ". Do you know how I can fix this error?

many thanks

**Comment by pyscripter** [comment]
Are you following the instructions at https://github.com/pyscripter/python4delphi/wiki/Installation?

I cannot reproduce this issue with Delphi 11:
- Cloned the repository
- Opened P4DComponentSuite group project.
- Build all packages
- Installed the Vcl and Fmx designer packages (the ones starting with dcl).

Everything went smoothly.  'PythonFmx.res and five other res  files were automatically created.

**Comment by Eezygzy** [comment]
Yes I am fairly certain that I have installed it correctly. I just uninstalled and reinstalled it. The error is still the same. "Can't load package C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\dclPythonFmx280.bpl. The specified module could not be found". However when I go to that directory dclPythonFmx280.bpl is there. So is there any way that I can insert the directory manually?

**Comment by Eezygzy** [comment]
I am also noticing that in the public folder, there is no Documents but there is Public Documents. could this be causing the issue?

**Comment by pyscripter** [comment]
Can you provide some more detail.

1. Add the source subdirectories (e.g., D:\Components\P4D\Source, D:\Components\P4D\Source\vcl and D:\Components\P4D\Source\fmx) to the IDE's library path
2. Open P4DComponentSuite group project.
3. Build all packages
4. Install the Vcl and Fmx designer packages (the ones starting with dcl).

Which of the above fails and what is the error message?

> The error is still the same. "Can't load package C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\dclPythonFmx280.bpl. The specified module could not be found".

Earlier you said that the error message was "File not found: 'PythonFmx.res' "  I am getting confused.

**Comment by Eezygzy** [comment]
'So I have added all that they recommended to the library path. So when I click build on "dclPythonFmx280.bpl" it says [dcc32 Error] E1026 File not found: 'PythonFmx.res' and [dcc32 Fatal Error] dclPythonFmx.dpk(38): F2063 Could not compile used unit 'FMX.PythonReg.pas'. When I click Install it says "Can't load package C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl\dclPythonFmx280.bpl. The specified module could not be found".

dclPythonVCL installed and built correctly as well as dclPython.

**Comment by pyscripter** [comment]
- After opening the group project, right click on it and select "Build All".  Do you still see the same error messages?  The *.res files should be automatically generated.
- Do you have write-access to the location of the repository?

**Comment by Eezygzy** [comment]
Ok Thank you very much. By clicking Build all it allowed me to install it.
