### ISSUE TITLE
How about my fork?

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#43]
Hi
Do you think changes in your repo needed for my fork https://github.com/Alexey-T/Python-for-lazarus
?
i don't have time to check...

**Comment by pyscripter** [comment]
e37caaf8a2a3fcfb509aee73cc8225fc4669ccc7



https://bugs.freepascal.org/view.php?id=20849

**Comment by Alexey-T** [comment]
My email— support at uvviewsoft.com
