### ISSUE TITLE
Apps with p4d do not run when python3.11 is used 

### ISSUE THREAD

**Issue by quini27** [pyscripter/python4delphi#432]
I installed P4D when I used Anaconda 3 with python 3.8. It worked fine. But I had to reinstall Anaconda and the latest python version  was installed (3.11). All my projects were updated with this python version and they compile but, when running the error message Error 127:could not map symbol "Py_divisionWarningFlag" appears.

**Comment by Alexey-T** [comment]
Did you try that latest P4D ? It had changes for Py 3.11 in last months.

**Comment by quini27** [comment]
Thank you. I am going to install the latest P4D.

> Did you try the latest P4D ? It had changes for Py 3.11 in last months.

Thank you. I am going to install the latest version of P4D

**Comment by pyscripter** [comment]
Python 3.12 is also supported!
