### ISSUE TITLE
Сan't compile PythonVcl

### ISSUE THREAD

**Issue by Niglavok** [pyscripter/python4delphi#435]
Сan't compile PythonVcl
unit WrapVclComCtrls
2392: PythonToPythonType(LVarParam.Value).PyObjectClass).DelphiObjectClass; PythonToPythonType -> TPythonType ?
3024: PyTuple_SetItem(LPyTuple, 3, OwnerDrawStateToPython(State)); OwnerDrawStateToPython -> CustomDrawStateToPython ?
3666: PythonToPythonType(LVarParam.Value).PyObjectClass).DelphiObjectClass; PythonToPythonType -> TPythonType ?

**Comment by netzeng** [comment]
The problem I encountered is the same as yours, I have tried many times。
Checking project dependencies...
Compiling Python.dproj (Release, Win32)

Compiling PythonVcl.dproj (Release, Win32)
dcc32 command line for "PythonVcl.dpk"
[dcc32 Error] WrapVclComCtrls.pas(362): E2003 Undeclared identifier: 'TNodeCheckState'
[dcc32 Error] WrapVclComCtrls.pas(374): E2005 'TNodeCheckState' is not a type identifier
[dcc32 Error] WrapVclComCtrls.pas(726): E2005 'TNodeCheckState' is not a type identifier
[dcc32 Error] WrapVclComCtrls.pas(753): E2005 'TNodeCheckState' is not a type identifier
[dcc32 Error] WrapVclComCtrls.pas(757): E2133 TYPEINFO standard function expects a type identifier
[dcc32 Error] WrapVclComCtrls.pas(2393): E2003 Undeclared identifier: 'TTVCheckStateChangedEvent'
[dcc32 Error] WrapVclComCtrls.pas(2393): E2133 TYPEINFO standard function expects a type identifier
[dcc32 Error] WrapVclComCtrls.pas(2397): E2005 'TNodeCheckState' is not a type identifier
[dcc32 Error] WrapVclComCtrls.pas(2437): E2003 Undeclared identifier: 'TTVCheckStateChangingEvent'
[dcc32 Error] WrapVclComCtrls.pas(2437): E2133 TYPEINFO standard function expects a type identifier
[dcc32 Error] WrapVclComCtrls.pas(2441): E2005 'TNodeCheckState' is not a type identifier
[dcc32 Fatal Error] WrapDelphiVCL.pas(38): F2063 Could not compile used unit 'WrapVclComCtrls.pas'
Failed
Elapsed time: 00:00:00.7

**Comment by pyscripter** [comment]
Please try again with the current state of the repo.

**Comment by pyscripter** [comment]
TNodeCheckState was introduced in Delphi 11.
Fixed.
