### ISSUE TITLE
A little problem Delphi 10.2.3

### ISSUE THREAD

**Issue by hosekb** [pyscripter/python4delphi#436]
In Delphi 10.2.3 little problem with new version
[dcc32 Error] WrapDelphi.pas(1468): E2250 There is no overloaded version of 'RttiCall' that can be called with these arguments
[dcc32 Error] WrapDelphi.pas(1516): E2250 There is no overloaded version of 'RttiCall' that can be called with these arguments
[dcc32 Error] WrapDelphi.pas(4047): E2250 There is no overloaded version of 'RttiCall' that can be called with these arguments
[dcc32 Error] WrapDelphi.pas(4092): E2250 There is no overloaded version of 'RttiCall' that can be called with these arguments
[dcc32 Fatal Error] Python_D.dpk(57): F2063 Could not compile used unit 'WrapDelphi.pas'

regards
Bohous

**Comment by pyscripter** [comment]
Please test again and confirm it is fixed.

**Comment by hosekb** [comment]
All is OK.

Regards

Bohous
