### ISSUE TITLE
patch for PyCFunction_NewEx?

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#44]
```
PyCFunction_NewEx: function(md:PPyMethodDef;self, ob:PPyObject):PPyObject; cdecl;
```
I don't know engine part. pls tell, what patch with _NewEx does? what works not ok w/out this patch?

**Comment by pyscripter** [comment]
+.. c:function:: PyObject* PyCFunction_NewEx(PyMethodDef *ml, PyObject *self, PyObject *module)
+
+   Create a new :c:type:`PyCFunctionObject` object.  *ml* points to a
+   :c:type:`PyMethodDef` describing the C function that will be
+   called.  *self* is a :c:type:`PyObject` that will be passed as
+   *self* to the C function, and can be *NULL*.  *module* will be set
+   as the :attr:`__module__` attribute of the :c:type:`PyCFunction`
+   object and can also be *NULL*.
+
+.. c:function:: PyObject* PyCFunction_New(PyMethodDef *ml, PyObject *self)
+
+   A variant of :c:func:`PyCFunction_NewEx` that takes *ml* and
+   *self*, but sets the :attr:`__module__` attribute of the resulting
+   :c:type:`PyCFunctionObject` to *NULL*.

**Comment by Alexey-T** [comment]
thus NewEx function not needed for P4D? Why did you add it to PythonEngine then.

**Comment by pyscripter** [comment]
I now remember.  PyCFunction_New was not exported in Python 3.4.  It appears this has been fixed in 3.6 and later.

See  https://bugs.python.org/issue21354

**Comment by Alexey-T** [comment]
and why _NewEx function was added here?

**Comment by pyscripter** [comment]
So the change is needed to support certain versions of Python 3.4, 3.5

**Comment by pyscripter** [comment]
The lack of documentation is another Python bug:
https://bugs.python.org/issue16776

**Comment by Alexey-T** [comment]
Ok, will add in my fork too.
