### ISSUE TITLE
Running Demos from Delphi-12

### ISSUE THREAD

**Issue by Andyk1234** [pyscripter/python4delphi#446]
Installed the latest Delphi 12 and P4D and have issues with the demo projects.

Python version is 3.10.2

The simple ones, Demo1-5 seem to work

Demo06.exe raised exception class EPyAttributeError with message 'AttributeError: U'.

Demo 7-9 produces
Project Demo07.exe raised exception class EPyAttributeError with message 'AttributeError: Unknown attribute "OffsetBy"'.

Demo11

Project ThrdDemo.exe raised exception class EPyOverflowError with message 'OverflowError: Python int too large to convert to C long'.

I gave up after that.

**Comment by pyscripter** [comment]
There was a change that had affected some of the older demos.
This is now fixed.  Please try again.
