### ISSUE TITLE
Need help, change sys.stdout encoding to utf8 on Win32

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#46]
In CudaText with python4d fork, user sees sys.stdout encoding as CP1251 (rus).
We need to change it to utf8.
How to do it automatically always on start?
I found
```
import sys
sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf-8', buffering=1)
```
https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3

how to use it in python4d?

**Comment by pyscripter** [comment]
Are you using IO redirection?  Which version of Python?
Internally P4D keeps output as Unicode strings.  Use UnicodeIO:= True and the events OnSendUniData OnReceiveUnidata for input output.

**Comment by Alexey-T** [comment]
Yes, io redirection component. SendUniData. Python 3.5. 
And still need to set sys.stdout enc to utf8 to not use Win10 rus cp

**Comment by pyscripter** [comment]
What do you mean:
You execute script:
```
s = "漢語"
print(s)

```
python writes unicode.
p4d receives unicode.

**Comment by Alexey-T** [comment]
P4d receives Unicode only if sys.stdout encoding is utf8.

**Comment by pyscripter** [comment]
It shouldn't.  If you look at DoRedirectIO  stdout.write calls pyio_write.
in pyio_write
```
            if PyUnicode_Check(a1) then
              IO.Write(PyUnicode_AsWideString(a1))
```
and in TPythonInputOutput.Write
```
     if UnicodeIO then  
        SendUniData( FLine_Buffer )
``` 
So no conversion should happen when you print Unicode strings in Python with P4D redirection.  This works as expected in PyScripter.  The sys.stdout.encoding (which by the way is set to None by P4D) is not used with Unicode strings which is the default string type in Python 3.x.

If you write to a console (which you then redirect) this of course is not the case.
