### ISSUE TITLE
How to specify the path to Python libraries?

### ISSUE THREAD

**Issue by Uefi1** [pyscripter/python4delphi#460]
Hello, for example, I know how to specify the path to python.dll:
PythonEngine.DllPath := ExtractFilePath(ParamStr(0))+'\Python';
PythonEngine.DllName := 'python311.dll';

How can I specify the path to a library or several libraries ?
it should be something like:
PythonEngine.LibraryPath:='C:\PythonLibs';
PythonEngine.LibPath:='C:\Lib';

?????????????????????????????????????????????????????????????????

**Comment by pyscripter** [comment]
Please use the support forum for questions.

**Comment by Uefi1** [comment]
> Please use the support forum for questions.

I tried to use the forum you recommended, there are trolls there and they don’t answer a single question properly, so I’ll ask questions here

**Comment by pyscripter** [comment]
You can execute python code (for instance in InitScript) to modify the python path. e.g.

```python 
import sys
sys.path += [desiredpath]
```

**Comment by Uefi1** [comment]
> There is also an event OnPathInitialization you can use if your pyhon version is registered,

Thank you so much for this library and your help! The library is super, I hope in new versions you will also add an explicit indication to the library paths?
