### ISSUE TITLE
Run the .py file immediately with parameters

### ISSUE THREAD

**Issue by Uefi1** [pyscripter/python4delphi#461]
Hello, please tell me how to correctly run a ready-made .py file via Python4Delphi if the file itself requires launching with some parameters, for example -h -u -i -o for example, I would like to do something like:
```
function ExecPythonFile(const Filename,Params:string):string;
var
FGILState: PyGILstate_STATE;
begin
Result := '';
FGILState := PythonEngine.PyGILState_Ensure;
try
PythonEngine.ExecFile(Filename, params); //????
finally
PythonEngine.PyGILState_Release(FGILState);
end;
end;

procedure TForm1.Button1Click(Sender: TObject);
var
s:string;
begin
ExecPythonFile(ExtractFilePath(ParamStr(0))+'pyscript\main.py', ' --help');
end;
```
And usually I run this file like this:
`python main.py --help`

**Comment by pyscripter** [comment]
Python stores command line parameters in sys.argv (list object).   You can manipulate sys.argv before running the file.

And PLEASE stop using the Issue Tracker for questions.

**Comment by Uefi1** [comment]
Issue Tracker is on Github and was created to ask questions, what is the problem?

**Comment by pyscripter** [comment]
> was created to ask questions

No.  The issue tracker is for reporting bugs.  PLEASE don't use it to ask questions.

**Comment by Uefi1** [comment]
> No. The issue tracker is for reporting bugs. PLEASE don't use it to ask questions.
Sorry, I don't have many questions, just a couple of questions.

**Comment by Uefi1** [comment]
It’s a little unclear how it goes like this ?:

```
function ExecPythonFile(const Filename:string;params:string):string;
var
FGILState: PyGILstate_STATE;
begin
Result := '';
FGILState := PythonEngine.PyGILState_Ensure;
try
PythonEngine.PySys_SetArgv(0, '-help');
PythonEngine.ExecFile(Filename);
finally
PythonEngine.PyGILState_Release(FGILState);
end;
end;
```

**Comment by Uefi1** [comment]
I'm getting errors for some reason 

`PythonEngine.PySys_SetArgv(0, PPWideChar('-in -o -m'));`

Invalid typecast

**Comment by Uefi1** [comment]
Will this be right ?

```
function ExecPythonFile(const Filename:string;params:string):string;
var
args:PPWideChar;
FGILState: PyGILstate_STATE;
begin
Result := '';
args:=@params;
FGILState := PythonEngine.PyGILState_Ensure;
try
PythonEngine.PySys_SetArgv(0, args);
PythonEngine.ExecFile(Filename);
finally
PythonEngine.PyGILState_Release(FGILState);
end;
end;
```

ExecPythonFile(ExtractFilePath(ParamStr(0))+'pyscript\main.py, '-i -o -threads 10')

**Comment by Uefi1** [comment]
No, it doesn’t work, and if only the first one works, the rest are ignored =(
I don’t quite understand how to do it
