### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by hosekb** [pyscripter/python4delphi#466]
Hi,
in Delphi 10.2.3:
[dcc64 Error] PythonEngine.pas(4701): E2003 Undeclared identifier: 'ExcludeLastEmpty'
Paths := FPythonPath.Split([PathSep], TStringSplitOptions.ExcludeLastEmpty);

Sincerely
Bohous

**Comment by pyscripter** [comment]
Thanks.   Could you please see how TStringSplitOptions is defined in Delphi 10?
