### ISSUE TITLE
[dcc64 fatal error] PythonVcl.dpk: F2084 Internal Error on RAD Studio 12.1

### ISSUE THREAD

**Issue by oyefer** [pyscripter/python4delphi#468]
The compilation was normal under 12.0 with patch1, but 12.1 encountered the following error:
![p4d_error](https://github.com/pyscripter/python4delphi/assets/7107672/8c9d1bdf-f4ca-4c04-98e1-1dee392d4370)

**Comment by pyscripter** [comment]
Which version of P4D are you using? (Getit, this repo or the Embarcadero repo)

**Comment by oyefer** [comment]
RAD Studio 12.1 29.0.51961.7529 Update 1, not beta version.
I'm using this repo.

**Comment by pyscripter** [comment]
Cannot reproduced with Delphi 12.1.
Following the installation instructions, I opened the group project, selected "Build All" and it all compiled without issues.

**Comment by oyefer** [comment]
By default, the target platform is win32, and there are really no errors at compile time. When the target platform is set to win64, there is no error in compiling Python290.bpl, which occurs when compiling PythonVcl290.bpl.
![image](https://github.com/pyscripter/python4delphi/assets/7107672/1080342c-2108-4981-b649-9619190b858f)

**Comment by pyscripter** [comment]
I see.   I can also replicate the error.  It does compile fine in Delphi 11.   Clearly this is a Delphi compiler bug and not a P4D one.

Reported as https://embt.atlassian.net/servicedesk/customer/portal/1/RSS-446.

**Comment by pyscripter** [comment]
This is fixed in https://blogs.embarcadero.com/rad-studio-12-1-athens-patch-1-available/
