### ISSUE TITLE
thread safe?

### ISSUE THREAD

**Issue by kattunga** [pyscripter/python4delphi#47]
Hi,

I'm interested in use python4delphi in a multi threaded environment, more specifically in an Indy TCP Server.
I need to execute python scripts inside threads in a high concurrent environment.

Looking at source code, I found that gPythonEngine is a global variable so obviously I can't have more that one PythonEngine at the same time in my application.

Is TPythonEngine thread safe?
If yes, how should be the right way to implement python4delphi in a threaded application?

Regards

**Comment by pyscripter** [comment]
Look at demo 33 regarding using threads with P4D

**Comment by kattunga** [comment]
In that example you are executing custom TPythonThreads.
In and Indy TCP server I am inside a standard Delphi Thread.
When I try to change the demo 33 to execute Pyhton script inside a standard Thread I get and access violation.

**Comment by pyscripter** [comment]
TPythonThread is a standard Delphi thread. It inherits from TThread and
therefore is a native Windows thread.  What it adds to TThread is the
management of acquiring and releasing the GIL (Python Global interpreter
lock) necessary for avoiding the exceptions you experienced.

**Comment by kattunga** [comment]
Ok, so I understand, i should need to write the management of acquiring and releasing the GIL inside the indy thread.
I'll investigate TPythonThread code and I'll to try to wrap that logic inside a function so I can execute code in a thread safe way.

**Comment by pyscripter** [comment]
Great!
