### ISSUE TITLE
Access violation: Open Tk GUI and running a python function without closing the GUI

### ISSUE THREAD

**Issue by idanmiara** [pyscripter/python4delphi#474]
Hi,

Is it possible to open a Python GUI (created with `tk` for instance) and then run a python function without closing the tk window?
I've created a project to demonstrate the issue here:
https://github.com/idanmiara/pyscripter_test
in order to demonstrate the issue please run the project then click the buttons in the following order:

`init`, `py load`, `py1` - this works
`init`, `py load`, `py5`, close the tk window, `py1` - this works
`init`, `py load`, `py5`, `py1` - this would cause `Access violation`.

(there are some other buttons there which are not related to this question)

Thanks!

**Comment by pyscripter** [comment]
When your run the tkinter script the ExecStrings does not exit until you close the tkinter window.   The tkinter mainloop somehow keeps the Delphi message loop alive,  and when you try to execute py1, this is effectively a recursive call to ExecStrings and does not work.

To make the above work, you need to run all scripts in threads using for instance ThreadPythonExec.  See https://github.com/pyscripter/python4delphi/wiki/PythonThreads for more details.

**Comment by pyscripter** [comment]
Did you follow the instructions?

> Preparation
> When PythonEngine loads the python DLL, the main thread holds the GIL. Before you can run python code in threads you must release the GIL. TPythonThread has two class methods that allow you to release the GIL and then acquire back.
> 
>     class procedure Py_Begin_Allow_Threads;
>     class procedure Py_End_Allow_Threads;
> Py_Begin_Allow_Threads saves the thread state and releases the GIL, whilst Py_End_Allow_Threads tries to get hold of GIL and restore the previous thread state. You should only call Py_Begin_Allow_Threads if you alread hold the GIL. Otherwise a deadlock will occur.
> 
> You should call Py_Begin_Allow_Threads in your main thread, after the python DLL was loaded, for example in your FormCreate event handler. Also you can call Py_End_Allow_Threads when you are done executing python in threads.

**Comment by idanmiara** [comment]
> Did you follow the instructions?

Oh, Thanks, I misread that section before. 
Now it works and I can open the code that opens a tk window multiple times and also run other functions. 
but for some reason if I open a tk window, close it and reopen it (run the code again) then it crashes.
any pointers?
