### ISSUE TITLE
"brcc32" exited with code 1. 

### ISSUE THREAD

**Issue by guistory** [pyscripter/python4delphi#48]
when i run your P4D demos found "brcc32" exited with code 1. 
win7+python3.6

**Comment by pyscripter** [comment]
Which demos.   Is this a compilation issue?  Could you please provide some more details?

**Comment by guistory** [comment]
my  ide is delphi xe7up1
i don't know c++builder and FPC, 
 in those demos ：
1-9 is works ，
10 because i don't install TTable don't know ，
**6 and 10-firedac is found this error**
remaining demos is found “pythoninputoutput1.onsenddata has an incompatible parameter list” error

**Comment by pyscripter** [comment]
Not a P4D issue.  See 
https://wiert.me/2014/01/10/pre-build-trick-to-circumvent-brcc32-error-xxx-vrc1-error-creating-xxx-res-via-embarcadero-discussion-forums-stackoverflow/
You can delete the .res files to resolve the problem.

**Comment by pyscripter** [comment]
Which demo fails to compile with “pythoninputoutput1.onsenddata has an incompatible parameter list” error?
OnSendData is not used in the demos.

**Comment by guistory** [comment]
maybe demo2* were found onsenddata error, my pc is not here.

**Comment by guistory** [comment]
no .res file

**Comment by guistory** [comment]
brcc32 command line for "Demo10.vrc"
  c:\xe7up1\bin\cgrc.exe -c65001 "Demo10.vrc" -foDemo10.res 
[BRCC32 Error] "brcc32" exited with code 1.
Failed

**Comment by guistory** [comment]
D:\360安全浏览器下载\python4delphi-master (1)\python4delphi-master\PythonForDelp
hi\Demos\Demo10_FireDAC>  c:\xe7up1\bin\cgrc.exe -c65001 "Demo10.vrc" -foDemo10.
res
CodeGear Resource Compiler/Binder
Version 1.2.2 Copyright (c) 2008-2012 Embarcadero Technologies Inc.

Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Demo10.vrc(60) : error RC2135 : file not found: Demo10_Icon1.ico

D:\360安全浏览器下载\python4delphi-master (1)\python4delphi-master\PythonForDelp
hi\Demos\Demo10_FireDAC>

**Comment by guistory** [comment]
i found the way to resolve this error
delete .vrc .dproj .local files
it works but no mainicon

**Comment by guistory** [comment]
maybe win32 and win64 is diffrent
