### ISSUE TITLE
I used your component for UniGUI and it worked fine for a while, but...

### ISSUE THREAD

**Issue by mdavodnia** [pyscripter/python4delphi#492]
I used your component for UniGUI and it worked fine for a while, probably, but after I installed Delphi 12, the program stopped working and gave an error
I created a component like the VCL component for UniGUI
It worked fine and displayed the result of executing Python commands in the Uni editor, but I don't know what happened and now it doesn't work properly
Do you have any ideas?

**Comment by pyscripter** [comment]
> and gave an error

The info you provide insufficient to provide any help.

**Comment by mdavodnia** [comment]
hi,Thank you for your attention. 
create testcase and send For U

**Comment by mdavodnia** [comment]
1- I am Create Component For Use In Unigui(MDpyUni)
2-create test Case For Use In Unigui Prog(MDPythonEditor)
3-Run In Browser 
4-load dll -OK
5-Excute Python String Command And ocurrected Error
![1-setupPyUni_Component](https://github.com/user-attachments/assets/3d9792b7-03fe-4a09-8132-0f4aa02dfd16)
![2-SetDirUniSetup](https://github.com/user-attachments/assets/b658142d-0e25-44d0-942e-04badc8e6dba)
![4-On Run Uni Sample Error](https://github.com/user-attachments/assets/4cadd933-9dae-45ab-8dda-1469b10e79a5)
![Screenshot 2024-12-28 125705](https://github.com/user-attachments/assets/3631f0b6-50d6-4ef6-aa8f-422fc37888a9)

testcase link download:

https://filebin.net/2fh9o1r3h76olt91

**Comment by mdavodnia** [comment]
testcase link download:

https://filebin.net/2fh9o1r3h76olt91

**Comment by pyscripter** [comment]
The test case is not of much use to me since  I do not have UniGUI.   A standard and simple test project reproducing the error would be useful instead.  Also, you have not answered my questions:

- What is the error you get?
- Where exactly does the error occur? Is it in line 5100?  If that is the case the error has occurred before executing the script.
- Does your app still work when you compile with Delphi 11?

**Comment by mdavodnia** [comment]
error Get
--> Access violation at address 7AB23F95 in module 'python313.dll' (offset 243F95). Read of address 00000048.

yes Error on line 5099 and 5011 efect But the line does not appear the first time, the second time the command .ExecStrings('pythoncode') is executed, it gives an error.

Does your app still work when you compile with Delphi 11?
yes,on delphi 11 same 12 has error

**Comment by mdavodnia** [comment]
It seems that after running a Python command once, the dll gets locked and cannot be run again.

**Comment by pyscripter** [comment]
> has be OK,Tanks,Tanks

Could you please explain what you found?

**Comment by mdavodnia** [comment]
yes I comment From Line 9384 to 9396

  // Forbid printing for any other thread than the main one
(*  {$IFNDEF FPC}
  if GetCurrentThreadId <> MainThreadId then
    with GeTPythonEngine do
      begin
        if RedirectIO and (IO <> nil) and (IO.ClassName <> 'TPythonInputOutput') and not IO.DelayWrites then
          begin
            Result := GeTPythonEngine.ReturnNone;
            Exit;
          end;
      end;
  {$ENDIF}
  *)

**Comment by pyscripter** [comment]
How is using Delphi 11 makes a difference?

The code you deleted is fine.  If you are printing from threads you should either:
1. Use a TPythonInputOuput descendent like TPythonGUIInputOutput with DelayWrites set to True
2. or Use a TPythonInputOutput and handle the OnSendUniData in a thread safe manner.

**Comment by pyscripter** [comment]
Also if you are running Python from multiple threads you should read https://github.com/pyscripter/python4delphi/wiki/PythonThreads very carefully.
