### ISSUE TITLE
Pls help with redundant text on Python output event

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#51]
I see problem in CudaText, don't know how to see in PyScripter. maybe you can help even here?

I have OnSendData, OnSendUniData
```
procedure TfmMain.PythonIOSendData(Sender: TObject; const Data: AnsiString);
begin
  MsgLogConsole(Data);
end;

procedure TfmMain.PythonIOSendUniData(Sender: TObject;
  const Data: UnicodeString);
begin
  MsgLogConsole(UTF8Encode(Data));
end;
```
then MsgLogConsole does output to ATSynedit editor.
On starting CudaText, i see broken output lines for started plugins:
```
Init: cuda_project_manInit: cuda_tst_coInit: cuda_sess_managerInit: cuda_brackets_hiliteInit: cuda_lint
Init: cuda_project_manInit: cuda_tst_coInit: cuda_sess_managerInit: cuda_brackets_hilite
Init: cuda_project_manInit: cuda_tst_coInit: cuda_sess_manager
Init: cuda_project_manInit: cuda_tst_co
Init: cuda_project_man
Init: cuda_tabs_list
Startup: total: 423ms, including plugins: 68ms
```

here are 4 first lines are broken: then have other lines added.

**Comment by Alexey-T** [comment]
Func MsgLogConsole is slow- it's reason (it makes python calls and python plugin gets text from it).

**Comment by pyscripter** [comment]
Why do you have both OnSendData and OnSendUniData?  Only one is used depending on UnicodeIO.  Do you set DelayWrites to False and RawOutput to True?
In relation to the missing text (if I understand well) cannot you debug and see at which point is the missing text lost?
To increase speed you may want to do  some buffering either on the python side or on the cuda side or both.

**Comment by Alexey-T** [comment]
Thanks, added buffer string list  for SendUniData.
