### ISSUE TITLE
Issue with demo 06 in Lazarus

### ISSUE THREAD

**Issue by zbyna** [pyscripter/python4delphi#52]
Hi,
thanks for great project.
I am testing this in Lazarus:
```
Lazarus version: 1.7
Lazarus svn revision: 54250M
Lazarus build date: 2018/05/11
Lazarus was compiled for i386-win32 on win7 64bit
Lazarus was compiled with fpc 3.1.1
```
Seems like 
```pascal
function  PyPoint_OffsetBy(self, args : PPyObject) : PPyObject; cdecl; 
```
is not properly registered and python code:
```python
p.OffsetBy( 5, 5 )
```
causes Access violation error.
I am able to run demo01 without problem and using embedded distribution downloaded from python.org.
For details please see:  
[![Bug](https://i.imgur.com/rW69agp.jpg)](//youtu.be/g5SPky7-Nfs "Bug")

**Comment by zbyna** [comment]
Py_FindMethod is depreciated in Python 3.x
```pascal
Result := Py_FindMethod( MethodsByName('PythonType1'), obj, key);
```
It is needed to replace with:
```pascal
Result:=PyObject_GenericGetAttr(obj,PyString_FromString('OffsetBy'));
 ```
The demo  has some memory leaks but above mentioned fixed python code behaviour.

**Comment by pyscripter** [comment]
Thanks.  I will have a look.

**Comment by pyscripter** [comment]
I have implemented your suggestion.  Thx.
