### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#56]
my repo has support for FreeBsd. it is in pythonengine.pas
https://github.com/alexey-t/python-for-lazarus

- replaced "ifdef linux" to "ifdef unix" in n places
- look at list at "ifdef freebsd"

**Comment by pyscripter** [comment]
Could you please submit a PR?

**Comment by Alexey-T** [comment]
I don’t use Rad Studio today, sorry

**Comment by pyscripter** [comment]
What using Rad Studio has to do with a Github PR?

**Comment by Alexey-T** [comment]
Before giving PR, I must test the final result

You can somehow do PR from my repo too
