### ISSUE TITLE
float divicde by zero exception when import pandas

### ISSUE THREAD

**Issue by chinshou** [pyscripter/python4delphi#57]
when execute import pandas , the python4 delphi will raise float divide by zero exception. I attached a patch to address this issue
[0001-fix-divide-by-zero-error-when-import-pandas.zip](https://github.com/pyscripter/python4delphi/files/2259468/0001-fix-divide-by-zero-error-when-import-pandas.zip)

**Comment by pyscripter** [comment]
Use the provided function MaskFPUExceptions instead.

**Comment by ReinierNL** [comment]
I have / had the same problem as chinshou, but with scipy in stead of pandas, but the MaskFPUExceptions solution didn't work for me.
Fortunately, his solution, to call SetExceptionMask(exAllArithmeticExceptions), DOES work for me.

(with Python 3.6 and Win64)

**Comment by pyscripter** [comment]
Reimplemented MaskFPUExceptions.  You still have to manually call it.  It is also a good idea to call it before running scripts since various DLLs may reset it to unwanted values.
