### ISSUE TITLE
How to publish with virtualenv?

### ISSUE THREAD

**Issue by dtamade** [pyscripter/python4delphi#67]
python3.7.
It seems unable to load Lib

Ask for advice

**Comment by dtamade** [comment]
sys.path.append({path})
Is that so?

**Comment by pyscripter** [comment]
You need to:
- set AutoLoad to False
- Call SetPythonHome() with the directory of your virtualenv.
- Then call LoadDLL

Alternatively you can set the Environment variable PYTHONHOME to point to the directory of the virtualenv.
