### ISSUE TITLE
Script working now not working

### ISSUE THREAD

**Issue by mcinquino** [pyscripter/python4delphi#70]
Hello,

I hope I am in the right place for this question. I apologize if I should be asking this somewhere else. I did post this question on the general Lazarus forum but did not get any feedback. 

I am using Python for Lazarus in an application to communicate with a few different lab instruments. 

I have a Lazarus application that was running well using the NI-Visa library for python. It suddenly stopped working and is now throwing an error:

AttributeError: module 'visa' has no attribute 'ResourceManager'

The odd part is that the same python code runs fine from IDLE or python directly? I am struggling to find any information on how P4L or P4D interacts with python and where this problem could be coming from. I would think they would use the same python module? 

I did get some good feedback from python visa forum but I think the visa and python side check out as ok because it is running in python itself. This seems to be something specific to the Lazarus side?

Simple python script that returns error:
import visa

from ThorlabsPM100 import ThorlabsPM100
rm = visa.ResourceManager()

Other python scripts seem to run fine from the same Lazarus application. 

Any information would be greatly appreciated.

**Comment by pyscripter** [comment]
Could it be that it is importing a wrong version of the visa python module?
Try print(dir(visa)) to see the members of visa.

**Comment by mcinquino** [comment]
print(dir(visa)) returns

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'absolute_import', 'division', 'print_function', 'unicode_literals']

**Comment by mcinquino** [comment]
I just noticed this behavior as well and I am not sure if it a clue.  If I run import visa from Lazarus in debug mode I get a 'External:SIGFPE' error the first time I run it. If I select ok then run/continue I get a Floating point division by zero error. If I select OK then run import visa again it seems to run it? I can accomplish the print(dir(visa)) command but it then fails once I try to rm = visa.ResourceManager()

**Comment by pyscripter** [comment]
See #69 and apply the same (similar) solution.

**Comment by mcinquino** [comment]
This is how I am understanding it should be used(see below)? It needs a boolean passed to it. I am not understanding what should be passed here? I tried both true and false and got the same errors as above. 

procedure TForm1.Button14Click(Sender: TObject);
begin
  MaskFPUExceptions(?);
  PythonEngine1.ExecStrings(Memo6.Lines);
end;

**Comment by pyscripter** [comment]
MaskFPUExceptions(True);

**Comment by mcinquino** [comment]
When you say Python Library, is this in Lazarus or in Python? If it is in python I am essentially doing that with the code I show above. I have narrowed the code down to just loading the library. Memo6.Lines has in it - "import visa" (in python) so it is being run directly before. 

If it needs to run before the lazarus python library gets loaded I am not sure how to do that?



When I run print(dir(visa)) from python shell I get this return:

['Error', 'InvalidBinaryFormat', 'InvalidSession', 'LibraryError', 'OSNotSupported', 'Resource', 'ResourceManager', 'UnknownHandler', 'VisaIOError', 'VisaIOWarning', 'VisaTypeError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'absolute_import', 'constants', 'division', 'log_to_screen', 'logger', 'print_function', 'unicode_literals', 'visa_info', 'visa_main', 'visa_shell']

When I run it from lazarus app I get this return:

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'absolute_import', 'division', 'print_function', 'unicode_literals']

Shouldn't I get all the visa_* in both?

**Comment by pyscripter** [comment]
By Python library I wasI referring to the python dll.  You can call MaskFPUException in the OnBeforeLoad event handler.

You should get the same behaviour in stand-alone and embedded python.
Try the following in both:
```

import sys
print(sys.path)
```

**Comment by mcinquino** [comment]
(I ran this code to get a easier to read format)
import sys
type(sys.path)
for path in sys.path:
    print(path)

In Python Shell I get: 

C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\Lib\idlelib
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\Lib\site-packages
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\Lib
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\DLLs
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\python37.zip
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\win32
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\win32\lib
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\Pythonwin

From Lazarus I get:

C:\Users\mcinquino\AppData\Local\Programs\Python\Python37
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\Lib\site-packages
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\Lib
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\DLLs
C:\Users\mcinquino\Desktop\Lazarus HMI
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\python37.zip
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\win32
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\win32\lib
C:\Users\mcinquino\AppData\Local\Programs\Python\Python37\lib\site-packages\Pythonwin

**Comment by pyscripter** [comment]
It seems to be OK.

**Comment by mcinquino** [comment]
I placed MaskFPUExceptions(True); in the OnBeforeLoad event of my PythonEngine1. Still get the same errors. 

Should the dir results from both python shell and lazarus have the same 'visa_info', 'visa_main', 'visa_shell' ?

**Comment by pyscripter** [comment]
Yes.

**Comment by mcinquino** [comment]
Could this be the underlying problem? Is there a way for me to force them to be the same?

**Comment by pyscripter** [comment]
This is the symptom not the problem.
Do you still get SIGFPE after using MaskFPUExceptions?

**Comment by Alexey-T** [comment]
I think it’s not problem of pascal code. It is python level. So it is wrong python code , maybe old version of Visa in some dir. close this.
