### ISSUE TITLE
fpc demo25  error

### ISSUE THREAD

**Issue by liuzg2** [pyscripter/python4delphi#73]
fpc demo25  error

test integer

var
  a, b, c,x : Variant;
  big : Int64;
begin
  // initialize the operands
  a := VarPythonCreate(2);
  Assert(VarIsPython(a));
  Assert(VarIsPythonNumber(a));
  Assert(VarIsPythonInteger(a));
  x:='5';
  showmessage(string(a) );
   Assert( strtoint(a)= 2);

  b := VarPythonCreate(3);
  Assert(VarIsPython(b));
  Assert(VarIsPythonNumber(b));
  Assert(VarIsPythonInteger(b));
  Assert(integer(b) = 3);      
not support  integer(a)  type cast . only  strtoint(a)

**Comment by pyscripter** [comment]
This is known and documented and due to an Fpc bug.  See https://github.com/pyscripter/python4delphi/wiki/LazarusCompatibility
