### ISSUE TITLE
ImportError: cannot import name

### ISSUE THREAD

**Issue by liuzg2** [pyscripter/python4delphi#74]
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: cannot import name 'Dialog' from 'spam' (unknown location)

how to set   to find by  program

**Comment by liuzg2** [comment]
{$I Definition.Inc}

unit WrapDelphiDialogs;

interface

uses
  Classes, SysUtils, PythonEngine, WrapDelphi, WrapDelphiClasses,
  WrapDelphiControls, Windows, Dialogs, TypInfo;

type




  TPyDelphiOpenDialog = class (TPyDelphiComponent)
  private
    function  GetDelphiObject: TOpenDialog;
    procedure SetDelphiObject(const Value: TOpenDialog);
  protected
    // Property Getters
    function Get_filename( AContext : Pointer) : PPyObject; cdecl;
   // function Get_PageControl( AContext : Pointer) : PPyObject; cdecl;
    // Property Setters
   // function Set_PageControl( AValue : PPyObject; AContext : Pointer) : integer; cdecl;
    function Get_Execute( AContext : Pointer) : PPyObject; cdecl;
  public
    class function  DelphiObjectClass : TClass; override;
    class procedure RegisterGetSets( PythonType : TPythonType ); override;
    // Properties
    property DelphiObject: TOpenDialog read GetDelphiObject write SetDelphiObject;
  end;


implementation

uses
  WrapDelphiTypes ;

{ Register the wrappers, the globals and the constants }
type
  TDialogRegistration = class(TRegisteredUnit)
  public
    function Name : String; override;
    procedure RegisterWrappers(APyDelphiWrapper : TPyDelphiWrapper); override;
    procedure DefineVars(APyDelphiWrapper : TPyDelphiWrapper); override;
  end;

{ TComCtrlsRegistration }

procedure TDialogRegistration.DefineVars(APyDelphiWrapper: TPyDelphiWrapper);
begin
  inherited;
end;

function TDialogRegistration.Name: String;
begin
  Result := 'Dialog';
end;

procedure TDialogRegistration.RegisterWrappers(APyDelphiWrapper: TPyDelphiWrapper);
begin
  inherited;
 // {$IFNDEF FPC}
 // APyDelphiWrapper.RegisterDelphiWrapper(TPyDelphiDateTimePicker);
 // {$ENDIF FPC}
  APyDelphiWrapper.RegisterDelphiWrapper(TPyDelphiOpenDialog);
 // APyDelphiWrapper.RegisterDelphiWrapper(TPyDelphiTabSheet);

 // APyDelphiWrapper.EventHandlers.RegisterHandler(TTabChangingEventHandler);
end;


{ TPyDelphiTabSheet }

class function TPyDelphiOpenDialog.DelphiObjectClass: TClass;
begin
  Result := TOpenDialog;
end;

function TPyDelphiOpenDialog.GetDelphiObject: TOpenDialog;
begin
  Result := TOpenDialog(inherited DelphiObject);
end;

 function TPyDelphiOpenDialog.get_Execute( AContext : Pointer) : PPyObject;
 begin

 with GetPythonEngine do begin
    Adjust(@Self);
    Result := VariantAsPyObject(DelphiObject.Execute());
  end;
 end;

function TPyDelphiOpenDialog.Get_filename(AContext: Pointer): PPyObject;
begin
  with GetPythonEngine do begin
    Adjust(@Self);
    Result := VariantAsPyObject(DelphiObject.FileName);
  end;
end;


class procedure TPyDelphiOpenDialog.RegisterGetSets(PythonType: TPythonType);
begin
  inherited;
  PythonType.AddGetSet('FileName', @TPyDelphiOpenDialog.Get_filename, nil,
        '', nil);
  //PythonType.AddGetSet('PageControl', @TPyDelphiTabSheet.Get_PageControl, @TPyDelphiTabSheet.Set_PageControl,
  //      'Indicates the page control object that contains the tab sheet.', nil);
end;

procedure TPyDelphiOpenDialog.SetDelphiObject(const Value: TOpenDialog);
begin
  inherited DelphiObject := Value;
end;



initialization
  RegisteredUnits.Add( TDialogRegistration.Create );
  //{$IFNDEF FPC}
 // Classes.RegisterClasses([TDateTimePicker]);
 // {$ENDIF FPC}
end.

**Comment by pyscripter** [comment]
I have added a [new wrapper](https://github.com/pyscripter/python4delphi/blob/master/PythonForDelphi/Components/Sources/Core/WrapDelphiDialogs.pas) based on your example and updated Demo 31 to show you how to use the wrapper.

i.e.  

```
from spam import OpenDialog
    def testOpenDialog(self):
        print("OpenDialog test:")
        open_dialog = CreateComponent("TOpenDialog", None)
        if open_dialog.Execute():
            print("FileName:", open_dialog.FileName)
        open_dialog.Free()
```
