### ISSUE TITLE
AttributeError: 'Component' object has no attribute 'Parent'

### ISSUE THREAD

**Issue by liuzg2** [pyscripter/python4delphi#75]
from spam import  MainForm, CreateComponent, Application,Screen, mrOk, Form, Button, CheckBox, caFree
from spam import Point, Monitor, DrawGrid, gdSelected, clBlue, ssCtrl, PageControl, TabSheet
   def createtab(self):
       P1 = TabSheet(MainForm)------------------?? how to create a class   ?TabSheet(MainForm)? 
                                                                                 CreateComponent('TabSheet', MainForm)??
                                                                                where is Keyword "TabSheet"  in   sourcecode
       P1.PageControl = MainForm.mainpage
       P1.Caption = "Page 1"
 
       MainForm.mainpage.ActivePageIndex = P1.TabIndex
       LB = CreateComponent('TEdit', MainForm)     
        LB.Parent = P1                         ------------------delphi  10.3  AttributeError: 
                                                                                           'Component' object has no attribute 
                                                                                                         'Parent'
       LB.Name = "Pxxxage1"

**Comment by pyscripter** [comment]
Please quote your code to make it readable and maintain whitespace (<> on GitHub editor).

TabSheet is exported by the wrapper (TTabSheet without the first T).
You can create wrapped components either by:

```
from spam import CreateComponent, Tabsheet
CreateComponent("TTabsheet", Owner)
```
or by
`TabSheet(Owner)`

Without the full source code I cannot tell why Parent failed.
Study the python code in Demo 31 to see how it is done.
