### ISSUE TITLE
Demo29 with module problem

### ISSUE THREAD

**Issue by wesleybobato** [pyscripter/python4delphi#79]
I have a problem in demo29, I can compile but I get an error I could not find any answers can you help me?

![demo29](https://user-images.githubusercontent.com/29354801/60630915-ee680c00-9dd2-11e9-89b3-fa0be31467ce.png)

Thank you.

**Comment by pyscripter** [comment]
Are you using python 3.x?
Have a look at https://stackoverflow.com/questions/11914472/stringio-in-python3

**Comment by wesleybobato** [comment]
Thanks for your response, please wait for feedback to close, thank you :)

I searched google and now I get an error in Delphi

Look at my code, can you help me again?

import
from PIL import Image

def ProcessImage (data):
   stream = io.BytesIO (date)
   im = Image.open (stream)
   new_im = im.rotate (90)
   new_im.format = im.format
   return new_im
  
def ImageToString (image):
   stream = io.BytesIO ()
   image.save (stream, image.format)
   return stream.getvalue ()

![ImageWin](https://user-images.githubusercontent.com/29354801/60689973-a8c24680-9e99-11e9-8d48-caa5a6e62c9d.png)

**Comment by pyscripter** [comment]
This is not an error related to P4D but rather an issue with your python installation and code.
I am not an expert on Image Processing but it appears that ImageWin is a module of Pillow (PIL fork).  Try to run this code in the standard python interpreter and see whether it reports the same error.
