### ISSUE TITLE
Support virtual environments

### ISSUE THREAD

**Issue by wooolly** [pyscripter/python4delphi#82]
I can't figure out how to set up Python4Delphi to use virtual python environments which have been created using the 'venv' library which comes pre-bundled with the latest versions of Python. I've tried creating a custom TPythonVersion and assigning it to the Python Engine, but this doesn't seem to completely work as importing a library specific to that environment doesn't work. It's as if still points at the libraries of the global installation version that the virtual environment was created from.

I suggest to improve support for Virtual Environments.

**Comment by pyscripter** [comment]
I would very much like to see this fixed but it is not easy.   
See for instance https://bugs.python.org/issue35706.

Virtualevn works fine in place of venv.
 Python 3.8 provides for finer control of the initialization of Python, but it would take quite a bit of work to implement that and would not work with earlier versions of Python.   I might do this at some later point.

**Comment by pyscripter** [comment]
I found a way to support venv.  Look at the latest commit.  There is a new published property  VenvPythonExe that you should set to the full path to the python.exe in the venv environment.

Alternatively you can use PythonVersions e.g.
SetPythonEngine AutoLoad to false.

```
Var
  PyVersion : TPythonVersion;
…
    PythonVersionFromPath('F:\Python\Python38-32-venv', PyVersion);
    PyVersion.AssignTo(PythonEngine);
    PythonEngine.LoadDll;
```

**Comment by wooolly** [comment]
Thanks for adding support for virtual environments, I tested with 3.7 and it worked nicely. Sadly, it doesn't seem to work with 3.6 and stops with a system exception. Is it possible to support older versions too? I'm happy with 3.7 support.

**Comment by pyscripter** [comment]
The venv module is rather new and has changed since it was first introduced.  Now python 3.8 is out and it P4D works with python 3.8 venvs. So python 3.7 and 3.8 work fine.  I don't have much time for making sure this works with earlier versions.  In any case you can use virtualenv with older versions.

**Comment by wooolly** [comment]
Yeah no worries, having it work with older versions was a minor suggestion, thanks for the support of venv in the latest versions!
