### ISSUE TITLE
My fix for checking mmap() call result

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#83]
This fix helps to avoid crash, when in Lazarus I add on empty form: PythonEngine, PythonDelphiVar, link Var to Engine, and run this demo on Linux.

https://github.com/Alexey-T/Python-for-Lazarus/commit/e7de104439434a88e586af42dad78d7e2e66f68b

**Comment by Alexey-T** [comment]
I didn't do the PullReq because for that I need to compile your repo in Delphi: i don't have Delphi here

**Comment by pyscripter** [comment]
Changes committed.  Any idea why mmap fails at design time?  Does it fail when you run the program also?

**Comment by Alexey-T** [comment]
It failed at runtime, not design time. just empty form with Engine and Var components.
