### ISSUE TITLE
exception on loading example 04

### ISSUE THREAD

**Issue by ricardodarocha** [pyscripter/python4delphi#84]
I am looking the example 04 and when the application starts its gives me an exception

---------------------------
Application Error
---------------------------
Exception EPySyntaxError in module Project1.exe at 00211B0B.

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Python Dll: ", sys.version)? (line 2, offset 20): 'print "Python Dll: ", sys.version'.

---------------------------
OK   
---------------------------

I couldn't find this instruction in any file of the project.

**Comment by pyscripter** [comment]
If you are using python 3.x then you need to modify the python code. 
In python 3.x print is a function and not a statement and you need to have brackets.

So
print 2 
needs to be replaced with
print(2)

The demos were designed to work with python 2.x.
