### ISSUE TITLE
Need help for Python error: wrong char code outside of range [0..$10ffff]

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#85]
I use this fork
https://github.com/alexey-t/python-for-lazarus
In the folder demo_lazarus I have a demo, which shows the problem. I cannot test this on Delphi (no Delphi here, I use Linux Ubuntu 18.x x64, Python 3.7).

- i run the demo
- demo provides Py module "demo" with function "s1". So i test it.
- in demo console, i enter
```
import demo
=demo.s1()
```
and have this error.
![Screenshot from 2019-10-10 13-04-15](https://user-images.githubusercontent.com/4154978/66559948-ff0ce880-eb5e-11e9-8e00-18c9358fbda0.png)

This is from Unicode string with high values:
```
function Py_s1(Self, Args : PPyObject): PPyObject; cdecl;
const
  S0: string = 'begin.𠏽𠏽𠏽𠏽𠏽.end';
begin
  with GetPythonEngine do
    Result:= PyString_FromString(PChar(S0));
end;
```

Can you repro this on Delphi?

**Comment by pyscripter** [comment]
PyString_FromString is expecting an Ansichar,

```
function TPythonEngine.PyString_FromString( str: PAnsiChar): PPyObject;
var
  _text : UnicodeString;
begin
  if IsPython3000 then
  begin
    _text := UnicodeString(str);
    Result := PyUnicode_FromWideString(_text);
  end
  else
    Result := DLL_PyString_FromString(str);
end; 
```
What is the default string type?  What is the encoding of the source file?

𠏽 is U+203FD (two words. four bytes).   You can debug and see what _test is.
It would be better to call  PyUnicode_FromWideString directly with the correct UTF16 representation.




See also:
https://stackoverflow.com/questions/33459384/unicode-character-not-in-range-when-calling-locale-strxfrm

**Comment by Alexey-T** [comment]
>What is the default string type? What is the encoding of the source file?

- string type is utf8 encoded string 
- utf8, see the $codepage in that demo.

**Comment by Alexey-T** [comment]
In the engine there is code which converts unicodestring to Ucs4string. I guess it fails somehow..

**Comment by pyscripter** [comment]
```
function TPythonEngine.PyUnicode_FromWideString( const AString : UnicodeString) : PPyObject;
{$IFDEF LINUX}
var
  _ucs4Str : UCS4String;
{$ENDIF}
begin
{$IFDEF LINUX}
  // Note that Linux uses UCS4 strings, whereas it declares using UCS2 strings!!!
  _ucs4Str := WideStringToUCS4String(AString);
  Result := PyUnicode_FromWideChar( {PWideChar}(@_ucs4Str[0]), Length(AString) );
{$ELSE}
  Result := PyUnicode_FromWideChar( PWideChar(AString), Length(AString) );
{$ENDIF}
end;
```
Again you can debug and see the value of AString and ucs4Str.   This will tell you where it fails.

**Comment by pyscripter** [comment]
By the way PyScripter handles the printing of the character correctly.

**Comment by Alexey-T** [comment]
Will see it.

Did you test PyScripter to pass this char from Delphi code to python code?

**Comment by pyscripter** [comment]
In PyScripter everything is UTF16 (UnicodeString), so I do not get such conversions.

**Comment by Alexey-T** [comment]
But you will anyway go through Wide->UCS4 conversion, so need to test it.

**Comment by pyscripter** [comment]
In Windows Python expects UTF16. not UCS4.

**Comment by Alexey-T** [comment]
yes, right.

**Comment by pyscripter** [comment]
Pls let me know if the fault is with P4D (I doubt it).

**Comment by Alexey-T** [comment]
OMG

  // Note that Linux uses UCS4 strings, whereas it declares using UCS2 strings!!!
  _ucs4Str := WideStringToUCS4String(AString);
  Result := PyUnicode_FromWideChar( {PWideChar}(@_ucs4Str[0]), Length(AString) );

seems we need length of _ucs4str, as last  param. Coz for surrogate pair, this length is smaller than original len. will test

**Comment by pyscripter** [comment]
Yes, we should use the length of _ucs4Str.

**Comment by Alexey-T** [comment]
It was the reason, pls fix too
https://github.com/Alexey-T/Python-for-Lazarus/commit/70662b087b1ce5b200cb310df9577344578e0454

**Comment by Alexey-T** [comment]
Another fix 
https://github.com/Alexey-T/Python-for-Lazarus/commit/bcc92772b00f7f3331e4258ebe18d77e85837367

**Comment by pyscripter** [comment]
Are you sure about this last one???  The function expects the number of characters.
Also according to the documentation you can pass -1 for length in which case the length is calculated.

**Comment by Alexey-T** [comment]
I am sure about Lazarus version of widestringToUCS4string, it always adds 0 at end, and i saw crashes in PY if i dont do `-1`.

**Comment by pyscripter** [comment]
Yes, but length(_ucs4Str) should return the number of characters ignoring the trailing zero, which is what python expects.

**Comment by pyscripter** [comment]
Unless length does not work with UCS4 strings!  Need to check.

**Comment by Alexey-T** [comment]
Just see the WidestringToUCS4string in Delphi- does it add zero?

**Comment by Alexey-T** [comment]
I checked it in Laz, Len(ucs4Str) includes +1 for zero.

**Comment by pyscripter** [comment]
In Delphi UCS4 strings are dynamic null terminated strings just like UnicodeStrings and Ancistrings.

**Comment by pyscripter** [comment]
This sounds like a Lazarus bug.

**Comment by Alexey-T** [comment]
What does Delphi show?
Length(WideStringToUCS4String('')) ?

**Comment by pyscripter** [comment]
Very strange.  Delphi does the same thing.  The result has length charcount + 1 the last character being 0.

**Comment by Alexey-T** [comment]
So my fix is Delphi compat.

**Comment by pyscripter** [comment]
I suppose so.

**Comment by pyscripter** [comment]
See https://en.delphipraxis.net/topic/1820-ucs4strings/
