### ISSUE TITLE
Range 0..16000

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#90]
This range is in about 6 places. in PythonEngine. Why this const? maybe increase it?

**Comment by pyscripter** [comment]
Not sure where this came from, possibly from python.h.  But there is no need to increase it.  PPAnsichar and PPWideChar are used to store program arguments.  I will see whether they can be replaced with PAnsiChar^, PWideChar^

**Comment by pyscripter** [comment]
Removed all used {$PointerMath on}  Should be on by default in FPC.
@Alexey-T Please review the change and test.

**Comment by Alexey-T** [comment]
Seems OK
