### ISSUE TITLE
Refactor?

### ISSUE THREAD

**Issue by Alexey-T** [pyscripter/python4delphi#91]
```
        if not (m   in [1..12]) or
           not (d   in [1..31]) or
           not (h   in [0..23]) or
           not (mi  in [0..59]) or
           not (sec in [0..59]) or
           not (wd  in [0..6]) or
           not ((jd>=0) and (jd<=366)) or
           not ((dl>=-1) and (dl<=1)) then
```
i suggest to make a func IsInRange(Value, MinValue, MaxValue: integer): boolean; inline;
and call it in all places. `if m in [1..12]` may work slow.

**Comment by pyscripter** [comment]
Set membership is usually highly optimised by the compiler.   I do not think there is any value in replacing it with a function..
