### ISSUE TITLE
Cleaning up the engine after each use

### ISSUE THREAD

**Issue by wooolly** [pyscripter/python4delphi#95]
Currently I execute Python scripts by loading them from a file and using ExecString method part of the Python Engine. I might want to run the Python script multiple times, but have since realised that the Python Engine persists the Python globals from the previous run? This isn't a problem, I guess that's to be expected if you use the same engine.

I free the Python engine and re-create it and call LoadDll to re-initialize the engine after each run. At first I thought this was sufficient, and it seemed to work. However, I'm using DLL's in my Python scripts which are loaded by ctypes, and these DLL connections are not getting cleaned up as expected. I was hoping the freeing of the Python Engine would completely wipe and free everything.

Am I going about this the wrong way? What's the recommended method for cleaning the slate and freeing everything inside the Python interpreter after each execution?

**Comment by Alexey-T** [comment]
Engine has methods to use `locals` and `globals` on run script, so just set another globals/locals and it will be clean python.

**Comment by pyscripter** [comment]
You need to unload the dlls.  See in https://github.com/pyscripter/pyscripter/blob/master/Source/cInternalPython.pas how pyscripter does it.
