### ISSUE TITLE
Importing pip modules like numpy - How do I do This?

### ISSUE THREAD

**Issue by muhammadahmad1999** [pyscripter/python4delphi#96]
Hello.

I would like to import modules such as numpy. I have tried searching the web for the past day but cant seem to find how to do this. Please help!

**Comment by pyscripter** [comment]
You need to call MaskFPUExceptions(True), before loading python or at least before loading Numpy.  See the links below.
```
(* Mask FPU Excptions - Useful for importing SciPy and other Python libs
   See http://bugs.python.org/issue9980 and
   http://stackoverflow.com/questions/3933851/
 *)
  procedure MaskFPUExceptions(ExceptionsMasked : boolean;
  MatchPythonPrecision : Boolean = True);
```

**Comment by muhammadahmad1999** [comment]
> You need to call MaskFPUExceptions(True), before loading python or at least before loading Numpy. See the links below.
> 
> ```
> (* Mask FPU Excptions - Useful for importing SciPy and other Python libs
>    See http://bugs.python.org/issue9980 and
>    http://stackoverflow.com/questions/3933851/
>  *)
>   procedure MaskFPUExceptions(ExceptionsMasked : boolean;
>   MatchPythonPrecision : Boolean = True);
> ```

Thank you very much for your quick reply! I will try this out.

Thank you again!
