### ISSUE TITLE
Pylint and Python 3.8

### ISSUE THREAD

**Issue by wooolly** [pyscripter/python4delphi#97]
I'm currently experiencing issues related to the Pylint library and Python 3.8. I'm posting here since it could be related to python4delphi but not entirely certain.

I execute a Python script using the typical PythonEngine.ExecStrings command, and the Python script imports Pylint. I then cleanup Python after execution and start fresh by freeing, nilling, and recreating the engine (which up to now has worked fine for me). However, if I run the same script 4 times (cleaning up after every execution), it fails to free and nil the engine on the 4th time with the following error...
![Pylint_Python38_AV](https://user-images.githubusercontent.com/9379185/70701316-146bd380-1cc4-11ea-955b-64838a821c48.png)

This only happens for Python 3.8 (no problem with 3.7), I'm using Pylint 2.4.4 (but also tested with 2.3.1 and same thing happened). Also, this only happens on my Windows 10 test VM, and not my actual desktop (same compiled Delphi exe). 

I'm posting here as I thought since the same Python script works fine in Visual Studio Code, it could perhaps be a problem with my Delphi program or python4delphi. I suspect the AV occurs because Python is somehow hanging and not closing properly, though I don't know why this would only happen on the 4th execution.

**Comment by pyscripter** [comment]
It could be related to #95.  When debugging, the Delphi IDE shows which DLLs (or python pyds) are loaded during execution.  Are you unloading all such DLLs?

**Comment by wooolly** [comment]
Is there a way to get the list of currently loaded DLLs rather than the list of load and unload events? It's rather difficult to try and determine which DLLs might still be loaded with so many DLLs being loaded by Python, Pylint, and my own code.

Is there a recommended way to clean up the engine and start fresh with each execution? I currently have this rather sloppy procedure and I'm sure there's a better way of doing it that I'm not aware of...

`procedure ClearEngine;
var
  installed: Boolean;
begin
  installed := PythonInformation.PythonInstalled;
  if (installed and not Executing) then begin
    if (Assigned(PythonEngine)) then begin
      // Clear the globals in the Python interpreter afterwards
      self.ExecuteString('for name in dir():' + sLineBreak +
                                  '  del globals()[name]');
      // Free previous engine
      FreeAndNil(PythonEngine);
    end;
    // Load new engine
    PythonEngine := TPythonEngine.Create(Self);
    PyVersion.AssignTo(PythonEngine);
    PythonEngine.IO := PythonGUIInputOutput;
    PythonEngine.InitScript := InitScript;
    // Assign vars to new python engine
    PylintExistsVar.Engine := PythonEngine;
    // Load DLL
    PythonEngine.LoadDll;
  end;
end;
`
The InitScript string imports pylint if the module is installed for Python (via pip).

**Comment by pyscripter** [comment]
What you are doing sounds fine.  Reloading the python.dll is not fool-proof and in fact it is not recommended.  However it does work in most cases if you unload all python related dlls.

To observe which dlls get loaded I would put a breakpoint before loading the python dll and observe in the debugger events which dlls are loaded.  Similarly for executing python scripts.
