### ISSUE TITLE
Proposition to become part of CrystalScripts

### ISSUE THREAD

**Issue by d-mozulyov** [pyscripter/python4delphi#98]
Hello

I am the author of a well-known library for binding native Delphi code with Lua scripts: https://github.com/d-mozulyov/CrystalLUA

The key feature of the library is to make binding as simple and productive as possible. In addition, work is underway on the Lua fork, which will allow linking of object files and getting rid of dynamic libraries.

Because programming is increasingly moving toward scripting, and besides Lua there are other popular scripting languages, it was decided to rename the CrystalLUA project to CrystalScripts, where in addition to Lua, Python and JavaScript will be supported as well. Quite a large part of the code in the binding analyzes RTTI, this code has been allocated to a separate library: https://github.com/d-mozulyov/Tiny.Rtti

Because our tasks are complex, and the efforts of developers of open source projects are few, I propose to combine our efforts in order to obtain excellent results :wink:

**Comment by pyscripter** [comment]
Good job you have done with Tiny.Rtti!  However, P4D already uses RTTI to expose Delphi objects (see #17) and is compatible to FPC, so there is not any immediate benefit in integrating with Tiny.RTTI.  

However feel free to reuse any of the P4D code in your project.   If the result is better I would be happy to jump into it.
