### ISSUE TITLE
 AttributeError: module 'matplotlib.cbook' has no attribute 'deprecated'

### ISSUE THREAD

**Issue by GitContainer** [pyscripter/python4delphi#99]
When I ran a matplotlib example code ,There always was an error " AttributeError: module 'matplotlib.cbook' has no attribute 'deprecated'".

**Comment by pyscripter** [comment]
And what makes you think this a P4D Issue?  Just google for " AttributeError: module 'matplotlib.cbook' has no attribute 'deprecated'" and see possible solutions.

**Comment by GitContainer** [comment]
There was no error throughout when I ran that .py script on pycharm.But It crashed with p4d on Delphi. When ran line “ ply.show”,Firstly throughout “divided by zero “,then attributeError

On Jan 7, 2020, at 7:17 AM, pyscripter <notifications@github.com> wrote:

﻿

And what makes you think this a P4D Issue? Just google for " AttributeError: module 'matplotlib.cbook' has no attribute 'deprecated'" and see possible solutions.

**Comment by pyscripter** [comment]
You need to call MaskFPUExceptions(True), before loading python or at least before loading Numpy.  See the links below.
```
(* Mask FPU Excptions - Useful for importing SciPy and other Python libs
   See http://bugs.python.org/issue9980 and
   http://stackoverflow.com/questions/3933851/
 *)
  procedure MaskFPUExceptions(ExceptionsMasked : boolean;
  MatchPythonPrecision : Boolean = True);
```

**Comment by GitContainer** [comment]
It works.
Thank you .It helps me a lot.

On Jan 7, 2020, at 12:58 PM, pyscripter <notifications@github.com> wrote:

﻿

You need to call MaskFPUExceptions(True), before loading python or at least before loading Numpy. See the links below.

(* Mask FPU Excptions - Useful for importing SciPy and other Python libs
   See http://bugs.python.org/issue9980 and
   http://stackoverflow.com/questions/3933851/
 *)
  procedure MaskFPUExceptions(ExceptionsMasked : boolean;
  MatchPythonPrecision : Boolean = True);
